refactor(WebSocketShard): payload sending
discordjs/discord.js pull request #10098
Opened 2024-01-23 16:48 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
After consulting with Discord and some conversations in this internal thread (https://canary.discord.com/channels/222078108977594368/1196094076395716608/0), this is the resolution we came up with for those 2 issues.

Fixes #8818, #10089

2024-01-23 19:11 UTC, vladfrangu approved these changes

2024-01-23 19:11 UTC, vladfrangu commented on packages/ws/src/ws/WebSocketShard.ts
> +		if (now > this.sendRateLimitState.resetAt) {
Should we maybe make this `>=`?

2024-01-24 01:18 UTC, Jiralite requested changes

2024-01-24 07:46 UTC, didinele commented on packages/ws/src/ws/WebSocketShard.ts
> -	remaining: number;
yup! just ignore it. it's one of those cases were like, maybe that function and type shouldn't even really be exported and you cannot possibly imagine a world where anyone is using those for a good reason in their code.

it's a price I'm willing to pay

2024-01-25 13:29 UTC, RedGuy12 commented on packages/ws/src/ws/WebSocketShard.ts
> -	remaining: number;
should it be marked deprecated then?

2024-01-25 14:24 UTC, didinele commented on packages/ws/src/ws/WebSocketShard.ts
> -	remaining: number;
no, what good is deprecating a property that is already being removed... I'm just saying that it's so un-important and that if you use this you're doing something so deeply weird I'm willing to compromise "sneaking" a technically breaking change into a minor/patch release.

2024-01-25 17:28 UTC, RedGuy12 commented on packages/ws/src/ws/WebSocketShard.ts
> -	remaining: number;
oh sorry, i meant deprecating the function `getInitialSendRateLimitState()`

2024-02-05 12:04 UTC, SpaceEEC requested changes
Very important, I know.

2024-02-05 13:30 UTC, SpaceEEC approved these changes

2024-02-05 18:40 UTC, kyranet approved these changes

2024-02-05 18:42 UTC, merged