feat(REST): dynamic rate limit offsets
discordjs/discord.js pull request #10099
Opened 2024-01-23 17:23 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
Closes #9762

2024-01-23 19:09 UTC, vladfrangu approved these changes
Up for debate if we should maybe make GetRateLimitOffsetFunction async compat or not, I'd say nah, but otherwise LGTM

2024-01-24 01:31 UTC, Jiralite commented on packages/rest/src/lib/utils/types.ts
> + * A function that determines the ratelimit offset for a given request.
```suggestion
 * A function that determines the rate limit offset for a given request.
```

2024-01-24 10:51 UTC, ckohen requested changes

2024-01-24 10:51 UTC, ckohen commented on packages/rest/src/lib/handlers/SequentialHandler.ts
> +				timeout = offset - Date.now();
```suggestion
				timeout = this.manager.globalReset + offset - Date.now();
```

You removed a bit too much. 👋 Global ratelimit

2024-01-24 10:51 UTC, ckohen commented on packages/rest/src/lib/handlers/SequentialHandler.ts
> +				timeout = offset - Date.now();
```suggestion
				timeout = this.manager.globalReset + offset - Date.now();
```

Ditto

2024-01-24 11:37 UTC, ckohen approved these changes

2024-01-30 09:27 UTC, Jiralite approved these changes

2024-01-30 09:29 UTC, merged