feat(websocket): use proxy for websocket connections
discordjs/discord.js pull request #10149
Opened 2024-02-23 17:03 UTC by NewMeeh

The PR adds a way to use discord.js through a proxy.

I tested it and it works for my configuration. 
I am not sure how to update typings but I'll be happy to do so :) 
This PR adds one parameter but it is optional.
I will also be happy to add some documentation if needed.

2024-02-23 17:40 UTC, almeidx commented
Documentation for this option needs to be added to:
- https://github.com/NewMeeh/discord.js/blob/ce08bca2e16537cf537c8e987db79d9fdc7e97f0/packages/discord.js/src/util/Options.js#L87
- https://github.com/NewMeeh/discord.js/blob/ce08bca2e16537cf537c8e987db79d9fdc7e97f0/packages/discord.js/typings/index.d.ts#L6779

2024-02-24 12:03 UTC, didinele requested changes
The key problem here is that your new agent option is not serializable over `worker_thread`s. This completely breaks the worker sharding strategy.

2024-02-24 16:50 UTC, NewMeeh commented
@didinele I see the problem. I don't really know how threads works in Javascript, if there's no way to share the agent option between threads, should I construct the `agent` inside the `WebSocketShard` but this means adding a dependency 🤷‍♂️

2024-03-04 16:07 UTC, didinele commented
I'm not confident we should go forward with this. Thoughts? @vladfrangu

2024-03-04 17:41 UTC, didinele commented
Yeah. Frankly, if the agent API was universal and we found a nice interface for users to pass an instance even in worker mode, I'd be a lot more in favor of this, but as it is it feels whacky at best.

2024-03-30 00:01 UTC, NotSugden commented on packages/ws/src/ws/WebSocketShard.ts
> +		const agent = proxy ? new HttpsProxyAgent(proxy, httpsProxyAgentOptions) : undefined;
```suggestion
		const { proxy, httpsProxyAgentOptions } = this.strategy.options.proxyAgentOptions ?? {
			proxy: undefined,
			httpsProxyAgentOptions: undefined,
		};
		const agent = proxy && new HttpsProxyAgent(proxy, httpsProxyAgentOptions);
```

2024-05-04 10:27 UTC, didinele commented
Hi. Especially considering the direction we're taking of ensuring the package works in non-node envs, on top of everything else already discussed in this thread, we won't be going forward with this.

2024-05-04 10:27 UTC, closed without merging