feat(discord.js): added support to setting bot banner
discordjs/discord.js pull request #10176
Opened 2024-03-14 23:31 UTC by MinerPL

**Please describe the changes this PR makes and why it should be merged:**
This PR adds the function of setting the bot's banner through the new `setBanner` function, Discord experiment adding a banner edit field but this is not locked at the API level and the banner is already rendering normally.
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- This PR changes the library's interface (methods or parameters added)

2024-03-14 23:33 UTC, Jiralite commented
[This is not documented](https://discord.com/developers/docs/resources/user#modify-current-user). We only document... documented features.

2024-03-15 17:39 UTC, MinerPL commented
Released a moment ago:
DDevs Post: https://discord.com/channels/613425648685547541/697138785317814292/1218248663869030521
Documentation PR: https://github.com/discord/discord-api-docs/pull/6710

2024-03-15 17:45 UTC, Jiralite requested changes

2024-03-15 17:45 UTC, Jiralite commented on packages/discord.js/src/structures/ClientUser.js
> +   * // Set avatar
```suggestion
   * // Set banner
```

2024-03-15 17:45 UTC, Jiralite commented on packages/discord.js/src/structures/ClientUser.js
> +   * @param {?(BufferResolvable|Base64Resolvable)} banner The new avatar
```suggestion
   * @param {?(BufferResolvable|Base64Resolvable)} banner The new banner
```

2024-03-15 18:17 UTC, almeidx submitted a review, later dismissed

2024-03-15 18:17 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
`banner` is missing in the `ClientUserEditOptions` interface

2024-04-09 14:04 UTC, Jiralite approved these changes

2024-04-09 14:05 UTC, vladfrangu approved these changes

2024-04-09 14:06 UTC, almeidx approved these changes

2024-04-09 14:09 UTC, merged