feat(Guild): Add `bulkBan()` method
discordjs/discord.js pull request #10182
Opened 2024-03-19 11:25 UTC by codershiba

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2024-03-19 13:35 UTC, GoldenAngel2 requested changes

2024-03-19 13:35 UTC, GoldenAngel2 commented on packages/discord.js/src/structures/Guild.js
> +    if (Array.isArray(users) && users instanceof Collection) throw new Error('"users" is not an array');
This is doing nothing...? 
'users' can't be an array and collection at the same time...

2024-03-19 13:35 UTC, GoldenAngel2 commented on packages/discord.js/src/structures/Guild.js
> +    if (userIds.length === 0) return new Collection();
Why return a new collection and not an error?

2024-03-19 14:50 UTC, GoldenAngel2 requested changes

2024-03-19 14:50 UTC, GoldenAngel2 commented on packages/discord.js/src/managers/GuildBanManager.js
> +    if (Array.isArray(users) || users instanceof Collection) throw new Error('"users" is not an array');
```suggestion
    if (!Array.isArray(users) && !(users instanceof Collection)) throw new Error('"users" is not an array or collection');
```
should fix this line.

2024-03-19 19:01 UTC, jaw0r3k commented
the users field is always required so it would be better to move it outside as the interface as a separate parameter

2024-03-19 19:08 UTC, jaw0r3k commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * both the `BAN_MEMBERS` and `MANAGE_GUILD` permissions.
Delete the permissions info as it is not a thing we do

2024-03-19 19:10 UTC, jaw0r3k commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * guild.bans.bulk({ users: ['84484653687267328'], deleteMessageSeconds: 604_800 })
```suggestion
   * guild.bans.bulk({ users: ['84484653687267328'], deleteMessageSeconds: 24 * 60 * 60 })
```

Magic numbers arent very nice

2024-03-19 20:14 UTC, sdanialraza commented on packages/discord.js/src/managers/GuildBanManager.js
> +  async bulk(users, options) {
I think it should be bulkCreate, just bulk seems weird, and maybe <GuildMemberManager>.bulkBan() that calls bulkCreate internally?

2024-03-20 12:34 UTC, vladfrangu requested changes

2024-03-20 12:34 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildBanManager.js
> +  async bulkCreate(users, options) {
Let's make options optional, no reason to have to pass in an object and leave it empty

2024-03-20 12:34 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildBanManager.js
> +    let userIds = users instanceof Collection ? [...users.keys()] : users.map(user => user.id ?? user);
Can be const

2024-03-20 12:34 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildBanManager.js
> +    }
These errors should probably be defined like the rest of the errors in our custom error classes

2024-03-20 12:41 UTC, almeidx requested changes

2024-03-20 12:41 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @param {Collection<Snowflake, User>|UserResolvable[]} users The users to ban
The Collection should also accept `UserResolvable` instead of just `User` imo

2024-03-20 12:41 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +    let userIds = users instanceof Collection ? [...users.keys()] : users.map(user => user.id ?? user);
```suggestion
const userIds = users.map(user => this.client.users.resolveId(user));
```

2024-03-20 12:41 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +      body: { user_ids: userIds, delete_message_seconds: options.deleteMessageSeconds ?? undefined },
```suggestion
      body: { user_ids: userIds, delete_message_seconds: options.deleteMessageSeconds },
```

2024-03-20 19:05 UTC, Qjuh commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * Ban up to 200 users from a guild, and optionally delete previous messages sent by the banned users.
We don’t usually write the limits of the API into the JSDoc and even less do we check the size of what we pass to the API before. The API will error itself anyway. But if discord changes those limits we‘d fail unnecessarily here and the docs would be wrong too.

2024-03-20 19:06 UTC, Qjuh commented on packages/discord.js/src/managers/GuildBanManager.js
> +    if (userIds.length > 200) throw new DiscordjsError(ErrorCodes.BulkBanUsersLimitExceeded);
Shouldn’t be checked, see above.

2024-03-20 20:00 UTC, codershiba commented on packages/discord.js/src/errors/ErrorCodes.js
> + * @property {'BulkBanUsersLimitExceeded'} BulkBanUsersLimitExceeded
```suggestion
```

2024-03-20 20:01 UTC, codershiba commented on packages/discord.js/src/errors/ErrorCodes.js
> +  'BulkBanUsersLimitExceeded',
```suggestion
```

2024-03-20 20:01 UTC, codershiba commented on packages/discord.js/src/errors/Messages.js
> +  [DjsErrorCodes.BulkBanUsersLimitExceeded]: 'A maximum of 200 users can be passed as the "users" parameter',
```suggestion
```

2024-03-20 20:01 UTC, codershiba commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * Ban up to 200 users from a guild, and optionally delete previous messages sent by the banned users.
```suggestion
   * Bulk ban users from a guild, and optionally delete previous messages sent by the banned users.
```

2024-03-20 20:02 UTC, codershiba commented on packages/discord.js/src/managers/GuildBanManager.js
> +    if (userIds.length > 200) throw new DiscordjsError(ErrorCodes.BulkBanUsersLimitExceeded);
```suggestion
```

2024-03-20 20:04 UTC, codershiba commented on packages/discord.js/typings/index.d.ts
> +    users: ReadonlyCollection<Snowflake, User | Resolvable> | readonly UserResolvable[],
```suggestion
    users: ReadonlyCollection<Snowflake, UserResolvable> | readonly UserResolvable[],
```

2024-03-20 20:04 UTC, codershiba commented on packages/discord.js/typings/index.d.ts
> +    options: BanBulkOptions,
```suggestion
    options?: BanBulkOptions,
```

2024-03-20 20:05 UTC, codershiba commented on packages/discord.js/typings/index.d.ts
> +    options: BanBulkOptions,
```suggestion
    options?: BanBulkOptions,
```

2024-03-20 20:05 UTC, codershiba commented on packages/discord.js/typings/index.d.ts
> +    options: BanBulkOptions,
```suggestion
    options?: BanBulkOptions,
```

2024-03-20 20:06 UTC, codershiba commented on packages/discord.js/src/managers/GuildMemberManager.js
> +  bulkBan(users, options) {
```suggestion
  bulkBan(users, options = {}) {
```

2024-03-20 20:06 UTC, codershiba commented on packages/discord.js/src/managers/GuildMemberManager.js
> +   * Ban up to 200 users from a guild, and optionally delete previous messages sent by the banned users.
```suggestion
   * Bulk ban users from a guild, and optionally delete previous messages sent by the banned users.
```

2024-03-21 17:30 UTC, almeidx requested changes

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +    }
```suggestion
    if (!users || (!Array.isArray(users) && !(users instanceof Collection))) {
      throw new DiscordjsTypeError(ErrorCodes.InvalidType, typeof users, 'array or collection', true);
    }
    if (typeof options !== 'object') throw new DiscordjsTypeError(ErrorCodes.InvalidType, 'options', 'object', true);
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +          (options.deleteMessageDays ? options.deleteMessageDays * 24 * 60 * 60 : undefined),
IMO there's no reason to add support for a deprecated option (`deleteMessageDays`) to a new method

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/errors/Messages.js
> +    `The type of "users" option is of type: ${type}; expected ${expected}.`,
```suggestion
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/errors/ErrorCodes.js
> +  'BulkBanUsersOptionInvalid',
```suggestion
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/errors/ErrorCodes.js
> + * @property {'BulkBanUsersOptionInvalid'} BulkBanUsersOptionInvalid
```suggestion
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * Bulk ban users from a guild, and optionally delete previous messages sent by the banned users.
```suggestion
   * Bulk ban users from a guild, and optionally delete previous messages sent by them.
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @param {Collection<Snowflake, User|UserResolvable>|UserResolvable[]} users The users to ban
`User` is a `UserResolvable`
```suggestion
   * @param {Collection<Snowflake, UserResolvable>|UserResolvable[]} users The users to ban
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @returns {Promise<BanBulkResult>} Returns an object with `bannedUsers` key containing the IDs of the banned users
This has not been resolved

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildMemberManager.js
> +   * @param {Collection<Snowflake, User|UserResolvable>|UserResolvable[]} users The users to ban
```suggestion
   * @param {Collection<Snowflake, UserResolvable>|UserResolvable[]} users The users to ban
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/src/managers/GuildMemberManager.js
> +   * Bulk ban users from a guild, and optionally delete previous messages sent by the banned users.
```suggestion
   * Bulk ban users from a guild, and optionally delete previous messages sent by them.
```

2024-03-21 17:30 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +    users: ReadonlyCollection<Snowflake, User | UserResolvable> | readonly UserResolvable[],
```suggestion
    users: ReadonlyCollection<Snowflake, UserResolvable> | readonly UserResolvable[],
```

2024-03-21 20:25 UTC, almeidx requested changes

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +    if (!users) throw new DiscordjsError(ErrorCodes.BulkBanUsersOptionRequired);
```suggestion
```

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @typedef {object} BanBulkResult
```suggestion
   * @typedef {Object} BanBulkResult
```

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * Result returned from bulk banning users from a guild.
```suggestion
   * Result of bulk banning users from a guild.
```

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/src/managers/GuildMemberManager.js
> +
You only have to define these once.
```suggestion
```

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +    options?: BanOptions,
```suggestion
    options?: BanBulkOptions,
```

2024-03-21 20:25 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +    options?: BanOptions,
```suggestion
    options?: BanBulkOptions,
```

2024-03-29 23:54 UTC, NotSugden commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @typedef {Object} BanBulkOptions
can we call it BulkBanOptions?

2024-03-29 23:54 UTC, NotSugden commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @property {string} [reason] The reason for the ban
reason for the ban or bans? we are banning multiple people

2024-03-29 23:54 UTC, NotSugden commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * @typedef {Object} BanBulkResult
BulkBanResult?

2024-03-29 23:54 UTC, NotSugden commented on packages/discord.js/src/managers/GuildBanManager.js
> +   * // Bulk ban users by ids (or with user/guild member objects)
```suggestion
   * // Bulk ban users by ids (or with user/guild member objects) and delete all their messages from the past 7 days
```

probably you can come up with something better

2024-03-29 23:54 UTC, NotSugden commented on packages/discord.js/src/managers/GuildMemberManager.js
> +   * // Bulk ban users by ids (or with user/guild member objects)
same as previous

2024-03-30 19:00 UTC, almeidx requested changes

2024-04-01 20:11 UTC, Qjuh approved these changes

2024-04-01 20:19 UTC, almeidx approved these changes

2024-04-01 21:28 UTC, SpaceEEC approved these changes

2024-04-01 21:47 UTC, kyranet requested changes
Just one thing, LGTM otherwise

2024-04-01 21:47 UTC, kyranet commented on packages/discord.js/src/managers/GuildBanManager.js
> +    if (!users || (!Array.isArray(users) && !(users instanceof Collection))) {
Little De Morgan law here
```suggestion
    if (!users || !(Array.isArray(users) || users instanceof Collection)) {
```

2024-04-02 19:38 UTC, kyranet approved these changes

2024-04-02 19:38 UTC, merged