Update index.d.ts
discordjs/discord.js pull request #10265
Opened 2024-05-10 14:04 UTC by fronkdev

**Please describe the changes this PR makes and why it should be merged:**
Added 'defaultValues' typings on ChannelSelectMenuComponentData, RoleSelectMenuComponentData, and UserSelectMenuComponentData.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

2024-05-10 15:13 UTC, Jiralite requested changes

2024-05-10 15:13 UTC, Jiralite commented on packages/discord.js/typings/index.d.ts
>  export interface MentionableSelectMenuComponentData extends BaseSelectMenuComponentData {
You missed this one!

2024-05-10 16:28 UTC, vladfrangu approved these changes

2024-05-11 08:43 UTC, kyranet approved these changes

2024-05-13 13:18 UTC, benjGam approved these changes

2024-05-13 13:22 UTC, Jiralite approved these changes

2024-05-13 13:29 UTC, merged