fix(Message): properly compare `attachments` and `embeds`
discordjs/discord.js pull request #10282
Opened 2024-05-18 08:27 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
This properly compares `attachments` and `embeds` properties instead of just comparing the lengths.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-05-19 09:55 UTC, vladfrangu approved these changes

2024-05-19 10:33 UTC, Jiralite approved these changes

2024-05-19 10:33 UTC, Jiralite commented on packages/discord.js/src/structures/Message.js
> +      this.attachments.every(attachment => message.attachments.get(attachment.id)) &&
Just being semantic:

```suggestion
      this.attachments.every(attachment => message.attachments.has(attachment.id)) &&
```

2024-05-24 12:37 UTC, kyranet requested changes

2024-05-24 12:37 UTC, kyranet commented on packages/discord.js/src/structures/Message.js
> +      this.embeds.every((embed, index) => embed.equals(message.embeds[index]));
The length checks must be preserved, as it would otherwise compare arrays of different length.

2024-05-24 14:13 UTC, kyranet approved these changes

2024-05-24 14:19 UTC, merged