feat: Premium buttons
discordjs/discord.js pull request #10353
Opened 2024-06-18 08:58 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**

- https://github.com/discord/discord-api-docs/pull/6875

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-06-21 20:09 UTC, vladfrangu approved these changes

2024-06-27 19:12 UTC, SpaceEEC approved these changes

2024-06-27 19:48 UTC, almeidx requested changes

2024-06-27 19:48 UTC, almeidx commented on packages/formatters/src/formatters.ts
> +): string {
The other formatter functions return strict template literal types, so perhaps this one should too

2024-06-27 19:48 UTC, almeidx commented on packages/discord.js/src/structures/interfaces/InteractionResponses.js
> +   * @deprecated Sending a premium-style button is the new Discord behaviour.
Missing in the typings

2024-06-27 21:57 UTC, almeidx approved these changes

2024-06-28 06:07 UTC, kyranet approved these changes

2024-07-04 18:53 UTC, suneettipirneni approved these changes

2024-07-04 18:57 UTC, merged