chore: remove all deprecated props
discordjs/discord.js pull request #10421
Opened 2024-07-31 11:56 UTC by didinele

2024-08-01 08:35 UTC, nsgpriyanshu reviewed
It's looks good

2024-08-04 11:33 UTC, vladfrangu approved these changes

2024-10-01 16:38 UTC, Jiralite approved these changes

2024-10-02 19:56 UTC, almeidx requested changes

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/index.js
>  exports.InviteGuild = require('./structures/InviteGuild');
This should be removed too:
https://github.com/discordjs/discord.js/blob/9aed9414c080ea7cbe0cec407d9a71bef903c7d5/packages/discord.js/typings/rawDataTypes.d.ts#L151

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/index.js
>  exports.ChannelSelectMenuInteraction = require('./structures/ChannelSelectMenuInteraction');
I guess this TODO can be resolved now:
https://github.com/discordjs/discord.js/blob/9aed9414c080ea7cbe0cec407d9a71bef903c7d5/packages/discord.js/typings/index.d.ts#L2898

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/structures/interfaces/InteractionResponses.js
Can't comment on the method for some reason (`sendPremiumRequired`), but there are 5 different places where this method is still in

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/managers/GuildBanManager.js
>     * @typedef {Object} BanOptions
With the removal of `deleteMessageDays`, `BulkBanOptions` is equivalent to `BanOptions`. Perhaps we should remove one of them

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/errors/ErrorCodes.js
>   * @property {'ShardingNoShards'} ShardingNoShards
Again, can't comment on the deleted lines but `BitFieldInvalid` wasn't deprecated and is in fact still being used.

Additionally, every other code above this line is still in the javascript array (below), and still have a Message set.

2024-10-02 19:56 UTC, almeidx commented on packages/discord.js/src/client/actions/WebhooksUpdate.js
>  'use strict';
Remove the TODO comment from L12

2024-10-03 20:25 UTC, almeidx approved these changes

2024-10-04 10:20 UTC, ckohen requested changes

2024-10-04 10:20 UTC, ckohen commented on packages/discord.js/src/structures/StringSelectMenuBuilder.js
> +   * @param {StringSelectMenuOptionData|APISelectMenuOption} selectMenuOption The option to normalize
The first of these types doesn't exist, and never seemed to? Can't find anything easily in history to figure out what it was.

2024-10-04 10:20 UTC, ckohen commented on packages/discord.js/src/structures/interfaces/InteractionResponses.js
> -  async sendPremiumRequired() {
Since you did another test, this is currently used in the monetization test.

2024-10-04 10:23 UTC, ckohen commented on packages/discord.js/typings/index.d.ts
> -  BitFieldInvalid = 'BitFieldInvalid',
Accidentally removed this too

2024-10-04 10:42 UTC, ckohen approved these changes

2024-10-04 11:17 UTC, merged