refactor(actions): safer getChannel calls
discordjs/discord.js pull request #10434
Opened 2024-08-07 16:55 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
Fixes #10393 and also does a little spring cleaning on areas that could have also been dangerous in the same way.

The gist of #10393 was that it was especially happening when a message sent unarchived a thread, and yet it only *sometimes* caused the error. It seems that sometimes, Discord was sending the `MESSAGE_CREATE` payload before the `THREAD_UPDATE`. The latter normally comes first and populates our cache, which yields to the subsequent `getChannel` caused by the `MESSAGE_CREATE` to return from cache.

In cases when the opposite was happening, before #10278 we were unable to resolve the channel type and would simply skip it, not adding it to cache at all (and also skipping the messageCreate) as a result. **This is a fundamental flaw of how those partials work, and should be addressed with either the next version, or the library's rewrite**. There is no easy way to fix this.

After #10278, we were essentially passing full message objects from `MESSAGE_CREATE` to `getChannel`, messages, which, have a `type` property, often `0`, which lead to a successful channel creation with jank data.

With this fix, we're back to the old behavior of dropping those events.

2024-08-09 07:34 UTC, kyranet approved these changes

2024-08-15 09:21 UTC, Qjuh requested changes

2024-08-15 09:21 UTC, Qjuh commented on packages/discord.js/src/client/actions/MessageReactionAdd.js
> +    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id, user_id: data.user_id });
Channels have no user_id
```suggestion
    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id });
```

2024-08-15 09:21 UTC, Qjuh commented on packages/discord.js/src/client/actions/MessageReactionRemove.js
> +    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id, user_id: data.user_id });
Same
```suggestion
    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id });
```

2024-08-15 09:53 UTC, didinele commented on packages/discord.js/src/client/actions/MessageReactionAdd.js
> +    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id, user_id: data.user_id });
https://github.com/discordjs/discord.js/blob/432e9b8425311f132e3970d238005c1166215dbb/packages/discord.js/src/client/actions/Action.js#L36

2024-08-15 09:57 UTC, Qjuh commented on packages/discord.js/src/client/actions/MessageReactionAdd.js
> +    const channel = this.getChannel({ id: data.channel_id, guild_id: data.guild_id, user_id: data.user_id });
Oh true, my bad…

2024-08-15 09:58 UTC, Qjuh approved these changes

2024-08-15 10:52 UTC, vladfrangu approved these changes

2024-08-19 19:48 UTC, SpaceEEC approved these changes

2024-08-19 19:53 UTC, merged