test: replace jest with vitest
discordjs/discord.js pull request #10472
Opened 2024-09-02 13:00 UTC by nyapat

**Please describe the changes this PR makes and why it should be merged:**

This is to update voice to use vitest instead of jest. It was ignored previously because the mocks are annoying to convert.
The tests compile and pass as shown by the CI.

**Status and versioning classification:**

2024-09-09 07:27 UTC, vladfrangu commented
Can you try to rebase your PR? Just start the rebase, and every time you get a merge issue on pnpm-lock.yaml, just run `pnpm i`. It'll solve itself

2024-09-09 07:30 UTC, vladfrangu submitted a review, later dismissed
Can you add a vitest config file for this too 🙏 Personally don't like relying on defaults

2024-09-09 12:55 UTC, vladfrangu commented
Turns out only rest has a custom vitest.config.ts file 🥴. It's fine as is 🫡

2024-09-11 08:18 UTC, vladfrangu requested changes

2024-09-11 08:18 UTC, vladfrangu commented on packages/voice/package.json
> +		"@favware/cliff-jumper": "^3.0.3",
revert this downgrade

2024-09-11 08:18 UTC, vladfrangu commented on packages/voice/package.json
> +		"@types/node": "16.18.105",
bump to 18

2024-09-13 13:20 UTC, vladfrangu approved these changes

2024-09-13 13:20 UTC, vladfrangu commented on packages/voice/__tests__/Secretbox.test.ts
>  test('Does not throw error with a package installed', () => {
Well this test is wrong now, should probably adjust / delete

2024-09-13 13:49 UTC, HigherOrderLogic commented on packages/voice/vitest.config.ts
> +export default defaultConfig;
Maybe consider [Vitest workspace](https://vitest.dev/guide/workspace)? It has supports for extending config without having to import the base config into each file.

Example:
```ts
// vitest.workspace.ts at root
import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  'packages/*',
  {
    extends: './vite.config.js',
  }
])
```

2024-10-04 09:24 UTC, didinele approved these changes

2024-10-04 10:56 UTC, kyranet approved these changes

2024-10-04 11:06 UTC, didinele commented
Once rebased this will be automatically merged.

2024-10-04 11:17 UTC, almeidx commented on packages/voice/package.json
>  		"mock-socket": "^9.3.1",
This dependency and its associated file can be removed as well
 https://github.com/nyapat/discord.js/blob/16390efe6e4f2035aa0fe365c8d593366beca7ce/packages/voice/__mocks__/ws.js

2024-10-06 14:17 UTC, iCrawl approved these changes

2024-10-06 14:26 UTC, merged