feat: add subscriptions
discordjs/discord.js pull request #10486
Opened 2024-09-05 15:16 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
Adds subscriptions for core and discord.js

- [x] core
- [ ] discord.js

Depends on changes from:
- https://github.com/discordjs/discord-api-types/pull/1078

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2024-10-01 16:43 UTC, Jiralite submitted a review, later dismissed

2024-10-01 16:43 UTC, Jiralite commented on packages/core/src/api/monetization.ts
> +	 * Fetches the subscriptions for a SKU.
```suggestion
	 * Fetches the subscriptions for an SKU.
```

2024-10-01 16:43 UTC, Jiralite commented on packages/core/src/api/monetization.ts
> +	 * Fetches the subscription for a SKU.
```suggestion
	 * Fetches the subscription for an SKU.
```

2024-10-02 19:34 UTC, almeidx requested changes
The new subscription events need to be added here

https://github.com/sdanialraza/discord.js/blob/f5761a9593ff6c691d0c752db2f97fd25dc46f7d/packages/core/src/client.ts#L96

2024-10-03 20:53 UTC, almeidx requested changes

2024-10-03 20:53 UTC, almeidx commented on packages/core/src/api/monetization.ts
> +		subscriptionId: Snowflake,
Missing in the TSDoc

2024-10-04 15:45 UTC, almeidx approved these changes

2024-10-04 15:45 UTC, almeidx commented on packages/core/src/api/monetization.ts
> +	 * Fetches the subscription for an SKU.
```suggestion
	 * Fetches a subscription for an SKU.
```

2024-10-04 15:45 UTC, almeidx commented on packages/core/src/api/monetization.ts
> +	 * Fetches the subscriptions for an SKU.
```suggestion
	 * Fetches subscriptions for an SKU.
```

2024-10-10 22:27 UTC, Jiralite approved these changes

2024-11-04 10:43 UTC, vladfrangu approved these changes

2024-11-04 10:48 UTC, merged