refactor: use builders v2 in mainlib
discordjs/discord.js pull request #10529
Opened 2024-10-02 10:37 UTC by didinele

:(

2024-10-02 15:08 UTC, Syjalo requested changes
Bump the version to 15.0.0

2025-02-26 19:00 UTC, Qjuh commented on packages/discord.js/typings/index.test-d.ts
> +  .setEmoji(resolvePartialEmoji('<a:foo:123>'))
This is merely testing the return type of resolveColor, so should just do that. The builder itself gets tested in /builders.

2025-02-26 19:01 UTC, Qjuh commented on packages/discord.js/typings/index.test-d.ts
> +new EmbedBuilder().setColor(resolveColor('#ffffff'));
In context of mainlib discord.js this would be a test for the return type of resolveColor, the builder‘s methods get tested in `@discordjs/builders` already.

the failing test above this one is also redundant.

2025-02-26 19:02 UTC, Qjuh commented on packages/discord.js/src/structures/MessagePayload.js
> +const { ActionRowBuilder } = require('@discordjs/builders');
This should be removed completely, since we don‘t want to make new builders in resolveBody() anymore and just keep json as is.

2025-02-26 19:53 UTC, Qjuh requested changes

2025-02-26 19:53 UTC, Qjuh commented on packages/discord.js/typings/index.test-d.ts
> +  .setEmoji(resolvePartialEmoji('😏'))
If this will be the recommended way to do that in mainlib then the `resolvePartialEmoji` function should either be renamed to something easier and/or at least not be marked as private/internal in https://github.com/discordjs/discord.js/blob/39eadce9cbf28de9e8217056bc6aef41032f2ab9/packages/discord.js/src/util/Util.js#L115 and https://github.com/discordjs/discord.js/blob/39eadce9cbf28de9e8217056bc6aef41032f2ab9/packages/discord.js/typings/index.d.ts#L3406-L3408 anymore.

2025-02-26 19:55 UTC, didinele commented on packages/discord.js/typings/index.test-d.ts
> +  .setEmoji(resolvePartialEmoji('😏'))
Yeah for sure, all though for unicode emotes you can also do `{ name: '<emote>' }` very easily (on the topic of recommendations)

2025-02-27 15:37 UTC, didinele commented on packages/discord.js/src/structures/MessagePayload.js
> -      (isJSONEncodable(component) ? component : new ActionRowBuilder(component)).toJSON(),
ah okay, I miss-understood initially

2025-02-27 18:25 UTC, Jiralite requested changes

2025-02-27 18:25 UTC, Jiralite commented on packages/discord.js/src/util/Components.js
There are still imports to this file in ActionRow.js and Message.js.

2025-02-27 22:17 UTC, Jiralite commented
It seems there's a circular dependency somewhere:

`import "discord.js";`

```
(node:41103) Warning: Accessing non-existent property 'createComponent' of module exports inside circular dependency
```

2025-02-28 08:34 UTC, didinele commented
> It seems there's a circular dependency somewhere:

should be fixed

2025-02-28 10:00 UTC, Jiralite submitted a review, later dismissed

2025-02-28 10:38 UTC, kyranet approved these changes
🧹

2025-02-28 17:55 UTC, Jiralite commented on packages/discord.js/src/util/Components.js
> -function createComponentBuilder(data) {
Nu-uh.

2025-02-28 17:56 UTC, Jiralite commented on packages/discord.js/src/util/Components.js
> -/**
I think `ComponentData` in the typings is not actually attached to anything in JavaScript. That or in JSDoc, it is a different type.

2025-02-28 18:23 UTC, didinele commented on packages/discord.js/src/util/Components.js
> -/**
> I think ComponentData in the typings is not actually attached to anything in JavaScript. That or in JSDoc, it is a different type.

The type is unused in the typings as well, good catch.

2025-03-01 10:43 UTC, Jiralite approved these changes

2025-03-01 21:32 UTC, vladfrangu submitted a review, later dismissed
After fixing this, it can be merged without needing my approval again 🫡

2025-03-01 21:32 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
> +    | JSONEncodable<APIActionRowComponent<APIActionRowComponentTypes>>
This is a mistake, it would now allow modal components too

2025-03-05 12:32 UTC, didinele commented
After a multitude of internal discussions and attempts, Vlad's request will ultimately be left unresolved for the time being.

2025-03-05 12:34 UTC, merged