fix(GuildScheduledEvent): handle null recurrence_rule
discordjs/discord.js pull request #10543
Opened 2024-10-08 18:00 UTC by Eejit43

**Please describe the changes this PR makes and why it should be merged:**

This PR handles a null `recurrence_rule` value in `GuildScheduledEvent`s. If there is no rule, the value appears to always be null rather than not present.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-10-08 19:22 UTC, almeidx approved these changes

2024-10-08 19:22 UTC, almeidx commented on packages/discord.js/src/structures/GuildScheduledEvent.js
> +    if ('recurrence_rule' in data && data.recurrence_rule) {
```suggestion
    if (data.recurrence_rule) {
```

2024-10-09 09:33 UTC, Jiralite requested changes
When the recurrence rule is removed, Discord will send `null`. This means the proposed condition change will result in `false` where it goes to the `else` clause where nothing happens. The cached scheduled event is not updated and will be incorrect.

A proposed fix would be to leave the condition as it is and instead do this:

```JavaScript
this.recurrenceRule = data.recurrenceRule && {...};
```

When `null` is received, it will be correctly set to `null`.

2024-10-11 04:24 UTC, vladfrangu approved these changes

2024-10-11 04:24 UTC, merged