refactor(InteractionResponses): Deprecate ephemeral response option
discordjs/discord.js pull request #10574
Opened 2024-10-23 09:35 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Deprecates the `ephemeral` option due to #10564.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2024-10-23 14:49 UTC, kyranet approved these changes

2024-10-23 17:13 UTC, vladfrangu approved these changes

2024-10-23 18:05 UTC, almeidx requested changes

2024-10-24 10:29 UTC, Jiralite commented on packages/discord.js/src/util/MessageFlagsBitField.js
> + * @typedef {string|number|MessageFlagsBitField|MessageFlagsResolvable[]} MessageFlagsResolvable
Should be done with 57b97f73f2bb06933470ed79e72a8d83efc5d7a6.

2024-10-25 08:13 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +  >;
Still not ideal to have this entire thing show up in the docs, but it can be address in another pull request (if at all)

2024-10-25 08:13 UTC, almeidx approved these changes

2024-10-25 08:15 UTC, merged