fix(ThreadChannel): Address parameter type on `fetchOwner()`
discordjs/discord.js pull request #10579
Opened 2024-10-24 23:14 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Resolves #10578.

In addition, this method cannot return `null`, so the typings and documentation had `null` removed (remnant of #10421).

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-10-25 09:54 UTC, vladfrangu approved these changes

2024-10-28 15:08 UTC, didinele approved these changes

2024-11-05 21:46 UTC, almeidx requested changes

2024-11-05 21:46 UTC, almeidx commented on packages/discord.js/src/structures/ThreadChannel.js
> +   * Options used to fetch a thread member owner.
```suggestion
   * Options used to fetch a thread owner.
```

2024-11-05 22:14 UTC, almeidx approved these changes

2024-11-05 22:19 UTC, merged