types(GuildAuditLogEntry): Fix some incorrect types
discordjs/discord.js pull request #10591
Opened 2024-11-05 22:00 UTC by cobaltt7

**Please describe the changes this PR makes and why it should be merged:**

Fixes some audit log types and runtime logic.
 - The target of `MessageBulkDelete` is a channel, not a guild
   - Runtime logic already resolved it as a channel
   - The types weren't resolving `MessageBulkDelete` properly anyway, they previously checked the action type (i.e. `"Update"` or `"Create"`) instead of the actual action
   - It also doesn't have a `options.channel_id`, so I stopped `.extra.channel` from being set to `{ id: undefined }`
 - AutoModeration trigger logs have the violating `User` as a target, not the `AutoModerationRule`
   - Fixed runtime logic here, it previously created a broken `AutoModerationRule`
 - `GuildOnboardingCreate` and `GuildOnboardingUpdate` do not have any target
   - Removed `Targets.GuildOnboarding`, it will fallback to `Targets.Unknown` and generate a placeholder `target` from the `changes`
   - Added a note to the types mentioning them and other events that do not have targets
 - Handle `SoundboardSound` as much as possible right now, add placeholders for after #10590
 - Properly type the values of the `GuildAuditLogsEntry.Target` static object
   - Previously was typed as:
      ```js
      {
        Guild: "Guild" | "Channel" | "User" | ...;
        Channel: "Guild" | "Channel" | "User" | ...;
        User: "Guild" | "Channel" | "User" | ...;
        ...
      }
      ```
      Instead of:
      ```js
      {
        Guild: "Guild";
        Channel: "Channel";
        User: "User";
        ...
      }
      ```
 - `"All"` is never a possible target type, only a possible action type
 - Include `PartialUser` in the types where a partial user is possible
 - Hardcode `Role` and `Emoji` targets

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-11-15 14:30 UTC, Jiralite commented
Please resolve conflicts!

2024-11-17 20:21 UTC, cobaltt7 commented
Resolved conflicts and removed the overlapping changes. Sorry, I hadn't realized that PR existed!

2025-01-12 20:15 UTC, SpaceEEC approved these changes

2025-01-13 10:10 UTC, vladfrangu approved these changes

2025-01-24 09:03 UTC, didinele approved these changes

2025-01-24 19:25 UTC, almeidx requested changes

2025-01-24 19:25 UTC, almeidx commented on packages/discord.js/src/structures/GuildAuditLogsEntry.js
> +    if (target >= 143 && target <= 145) return Targets.User;
We already know the first conditions are true at this point.
Also updated to use `<` to more or less keep the pattern that was being followed on this method.

```suggestion
    if (target < 143) return Targets.AutoModeration;
    if (target < 146) return Targets.User;
```

2025-01-26 02:30 UTC, cobaltt7 commented on packages/discord.js/src/structures/GuildAuditLogsEntry.js
> +    if (target >= 143 && target <= 145) return Targets.User;
Thanks @almeidx, fixed

2025-01-26 13:34 UTC, almeidx approved these changes
🤠

2025-01-26 13:48 UTC, merged