feat: add soundboard
discordjs/discord.js pull request #10590
Opened 2024-11-05 18:31 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
Adds soundboard for mainlib

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2024-11-28 11:15 UTC, Jiralite commented
Make sure you modify this to `GuildExpressions`:

https://github.com/discordjs/discord.js/blob/2b0944a92feff02788942d1d9beb7de0d38ac7be/.github/ISSUE_TEMPLATE/01-package_bug_report.yml?plain=1#L110

2025-02-27 17:50 UTC, Qjuh requested changes
Might be worth to add a `get soundboardSound()` to https://github.com/discordjs/discord.js/blob/b6fda781c89a537469edb0ea52f25bcbcc4bed91/packages/discord.js/src/structures/VoiceChannelEffect.js#L50 which can be null if that sound_id is not found in the `this.guild.soundBoards.cache`.

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +   * @property {Snowflake} [emojiId] The emoji id of the soundboard sound
```suggestion
   * @property {?Snowflake} [emojiId] The emoji id of the soundboard sound
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +   * @property {string} [emojiName] The emoji name of the soundboard sound
```suggestion
   * @property {?string} [emojiName] The emoji name of the soundboard sound
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +   * @property {number} [volume] The volume of the soundboard sound, from 0 to 1.
Those three properties are documented to be nullable to unset on edit.
```suggestion
   * @property {?number} [volume] The volume of the soundboard sound, from 0 to 1.
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/src/structures/SoundboardSound.js
> +       * The volume of the soundboard sound
```suggestion
       * The volume of the soundboard sound, from 0 to 1
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/src/client/actions/GuildSoundboardSoundDelete.js
> +class GuildSoundboardSoundDeleteAction extends Action {
Why is this an action? It doesn't get used anywhere but from the websocket handler, so it could just be in the websocket handler like the other events.

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  public fetchDefaultSoundboardSounds(): Promise<Collection<string, SoundboardSound & { soundId: string }>>;
```suggestion
  public fetchDefaultSoundboardSounds(): Promise<Collection<string, SoundboardSound & { soundId: string; guildId: null; guild: null }>>;
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  ): Promise<Collection<Snowflake, Collection<Snowflake, SoundboardSound & { soundId: Snowflake }>>>;
```suggestion
  ): Promise<Collection<Snowflake, Collection<Snowflake, SoundboardSound & { soundId: Snowflake; guildId: Snowflake }>>>;
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  public edit(options?: GuildSoundboardSoundEditOptions): Promise<SoundboardSound & { soundId: Snowflake }>;
```suggestion
  public edit(options?: GuildSoundboardSoundEditOptions): Promise<SoundboardSound & { soundId: Snowflake; guildId: Snowflake }>;
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  public delete(reason?: string): Promise<SoundboardSound & { soundId: Snowflake }>;
```suggestion
  public delete(reason?: string): Promise<SoundboardSound & { soundId: Snowflake; guildId: Snowflake }>;
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  public create(options: GuildSoundboardSoundCreateOptions): Promise<SoundboardSound & { soundId: Snowflake }>;
```suggestion
  public create(options: GuildSoundboardSoundCreateOptions): Promise<SoundboardSound & { soundId: Snowflake; guildId: Snowflake; guild: Guild }>;
```

2025-02-27 17:50 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
> +  public fetch(id: Snowflake, options?: BaseFetchOptions): Promise<SoundboardSound & { soundId: Snowflake }>;
```suggestion
  public fetch(id: Snowflake, options?: BaseFetchOptions): Promise<SoundboardSound & { soundId: Snowflake; guildId: Snowflake; guild: Guild }>;
```

2025-02-27 18:27 UTC, sdanialraza commented on packages/discord.js/src/client/actions/GuildSoundboardSoundDelete.js
> +class GuildSoundboardSoundDeleteAction extends Action {
It's because of the `getSoundboardSound()` method, as Discord only sends the sound and guild ids, so it can be partial. I wasn't sure how I'd go about it, I saw this is how it goes in other actions. They don't get used anywhere either.

2025-03-04 07:48 UTC, didinele commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +    const sound = resolveBase64(resolvedFile.data, 'audio/mp3');
First thing we can do is try to see if `resolvedFile.contentType` is present (only possible for HTTP/URL input), otherwise we need to do one of the following

1. Take it as a required parameter from the user (I wouldn't go this route)
2. `userParam ?? resolvedFile.contentType ?? lazilyLoadedMagicBytesLib()`

2025-03-06 06:11 UTC, Qjuh approved these changes

2025-03-08 19:09 UTC, vladfrangu requested changes

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildManager.js
> +    }
Call this after setting up the listener in the promise, otherwise you may miss events

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildManager.js
> +        timeout.refresh();
Let's always refresh the timeout maybe

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +    const resolvedContentType = contentType ?? resolvedFile.contentType ?? fileTypeMime()(resolvedFile.data)[0];
Should probably assert that you get a content type (maybe one that is also valid?)

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/structures/SoundboardSound.js
> +    }
I'm not saying this so you change it, but I will call out that we should think if we wanna do emojis properly and use the emoji class instead of Discord's inconsistent handling of emojis across different objects.

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/structures/SoundboardSound.js
> +    if (!this.guild) throw new DiscordjsError(ErrorCodes.NotGuildSoundboardSound, 'edited');
This will be a sync error, either mark the function as async or wrap in Promise.reject

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/src/util/Events.js
> +  GuildSoundboardSoundUpdate: 'guildSoundboardSound',
Event doesn't match enum name, why is that

2025-03-08 19:09 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
> +    | (SoundboardSound & { get guild(): Guild; guildId: Snowflake; soundId: Snowflake })
You could make types for this

2025-03-08 19:58 UTC, Qjuh commented on packages/discord.js/src/managers/GuildManager.js
> +    }
We do it the same way in `GuildMemberManager#_fetchMany()` and don’t have an issue, because all of this happens in the same event loop iteration, the ws responses will only be handled after

2025-03-09 23:31 UTC, Jiralite commented on packages/discord.js/src/structures/VoiceChannel.js
> +   * Fires a Voice Channel Effect Send Gateway event.
There is a tag for this: [`@fires`](https://jsdoc.app/tags-fires)

2025-03-18 09:20 UTC, Qjuh commented on packages/discord.js/src/structures/VoiceChannel.js
> +   * @fires Client#voiceChannelEffectSend
This is misleading though. The `@fires` tag indicates that the event might be emitted inside this method. When in reality the event will emit later, when the gateway event reaches our websocket, completely unrelated to this REST call.

2025-04-24 19:48 UTC, didinele approved these changes

2025-04-24 19:48 UTC, didinele commented on packages/discord.js/src/client/Client.js
> +
```suggestion

```
nit

2025-04-24 21:25 UTC, almeidx submitted a review, later dismissed

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +       * The name of the soundboard sound
```suggestion
       * The name of this soundboard sound
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +       * The volume of the soundboard sound, from 0 to 1
```suggestion
       * The volume of this soundboard sound, from 0 to 1
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +       * The guild id of the soundboard sound
```suggestion
       * The guild id of this soundboard sound
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +      this.emojiName ??= null;
We should probably turn this into just an `emoji` prop. Perhaps similar to the one in `WelcomeChannel`

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +   * The timestamp the soundboard sound was created at
```suggestion
   * The timestamp this soundboard sound was created at
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +   * The time the sticker was created at
```suggestion
   * The time this soundboard sound was created at
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +   * A link to the soundboard sound
```suggestion
   * A link to this soundboard sound
```

2025-04-24 21:25 UTC, almeidx commented on packages/discord.js/src/structures/SoundboardSound.js
> +     * The id of the soundboard sound
```suggestion
     * The id of this soundboard sound
```

2025-04-24 22:03 UTC, Jiralite commented on packages/discord.js/src/managers/GuildSoundboardSoundManager.js
> +   * @property {number} [volume] The volume for the soundboard sound, from 0 to 1. Defaults to 1
Is this inclusive of 0, so you can upload mute soundboard sounds? Might be wise to clarify this!

2025-04-24 22:03 UTC, Jiralite commented on packages/discord.js/src/structures/SoundboardSound.js
> +       * The volume of the soundboard sound, from 0 to 1
Can we specify that this is a double? (It is, right?)

2025-04-25 15:44 UTC, vladfrangu submitted a review, later dismissed

2025-04-25 15:44 UTC, vladfrangu commented on packages/discord.js/src/structures/VoiceChannel.js
> +   * @param {SoundboardSound} sound the sound to send
This ideally should also support passing in just an object with those properties and not just the full structure for docs sake

2025-04-25 15:44 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
I might be blind but I don't see where you added sendSound to VoiceChannels 👀, please add that in too 🙏

2025-04-25 15:51 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
Line 3455 you mean?

2025-04-25 15:53 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
![Google Chrome Beta - 2025-04-25 at 18 53 35](https://github.com/user-attachments/assets/beccb858-f7df-4441-bba2-29b451b33c90)
huh

2025-04-25 15:54 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
*new* line 3455

2025-04-25 15:55 UTC, sdanialraza commented on packages/discord.js/typings/index.d.ts
> I might be blind but I don't see where you added sendSound to VoiceChannels 👀, please add that in too 🙏

Yeah, I saw it was missing and added it in [`7b3cfe4` (#10590)](https://github.com/discordjs/discord.js/pull/10590/commits/7b3cfe4c19ab7b84406379fb0ed11c5a17d98237)

2025-04-25 15:56 UTC, Qjuh commented on packages/discord.js/typings/index.d.ts
oh, so review and commit clashed in timing... that's why I was confused

2025-04-25 15:56 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
Now it shows up, Thx github LOL

2025-04-25 19:43 UTC, vladfrangu approved these changes

2025-04-25 19:43 UTC, merged