refactor: consistent use of `resolve` instead of `cache.get() ?? null`
discordjs/discord.js pull request #10626
Opened 2024-11-28 13:38 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
Some places would use `manager.cache.get() ?? null` and some `manager.resolve()`. This updates all instances to consistently use `manager.resolve` instead

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-11-28 13:42 UTC, didinele submitted a review, later dismissed
surely this won't somehow break anything

2024-11-28 16:27 UTC, Jiralite requested changes

2024-11-28 16:27 UTC, Jiralite commented on packages/discord.js/src/managers/ThreadMemberManager.js
> +    if (userResolvable) return super.cache.get(userResolvable);
It looks more appropriate to rename the variable to `userId`.

2024-11-28 16:27 UTC, Jiralite commented on packages/discord.js/src/managers/PresenceManager.js
> +    return super.cache.get(userResolvable) ?? null;
It looks more appropriate to rename the variable to `userId`.

2024-11-28 16:27 UTC, Jiralite commented on packages/discord.js/src/structures/ThreadMember.js
> +    return this.client.users.cache.get(this.id);
```suggestion
    return this.client.users.cache.get(this.id) ?? null;
```

2024-11-28 17:03 UTC, Jiralite approved these changes

2024-11-28 17:07 UTC, vladfrangu approved these changes

2024-11-28 17:07 UTC, vladfrangu commented on packages/discord.js/src/managers/GuildBanManager.js
> +    const _user = this.client.users.cache.get(id) ?? null;
This is one of the cases, like in `packages/discord.js/src/client/actions/ThreadListSync.js`, where you don't need `?? null`

2024-11-28 17:43 UTC, SpaceEEC approved these changes

2024-11-28 17:48 UTC, merged

2025-01-03 22:55 UTC, DJj123dj commented
This change DID indeed break a lot of bots. It might not look like it at a first glance, but the `cache.get()` method only allows ID's/snowflakes. It returns `undefined` when trying to resolve a `Role` or `User` class in the `PermissionOverwrites`.

The param type still allows the `Role` & `User` class to be used even if they aren't processed and will just return `undefined`.

😄 But no worries, in the latest version of discord.js is this code already overwritten/modified & now it works again.

2025-01-03 23:04 UTC, Jiralite commented
Code talks better! What was the issue? I want to understand what you are talking about.

2025-01-04 21:58 UTC, DJj123dj commented
> Code talks better! What was the issue? I want to understand what you are talking about.

Yea, the issue was exactly what is described in pull request #10686 as mentioned by @sdanialraza. The fact that it would return `undefined` when using a `discorde.Role` or `discord.User` in the `id` of the `PermissionOverwrites` instead of a `string` (snowflake)

2025-01-04 22:05 UTC, Jiralite commented
We had decoded your message by then! Please open an issue instead of commenting on pull requests in the future with a reproducible code sample next time.