refactor: standardize export style to named exports
discordjs/discord.js pull request #10630
Opened 2024-12-02 18:36 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
This standardizes the export style across the codebase by replacing default exports with named exports for consistency. It was pointed out internally [here](https://canary.discord.com/channels/222078108977594368/999796393810067607/1312244173671235644). 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2024-12-03 07:02 UTC, vladfrangu requested changes

2024-12-03 07:02 UTC, vladfrangu commented on packages/discord.js/src/client/actions/ActionsManager.js
> +    this.register(require('./ApplicationCommandPermissionsUpdate').ApplicationCommandPermissionsUpdateAction);
This needs to be updated in the generateRequires script, otherwise it will fail the next time we run this file.

2024-12-05 08:29 UTC, vladfrangu approved these changes
Good luck testing this XD

2024-12-05 18:36 UTC, didinele submitted a review, later dismissed

2025-01-18 07:47 UTC, Jiralite approved these changes

2025-01-18 07:58 UTC, vladfrangu approved these changes

2025-01-18 07:58 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/READY.js
> +    ClientUser ??= require('../../../structures/ClientUser').ClientUser;
Should've moved this to lazy() while at it

2025-01-18 08:20 UTC, SpaceEEC approved these changes
🤞

2025-01-18 18:54 UTC, almeidx approved these changes

2025-01-18 18:58 UTC, merged