feat(interactions): add launchActivity method
discordjs/discord.js pull request #10646
Opened 2024-12-08 22:00 UTC by imnaiyar

**Please describe the changes this PR makes and why it should be merged:**
 #10640 but for core

Depends on
- https://github.com/discordjs/discord-api-types/pull/1166

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2025-01-03 11:37 UTC, Jiralite requested changes

2025-01-03 11:37 UTC, Jiralite commented on packages/core/src/api/interactions.ts
> +	 * Launches activity and returns an interaction callback object
```suggestion
	 * Launches an activity and returns an interaction callback object
```

2025-01-03 11:37 UTC, Jiralite commented on packages/core/src/api/interactions.ts
> +	 * Launches activity
```suggestion
	 * Launches an activity
```

2025-01-03 17:17 UTC, Jiralite approved these changes

2025-01-12 19:54 UTC, SpaceEEC requested changes

2025-01-12 19:54 UTC, SpaceEEC commented on packages/core/src/api/interactions.ts
> +	): Promise<undefined>;
This overload will be selected when passing a `RESTPostAPIInteractionCallbackQuery` where `with_response` is `boolean`.
This could be a `true` in runtime and then return resolve to a `RESTPostAPIInteractionCallbackWithResponseResult`.

You could add another overload with `{ with_response: false }` where the function resolves to `undefined` and then the catch-all with an union of both.

2025-01-12 19:58 UTC, Jiralite commented on packages/core/src/api/interactions.ts
> +	): Promise<undefined>;
Adding onto this, it could prove useful to add tests into https://github.com/discordjs/discord.js/blob/main/packages/core/__tests__/types.test.ts.

2025-01-13 11:08 UTC, SpaceEEC approved these changes

2025-01-24 08:54 UTC, didinele approved these changes

2025-01-24 09:11 UTC, merged