refactor(actions): removed unnecessary actions
discordjs/discord.js pull request #10666
Opened 2024-12-27 23:42 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**

Removed actions that were only being used in their
respective websocket handlers. The remaining
actions either were either being used elsewhere or
were using methods from the `GenericAction` class.

**Status and versioning classification:**

2025-01-12 19:40 UTC, SpaceEEC approved these changes

2025-01-13 05:48 UTC, Jiralite approved these changes

2025-01-13 10:21 UTC, vladfrangu requested changes

2025-01-13 10:21 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/AUTO_MODERATION_RULE_CREATE.js
> +  if (guild) return;
```suggestion
  if (!guild) return;
```

2025-01-13 10:21 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/AUTO_MODERATION_RULE_DELETE.js
> +  if (guild) return;
```suggestion
  if (!guild) return;
```

2025-01-13 10:21 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/AUTO_MODERATION_ACTION_EXECUTION.js
> +  if (guild) return;
```suggestion
  if (!guild) return;
```

2025-01-13 10:21 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/AUTO_MODERATION_RULE_UPDATE.js
> +  if (guild) return;
```suggestion
  if (!guild) return;
```

2025-01-13 10:21 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/handlers/PRESENCE_UPDATE.js
> +  if (!user && data.user.username) user = client.users._add(data.user);
https://github.com/discordjs/discord.js/pull/10672

2025-01-13 10:50 UTC, vladfrangu commented
This needs a rebase too

2025-01-13 11:29 UTC, vladfrangu approved these changes

2025-01-13 11:29 UTC, merged