types: add all type for GuildAuditLogsEntry#target
discordjs/discord.js pull request #4738
Opened 2020-08-24 15:24 UTC by tguichaoua

**Please describe the changes this PR makes and why it should be merged:**
fix #4728 

Add `Message`, `GuildChannel` and `{ id: string }` as possible type for `GuildAuditLogsEntry#target`.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-08-24 16:03 UTC, NotSugden requested changes

2020-08-24 16:03 UTC, NotSugden commented on typings/index.d.ts
> +      | { id: string }
```suggestion
      | { id: Snowflake }
```

2020-08-27 14:38 UTC, iCrawl approved these changes

2020-08-27 14:53 UTC, vladfrangu approved these changes

2020-08-27 15:41 UTC, kyranet approved these changes

2020-08-28 12:18 UTC, merged