feat: add includeDefault option to User#avatarURL
discordjs/discord.js pull request #4770
Opened 2020-09-01 02:33 UTC by Tenpi

**Please describe the changes this PR makes and why it should be merged:**
This PR implements one of the ideas from #4767. It merges the functionality of User#displayAvatarURL into User#avatarURL with the option `includeDefault`, which when set to true will return a link to a user's default avatar if they don't have one.
```ts
user.avatarURL({includeDefault: true}) // equals user.displayAvatarURL()
```
It deprecates the method User#displayAvatarURL, which could be removed in the next major version.

The main point of this is to remove the confusion of having two separate avatarURL methods. I also think that it's more consistent with the rest of the methods, because there is `guild.iconURL()` but not `guild.displayIconURL()` for example. 

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [X] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-09-01 02:43 UTC, advaith1 commented
there's no `guild.displayIconURL()` because the guild has no icon by default, the client just shows the acronym text in place of it

2020-09-01 03:06 UTC, monbrey commented
Deprecating a method should use `util.deprecate`, not just the jsdoc flag

2020-09-01 14:47 UTC, devsnek commented
This seems strictly worse.

2020-09-01 14:49 UTC, NotSugden requested changes

2020-09-01 14:49 UTC, NotSugden commented on src/structures/User.js
> +   * @deprecated Use avatarURL() with includeDefault set to true instead.
```suggestion
   * @deprecated
```
consistency with other `@deprecated` tags

2020-09-01 14:49 UTC, NotSugden commented on src/structures/User.js
> +  'User#displayAvatarURL is deprecated! Use User#avatarURL with the option includeDefault instead.',
```suggestion
  'User#displayAvatarURL: Use User#avatarURL with the option includeDefault instead',
```
consistency

2020-09-01 16:54 UTC, Aakodal commented
> This seems strictly worse.

How can this be worse? It's much better for consistency, much clearer than two similar methods, and isn't a horrible breaking change.

2020-09-01 16:54 UTC, Tenpi commented
> This seems strictly worse.

I renamed `includeDefault` to `display` so that it's shorter to type, and isn't much different to the older method.

2020-09-01 16:56 UTC, Aakodal commented
> > This seems strictly worse.
> 
> I renamed `includeDefault` to `display` so that it's shorter to type, and isn't much different to the older method.

In my opinion, newcomers would think that `.avatarURL({displayDefault: true})` would do the same as `.defaultAvatarURL` and not `.displayAvatarURL()`. Why not renaming it by `defaultFallback`, or something like this?

2020-09-01 17:01 UTC, devsnek commented
To be clear there are two goals of djs:

- expose Discord's API data
- abstract logic needed to interact with Discord's API

The current methods seem to do that perfectly. This PR just randomly moves the logic into the presentation options for *??? reasons ???*

2020-09-01 17:07 UTC, Tenpi commented
> In my opinion, newcomers would think that `.avatarURL({displayDefault: true})` would do the same as `.defaultAvatarURL` and not `.displayAvatarURL()`. Why not renaming it by `defaultFallback`, or something like this?

Sorry for being unclear, it's just `display` not `displayDefault`. So now it's like this:
```ts
user.avatarURL({display: true}) // equals user.displayAvatarURL()
```
I think that it's still clear what it does but is shorter than `includeDefault`

2020-09-01 17:10 UTC, tipakA commented
No, `display` is in no way clear what it does. Does it display it in console? does it send it to channel on its own? does it create an embed with it as an image?

The hypotethical newcomer that wouldn't be able to tell difference between `avatarURL` and `displayAvatarURL` basing on the method descriptions, will in no way be able to tell what is `display` supposed to mean.

2020-09-01 17:13 UTC, iCrawl commented
I disagree with this idea on a fundamental level.

2020-09-01 17:18 UTC, Tenpi commented
> No, `display` is in no way clear what it does. Does it display it in console? does it send it to channel on its own? does it create an embed with it as an image?
> 
> The hypotethical newcomer that wouldn't be able to tell difference between `avatarURL` and `displayAvatarURL` basing on the method descriptions, will in no way be able to tell what is `display` supposed to mean.

Nevermind, you are right. I reverted it back to `includeDefault`

2020-09-01 19:14 UTC, HarmoGlace commented
Why don't you name it `ensureDefault` or something like that ?

2020-09-02 19:27 UTC, iCrawl commented
I don't see this happening. Maybe in the next major we'll have a better process of handling this.

2020-09-02 19:27 UTC, closed without merging