feat(GuildMemberManager): throw TypeError on incorrect GuildMemberManager#ban params
discordjs/discord.js pull request #4816
Opened 2020-09-14 00:18 UTC by monbrey

Consistent with the error thrown by `Message#delete()` when passing a number instead of an object, implements the same TypeError to `GuildMemberManager#ban()` and subsequently `GuildMember#ban()` to catch people passing a string instead of an object.

Not sure how to semantically version this.

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-09-14 00:31 UTC, NotSugden requested changes
This would be a breaking change correct? the PR mentioned (#3772) was labelled as semver: major

2020-09-14 00:31 UTC, NotSugden commented on src/managers/GuildMemberManager.js
> +    if (typeof options !== 'object') throw new TypeError('INVALID_TYPE', 'options', 'object', true);
```suggestion
    if (typeof options !== 'object') return Promise.reject(new TypeError('INVALID_TYPE', 'options', 'object', true));
```
this should be Promise.reject, not throw

2020-09-14 09:46 UTC, kyranet approved these changes

2020-09-14 13:59 UTC, vladfrangu approved these changes

2020-11-22 17:17 UTC, vladfrangu approved these changes

2020-11-22 17:18 UTC, SpaceEEC approved these changes

2020-11-22 18:12 UTC, iCrawl approved these changes

2020-11-22 18:13 UTC, merged