fix(typings): return types for 'Webhook(Client)#send()'
discordjs/discord.js pull request #4876
Opened 2020-10-02 09:35 UTC by izexi

As shown below, [`Webhook(Client)#send()`](https://discord.js.org/#/docs/main/stable/class/Webhook?scrollTo=send) would either return a Message (if the client was initiated and the channel was cached) or it would return the raw message response from the API (which has been added as a `APIRawMessage` interface in this PR).
https://github.com/discordjs/discord.js/blob/d2341654fe6ef87c6048bb5bf74c394062f3f618/src/structures/Webhook.js#L162-L164

Cuurently the typings do not reflect this behaviour, this PR fixes that.

I did consider making use of the [`APIMessage`](https://github.com/discordjs/discord-api-types/blob/main/v6/payloads/channel.ts#L53-L81) over on [`discord-api-types`](https://github.com/discordjs/discord-api-types) but that would mean introducing another dependency which be a breaking change for all Typescript developers.

| :warning: This change is breaking for Typescript developers that make use of properties or methods exclusive to a Message and not within the APIRawMessage from the resolved returned value of `Webhook(Client)#send()`. |
| --- |

<details>
<summary>Here's a snippet of how I tested these changes</summary>

```ts
import { expectType } from 'tsd';
import { APIRawMessage, Message, WebhookClient } from 'discord.js';

const webhookClient = new WebhookClient('', '');

expectType<Message | APIRawMessage>(await webhookClient.send('foo'));

expectType<(Message | APIRawMessage)[]>(
  await webhookClient.send('foo', { split: true })
);

expectType<Message | APIRawMessage | (Message | APIRawMessage)[]>(
  await webhookClient.send({ embeds: [] }, { split: true })
);

expectType<Message | APIRawMessage>(
  await webhookClient.send('foo', { embeds: [] })
);

expectType<Message | APIRawMessage | (Message | APIRawMessage)[]>(
  await webhookClient.send('foo', { embeds: [], split: true })
);
```
</details>

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-10-02 09:52 UTC, vladfrangu commented
I don't see how adding a dependency on `discord-api-types` is breaking for TS developers (note: dependency, not dev/peer dep).. 👀

2020-10-02 11:02 UTC, NotSugden requested changes
these overloads should be applied to `WebhookClient` directly, as the `Webhook` class is instantiated by internal methods and always has a client, thus always returns a full message

2020-10-02 11:02 UTC, NotSugden commented on typings/index.d.ts
> +      premium_type?: number;
properties like this wont ever be present i dont think, they're only available using oauth2

2020-10-02 11:02 UTC, NotSugden commented on typings/index.d.ts
> +      bot: boolean;
```suggestion
      bot?: boolean;
```
this is optional, true if present so if you wanted yo be explicit you could do `bot?: true`

2020-10-02 12:26 UTC, izexi commented
> I don't see how adding a dependency on `discord-api-types` is breaking for TS developers (note: dependency, not dev/peer dep).. 👀

@vladfrangu I was assuming that they had to go under `devDependicies` since that's where the other type packages were listed. Although, as mentioned by Sudgen some of the OAuth2 properties wont be present so I could Omit them I guess but I'm not sure about adding it as a dependency just for the `APIMessage`.

--- 
> these overloads should be applied to `WebhookClient` directly, as the `Webhook` class is instantiated by internal methods and always has a client, thus always returns a full message

@NotSugden If the channel isn't within the `ChannelManager#cache` Collection then it would return the raw message, although this isn't possible unless the developer removes the channel manually I believe it should still be accounted for.

2020-12-08 20:28 UTC, iCrawl approved these changes

2020-12-08 21:19 UTC, kyranet commented
> > I don't see how adding a dependency on `discord-api-types` is breaking for TS developers (note: dependency, not dev/peer dep).. 👀
> 
> @vladfrangu I was assuming that they had to go under `devDependicies` since that's where the other type packages were listed. Although, as mentioned by Sudgen some of the OAuth2 properties wont be present so I could `Omit` them I guess but I'm not sure about adding it as a dependency just for the `APIMessage`.

Since we're releasing this for discord.js v13, I personally don't see a reason to not include `discord-api-types`, we can afford semver-major this time.

2020-12-14 13:05 UTC, iCrawl commented
For what its worth: I would like to keep this as is and move forward like this until we have a clear path for modularization.

2020-12-15 08:42 UTC, vladfrangu approved these changes

2020-12-30 10:56 UTC, SpaceEEC approved these changes

2020-12-31 10:35 UTC, kyranet approved these changes

2021-01-22 16:46 UTC, merged