feat: create 'GuildTemplate' & add 'Client#fetchGuildTemplate()'
discordjs/discord.js pull request #4906
Opened 2020-10-15 20:37 UTC by izexi

- Ref: https://github.com/discord/discord-api-docs/pull/1712
 - Adds `DataResolver#resolveGuildTemplateCode()` to resolve template URLs
 - Along with `DataResolver#resolveCode()` to reuse code for the above and the `resolveInviteCode` method
 - Creates a `GuildTemplate` structure with a `createGuild` method to add support for the `POST /guilds/templates/:template_code` endpoint
 - Adds `Client#fetchGuildTemplate()` to support for the `GET /guilds/templates/:template_code` endpoint
 - Resolves #4651 

<details>
<summary>Here's a snippet of how I tested these changes</summary>

```ts
import { once } from 'events';
import { Client, DataResolver, GuildTemplate } from 'discord.js';
import { TEST_TEMPLATE_CODE, TOKEN } from './constants';

const client = new Client();
let createdGuildId;

client.login(TOKEN);

test('DataResolver#resolveGuildTemplateCode()', () => {
  expect(
    DataResolver.resolveGuildTemplateCode(
      'https://discord.com/template/FKvmczH2HyUf'
    )
  ).toBe('FKvmczH2HyUf');

  expect(
    DataResolver.resolveGuildTemplateCode('https://discord.new/FKvmczH2HyUf')
  ).toBe('FKvmczH2HyUf');

  expect(
    DataResolver.resolveGuildTemplateCode('https://discord.invalid/code')
  ).toBe('https://discord.invalid/code');
});

test('Client#fetchGuildTemplate() & GuildTempalte#createGuild()', async () => {
  await once(client, 'ready');

  const template = await client.fetchGuildTemplate(TEST_TEMPLATE_CODE);
  expect(template).toBeInstanceOf(GuildTemplate);

  const createdGuildName = 'foo';
  const guild = await template.createGuild(createdGuildName);
  expect(guild.name).toBe(createdGuildName);

  createdGuildId = guild.id;
});

afterAll(() => client.guilds.cache.get(createdGuildId).delete());
```

</details>

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-10-15 21:13 UTC, NotSugden requested changes

2020-10-15 21:13 UTC, NotSugden commented on src/util/Constants.js
> +    template: 'https://discord.com/template',
there needs to be a jsdoc `@property` tag for this too, and the typings need updating for it

2020-10-15 21:21 UTC, NotSugden requested changes

2020-10-15 21:21 UTC, NotSugden commented on typings/index.d.ts
> +    private _patch(data: object): void;
_patch isn't in the typings at all, would be inconsistent to only have it here

2020-11-14 03:00 UTC, NotSugden requested changes
json error code 10057 unknown template could be added to this PR https://discord.com/developers/docs/topics/opcodes-and-status-codes#json

2020-11-20 19:36 UTC, izexi commented
Closing this PR since its being superseded by #4907 and the referenced API docs PR on there has been merged

2020-11-20 19:36 UTC, closed without merging