Update fetch description
discordjs/discord.js pull request #4920
Opened 2020-10-19 21:19 UTC by anandre

The `fetch` method does not support fetching multiple IDs, so the description is currently inaccurate.

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [X] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-10-19 22:20 UTC, kyranet approved these changes

2020-10-19 22:22 UTC, vladfrangu approved these changes

2020-10-20 11:01 UTC, tguichaoua requested changes

2020-10-20 11:01 UTC, tguichaoua commented on src/managers/RoleManager.js
>     * Obtains one or more roles from Discord, or the role cache if they're already available.
```suggestion
   * Obtains a role from Discord, or the role cache if they're already available.
```

2020-12-14 13:09 UTC, iCrawl approved these changes

2020-12-14 13:12 UTC, merged