feat: add missing error codes
discordjs/discord.js pull request #5008
Opened 2020-11-14 03:19 UTC by NotSugden

**Please describe the changes this PR makes and why it should be merged:**
this PR adds error codes that were missing from `APIErrors` in the constants

`CANNOT_DELETE_COMMUNITY_REQUIRED_CHANNEL` sounds a bit too long, so if someone has a better name for that lmk

([api errors listed here](https://discord.com/developers/docs/topics/opcodes-and-status-codes#json))

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-11-17 20:59 UTC, SpaceEEC requested changes
Otherwise LGTM

2020-11-17 20:59 UTC, SpaceEEC commented on src/util/Constants.js
> +  CHANNEL_HIT_RATELIMIT: 20028,
Is that name from somewhere else?
Otherwise I'd like to include `write` there. 😅 

```suggestion
  CHANNEL_HIT_WRITE_RATELIMIT: 20028,
```

2020-11-17 20:59 UTC, SpaceEEC commented on typings/index.d.ts
> +    CHANNEL_HIT_RATELIMIT: 20028;
See my comment above.

```suggestion
    CHANNEL_HIT_WRITE_RATELIMIT: 20028;
```

2020-11-17 21:50 UTC, NotSugden commented on src/util/Constants.js
> + * * CHANNEL_HIT_RATELIMIT
```suggestion
 * * CHANNEL_HIT_WRITE_RATELIMIT
```
lazy batch commit

2020-11-19 11:58 UTC, SpaceEEC approved these changes

2020-11-19 12:43 UTC, kyranet approved these changes

2020-11-20 15:18 UTC, iCrawl approved these changes

2020-11-20 15:18 UTC, merged