chore(Engine): bump Node.js to v14.0.0
discordjs/discord.js pull request #5067
Opened 2020-12-01 17:37 UTC by kyranet

**Please describe the changes this PR makes and why it should be merged:**

For v13.x, we are permitted to do breaking changes, and can clean up a lot of code (specially sanity checks) with the new ES2020 syntax, specially with `?.` and `??`.

Node.js v14.0.0 is the lowest version that supports both features.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-12-01 18:05 UTC, vladfrangu approved these changes

2020-12-01 18:06 UTC, advaith1 commented
While having access to the new syntax would be great, since there are so many glitch bots we might wanna consider that glitch [currently only supports up to 12](https://nodeversions.glitch.me)

2020-12-01 18:25 UTC, iCrawl commented
@advaith1 I certainly do not care about glitch support.

While orientating yourself around services that support our software, I am not too much inclined in completely working around them.

2020-12-01 18:32 UTC, kyranet commented
Furthermore I wouldn't expect v13 to be released for at least a month, by that time Glitch should have support for v14, which has been LTS for a month and a half.

discord.js v12 will remain working for a few more months (until Discord kills v6 WS and/or REST, which I don't see happening until Summer 2021) if you need a version working with Node.js v12.

2020-12-01 19:41 UTC, MattIPv4 reviewed
GitHub workflows should probably also be bumped to node 14 at the same time?

2020-12-02 01:27 UTC, Sidemen19 approved these changes

2020-12-02 11:41 UTC, MattIPv4 approved these changes

2020-12-02 13:59 UTC, SpaceEEC requested changes
You seem to have dropped a few significant spaces here.

2020-12-02 13:59 UTC, SpaceEEC commented on README.md
> +**Node.js 14.0.0 or newer is required.**
```suggestion
**Node.js 14.0.0 or newer is required.**  
```

2020-12-02 13:59 UTC, SpaceEEC commented on README.md
> +With voice support ([@discordjs/opus](https://www.npmjs.com/package/@discordjs/opus)): `npm install discord.js @discordjs/opus`
```suggestion
Without voice support: `npm install discord.js`  
With voice support ([@discordjs/opus](https://www.npmjs.com/package/@discordjs/opus)): `npm install discord.js @discordjs/opus`  
```

2020-12-02 13:59 UTC, SpaceEEC commented on README.md
> +[documentation](https://discord.js.org/#/docs).
```suggestion
[documentation](https://discord.js.org/#/docs).  
```

2020-12-02 13:59 UTC, SpaceEEC commented on docs/general/welcome.md
> +**Node.js 14.0.0 or newer is required.**
```suggestion
**Node.js 14.0.0 or newer is required.**  
```

2020-12-02 13:59 UTC, SpaceEEC commented on docs/general/welcome.md
> +With voice support ([@discordjs/opus](https://www.npmjs.com/package/@discordjs/opus)): `npm install discord.js @discordjs/opus`
```suggestion
Without voice support: `npm install discord.js`  
With voice support ([@discordjs/opus](https://www.npmjs.com/package/@discordjs/opus)): `npm install discord.js @discordjs/opus`  
```

2020-12-02 13:59 UTC, SpaceEEC commented on docs/general/welcome.md
> +[documentation](https://discord.js.org/#/docs).
```suggestion
[documentation](https://discord.js.org/#/docs).  
```

2020-12-02 18:29 UTC, Vaporox commented
Should this also be updated?
https://github.com/discordjs/discord.js/blob/master/docs/general/faq.md#L7

2020-12-02 18:29 UTC, advaith1 commented
this pr already updates that

2020-12-02 18:30 UTC, Vaporox commented
oops yeah, mb

2020-12-06 16:57 UTC, iCrawl approved these changes

2020-12-06 16:58 UTC, merged