feat(GuildMember): make GuildMember#setNickname first param nullable
discordjs/discord.js pull request #5070
Opened 2020-12-01 21:32 UTC by zaida04

Passing null into GuildMember#setNickname will reset the nickname. But neither the typings nor the jsdoc indicate that you can pass that in.

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-12-01 21:33 UTC, zaida04 commented
In response to #5068

2020-12-01 21:44 UTC, Vaporox commented on src/structures/GuildMember.js
> +   * @param {string|null} nick The nickname for the guild member, or `null` if you want to reset their nickname
```suggestion
   * @param {?string} nick The nickname for the guild member, or `null` if you want to reset their nickname
```

2020-12-05 15:18 UTC, mozartrafi commented
Lol

2020-12-08 19:01 UTC, iCrawl approved these changes

2020-12-08 19:14 UTC, kyranet approved these changes

2020-12-08 21:17 UTC, vladfrangu approved these changes

2020-12-10 13:50 UTC, SpaceEEC requested changes
This also need to be documented here:
https://github.com/discordjs/discord.js/blob/105238fc8936646775091f6e242ff8c8cb2bf7fa/src/structures/GuildMember.js#L277
And here:
https://github.com/discordjs/discord.js/blob/105238fc8936646775091f6e242ff8c8cb2bf7fa/typings/index.d.ts#L2651

2020-12-11 16:28 UTC, SpaceEEC approved these changes

2020-12-12 13:50 UTC, merged