refactor: RoleManager
discordjs/discord.js pull request #5131
Opened 2020-12-18 11:11 UTC by Extroonie

**Please describe the changes this PR makes and why it should be merged:**
This PR suggests some refactoring to keep consistency, and also uses the newest Node v14 syntax in relevant places.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2020-12-18 11:25 UTC, kyranet approved these changes

2020-12-18 12:13 UTC, vladfrangu approved these changes

2020-12-18 13:14 UTC, NotSugden requested changes

2020-12-18 13:14 UTC, NotSugden commented on src/managers/RoleManager.js
> +    return this.cache.find(role => role.tags && role.tags.botID === userID) ?? null;
```suggestion
    return this.cache.find(role => role.tags?.botID === userID) ?? null;
```

2020-12-18 13:14 UTC, NotSugden commented on src/managers/RoleManager.js
> +    return this.cache.find(role => role.tags && role.tags.premiumSubscriberRole) ?? null;
```suggestion
    return this.cache.find(role => role.tags?.premiumSubscriberRole) ?? null;
```

2020-12-26 09:57 UTC, iCrawl approved these changes

2020-12-26 09:57 UTC, merged