feat(Client): remove fetchAllMembers option & logic
discordjs/discord.js pull request #5257
Opened 2021-01-24 11:50 UTC by MattIPv4

**Please describe the changes this PR makes and why it should be merged:**

Removes the `fetchAllMembers` from the client options, per https://github.com/discordjs/discord.js/discussions/5246,https://github.com/discordjs/discord.js/issues/5123#issuecomment-766329225, etc.

Updates the `random.js` test to have a version of the old internal logic for `fetchAllMembers`, for folks that really need it.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-01-24 11:52 UTC, kyranet approved these changes

2021-01-24 12:49 UTC, vladfrangu requested changes
Nitpick and also consider fixing the annotations from actions

2021-01-24 12:49 UTC, vladfrangu commented on test/random.js
> +    .catch(err => console.log(`Failed to fetch all members: ${err}\n${err.stack}`)) : Promise.resolve());
Should go outside ready

2021-01-24 13:16 UTC, vladfrangu approved these changes
LGTM, make sure all uses of `checkShardsReady` don't call await. you can also remove the NEARLY status, unless it's used somewhere

2021-01-24 13:20 UTC, NotSugden requested changes

2021-01-24 13:20 UTC, NotSugden commented on src/client/websocket/WebSocketManager.js
> +  checkShardsReady() {
typings for this method need changing as it no longer returns a Promise

2021-01-24 13:36 UTC, MattIPv4 commented
https://github.com/discordjs/discord.js/blob/9ffcd83027f0fc06d69df21475865ad55138de01/src/client/websocket/WebSocketShard.js#L268 is the only remaining use of NEARLY.

2021-01-25 11:46 UTC, SpaceEEC approved these changes

2021-01-27 10:27 UTC, iCrawl approved these changes

2021-01-27 10:27 UTC, merged