Added check for if guild is unavailable on guild object
discordjs/discord.js pull request #5367
Opened 2021-03-02 12:57 UTC by Ortovoxx

**guildDelete event fires on startup due to an unavailable guild but not the guildUnavailable event**

There is a guild in my bot which is unavailable ( sitenote: I am pretty certain that this my bot user left this guild about a week or so ago ) and everytime the client starts up the `guildDelete` event fires and the `guildUnavailable` event does not fire.

I looked into it and it appears that the `GuildDeleteAction` event fires when this occurs but the data object that is sent to it just contains the guild id property: `{ id: '813428000925417513' }` with no `unavailable` property like [documented](https://discord.com/developers/docs/resources/guild#unavailable-guild-object)

However it appears that the guild does have the `available` property found on all guilds so I added an extra check for this property when deciding if to fire the `guildUnavailable` or `guildDelete` event.

I believe that this is an edge case on discords end as I mentioned earlier that I don't think that my bot is in this guild anymore. It has also been unavailable for about a week now.

Adding this change to my local library seemed to fix it. Let me know if I am missing anything here I hope my first PR has been useful!

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes

2021-03-03 14:01 UTC, almostSouji commented
Not sure yet if this should need to be handled in the library. Discord devs are aware of it happening but have so far not been able to figure out when it occurs. With how the said statement was phrased I'm not yet certain if this should be handled on the library level at all.

2021-03-03 20:04 UTC, Ortovoxx commented
Okay that makes sense. Hopefully it get fixed soon.

2021-03-10 11:59 UTC, Ortovoxx commented
Reopening because we need to handle in the library and ignore soft deleted guilds. See [this comment](https://github.com/discordjs/discord.js/issues/5350#issuecomment-793726018)

2021-03-23 16:07 UTC, DaliborTrampota commented
https://github.com/discordjs/discord.js/issues/5430 hello i have the same issue i  guess

2021-04-30 11:14 UTC, vladfrangu approved these changes
LGTM

2021-04-30 12:26 UTC, kyranet approved these changes

2021-05-23 10:12 UTC, vladfrangu requested changes
What space said

2021-06-25 10:16 UTC, iCrawl commented
This PR has been pretty stale with no feedback from the author, hence I am going to close this.

Please reopen with the suggested changes if this is still needed/wanted.

2021-06-25 10:16 UTC, closed without merging