Make MessageEmbed#normalizeField better
discordjs/discord.js pull request #5459
Opened 2021-04-01 02:24 UTC by anandre

**Please describe the changes this PR makes and why it should be merged:**

`normalizeField` was made with a custom error to throw, this PR removes that so that a proper API error with path will be thrown instead.  This makes the error message more informative.

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2021-04-30 11:08 UTC, vladfrangu approved these changes

2021-04-30 12:28 UTC, kyranet approved these changes

2021-05-10 09:42 UTC, SpaceEEC commented
How is the location of where you are sending the message more informative than where you are adding the malformed field?

2021-05-10 09:44 UTC, kyranet commented
> How is the location of where you are sending the message more informative than where you are adding the malformed field?

We don't really check values in many other places, so why should we do so here?

2021-05-10 09:46 UTC, kyranet requested changes
You should remove those two constants, as their only references are removed with this PR:

https://github.com/anandre/discord.js/blob/b70c8bde81bb2b29fa8d08d76a830e68211e270b/src/errors/Messages.js#L40-L41

2021-05-10 14:11 UTC, anandre commented
Removed.

2021-05-10 14:28 UTC, kyranet commented
Just one last thing so ESLint passes... this line needs to be removed, now that it's unused:

![image](https://user-images.githubusercontent.com/24852502/117675316-bf7c0780-b1ac-11eb-8e2f-9e8a42bbbbe5.png)

2021-05-10 14:35 UTC, kyranet approved these changes

2021-05-11 20:24 UTC, merged