feat(SysChanFlags): new flag and rename in sync with client
discordjs/discord.js pull request #5506
Opened 2021-04-08 19:38 UTC by almostSouji

**Please describe the changes this PR makes and why it should be merged:**

As per https://github.com/discordjs/discord-api-types the flag names for system channel flags are inconsistent with the client, this PR aims to streamline this. Additionally, a new Flag for the new "Send helpful tips for server setup" guild setting has been introduced.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- Code changes have been tested against the Discord API, or there are no code changes
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2021-04-08 21:09 UTC, vladfrangu approved these changes

2021-04-08 21:12 UTC, SpaceEEC approved these changes

2021-04-09 08:50 UTC, kyranet approved these changes

2021-04-10 00:46 UTC, advaith1 requested changes
docs have to be updated too

2021-04-10 11:49 UTC, advaith1 approved these changes
might wanna add the client descriptions to docs but otherwise lgtm

2021-04-11 15:31 UTC, iCrawl approved these changes

2021-04-14 22:37 UTC, merged