feat(Webhook): sourceGuild, sourceChannel, improve owner
discordjs/discord.js pull request #5508
Opened 2021-04-08 22:41 UTC by almostSouji

**Please describe the changes this PR makes and why it should be merged:**

Webhooks can have a `source_guild` and a `source_channel` as per https://github.com/discord/discord-api-docs/pull/1837

- `owner `user data is fully available, meaning we can always construct a user here, and even cache it
- `source_guild` data is not fully available, by not caching but constructing a Guild instance we can leverage some guild methods (invites use the same approach to construct "partial" guilds - very empty guilds)
- `source_channel` for guilds the bot is not on, only consists of name and id, not enough to construct a channel from, meaning the data object default is required here

The type change `User | Object | null` to the more specific `User | null` should not be considered breaking, making this a minor release PR. 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-04-08 23:00 UTC, vaporox commented
The purpose of assigning `data.user` directly was for webhook clients that do not have a user manager available, with this change it would just always return `undefined`

2021-04-09 08:39 UTC, kyranet approved these changes

2021-04-09 10:26 UTC, vladfrangu requested changes

2021-04-09 10:26 UTC, vladfrangu commented on src/structures/Webhook.js
> +    this.sourceGuild = data.source_guild ? this.client.guilds?.add(data.source_guild, false) : null;
Should also default to `?? data.source_guild`

2021-04-09 17:31 UTC, vladfrangu approved these changes

2021-04-11 15:32 UTC, iCrawl approved these changes

2021-04-30 19:44 UTC, merged