refactor(Sharding): use options objects
discordjs/discord.js pull request #5510
Opened 2021-04-09 02:04 UTC by monbrey

This refactors the spawn/respawn methods on Sharding classes to use a single, optional object parameter with optional properties, rather than up to three separate optional parameters.

This should make it easier for developers to address the `SHARD_READY_TIMEOUT` issue to provide the `spawnTimeout` without needing to fill the other two optional params. It also renames the `spawnTimeout` parameter to `timeout` for simplicity and ease of use.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2021-04-09 10:25 UTC, vladfrangu requested changes

2021-04-09 10:25 UTC, vladfrangu commented on src/sharding/Shard.js
> +  async respawn({ delay = 500, timeout } = {}) {
```suggestion
  async respawn({ delay = 500, timeout = 30000 } = {}) {
```

2021-04-09 10:25 UTC, vladfrangu commented on src/sharding/ShardingManager.js
> +  async spawn({ amount = this.totalShards, delay = 5500, timeout } = {}) {
```suggestion
  async spawn({ amount = this.totalShards, delay = 5500, timeout = 30000 } = {}) {
```

2021-04-09 10:25 UTC, vladfrangu commented on src/sharding/ShardingManager.js
> +  async respawnAll({ shardDelay = 5000, respawnDelay = 500, timeout } = {}) {
```suggestion
  async respawnAll({ shardDelay = 5000, respawnDelay = 500, timeout = 30000 } = {}) {
```

2021-04-11 15:33 UTC, iCrawl approved these changes

2021-04-11 17:29 UTC, kyranet approved these changes

2021-04-11 17:56 UTC, vladfrangu approved these changes

2021-04-25 09:19 UTC, CyberFlameGO approved these changes

2021-04-26 12:45 UTC, catcosmicice approved these changes

2021-04-30 18:53 UTC, SpaceEEC approved these changes

2021-04-30 19:46 UTC, merged