refactor: add discord-api-types as a dependency
discordjs/discord.js pull request #5539
Opened 2021-04-17 19:43 UTC by vaporox

**Please describe the changes this PR makes and why it should be merged:**

This adds `discord-api-types` as a dev dependency. This way we don't need to keep interfaces of raw data in the declaration file and more imports can be added later if needed.

The imports were renamed from `API...` to `Raw...` to avoid conflicts with the local `APIMessage` class.

**Status and versioning classification:**

- There are no code changes
- I know how to update typings and have done so
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-04-18 07:06 UTC, OverseersMight approved these changes

2021-04-18 16:35 UTC, OverseersMight approved these changes

2021-04-19 10:26 UTC, kyranet approved these changes

2021-04-19 14:18 UTC, vladfrangu requested changes

2021-04-19 14:18 UTC, vladfrangu commented on typings/index.d.ts
> +  import { APIMessage as RawMessage, APIOverwrite as RawOverwrite } from 'discord-api-types';
Specify the version, identical to whatever rest version we support

2021-04-19 14:26 UTC, vladfrangu approved these changes

2021-04-19 14:26 UTC, vladfrangu commented on package.json
> +    "discord-api-types": "^0.17.0",
Might as well bump again before merging :P

2021-04-21 10:56 UTC, catcosmicice approved these changes

2021-04-23 00:17 UTC, iCrawl approved these changes

2021-04-23 00:18 UTC, merged