feat(ShardingManager): add options typings
discordjs/discord.js pull request #5583
Opened 2021-05-02 22:00 UTC by uhKevinMC

**Please describe the changes this PR makes and why it should be merged:**

This PR adds typings for the ShardingManager options parameter, along with adding documentation for the option.

*lets hope github doesn't rebase this again*

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-05-06 07:37 UTC, vladfrangu requested changes

2021-05-06 07:37 UTC, vladfrangu commented on src/sharding/ShardingManager.js
> +   * @property {string} [token] Token to use for automatical shard count and passing to shards
```suggestion
   * @property {string} [token] Token to use for automatic shard count and passing to shards
```

2021-05-10 09:05 UTC, SpaceEEC requested changes

2021-05-10 09:05 UTC, SpaceEEC commented on src/sharding/ShardingManager.js
> +
```suggestion
```

2021-05-10 09:38 UTC, kyranet approved these changes

2021-05-10 10:53 UTC, SpaceEEC approved these changes

2021-05-10 21:53 UTC, iCrawl approved these changes

2021-05-10 21:54 UTC, merged