Added Certified Moderator badge flag.
discordjs/discord.js pull request #5642
Opened 2021-05-18 10:03 UTC by vanishedvan

**Please describe the changes this PR makes and why it should be merged:**
This pull request adds the CERTIFIED_MODERATOR badge flag to the UserFlags class.

PR in discord-api-docs: https://github.com/discord/discord-api-docs/pull/2946

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- This PR changes the library's interface (methods or parameters added)

2021-05-18 10:27 UTC, iCrawl commented
We might as well wait until they rename it `EARLY_CERTIFIED_MODERATOR` because people try to abuse it again 😄

2021-05-18 15:09 UTC, advaith1 commented
add to typings

https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L3609-L3621

2021-05-18 15:14 UTC, vanishedvan commented
> add to typings
> 
> https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L3609-L3621

Done.

2021-05-19 07:00 UTC, iShibi requested changes
This time they [changed](https://github.com/discord/discord-api-docs/pull/2946#discussion_r634771408) the name too quickly 🏃‍♀️ 💨

2021-05-19 07:00 UTC, iShibi commented on src/util/UserFlags.js
> + * * `CERTIFIED_MODERATOR`
```suggestion
 * * `DISCORD_CERTIFIED_MODERATOR`
```

2021-05-19 07:00 UTC, iShibi commented on src/util/UserFlags.js
> +  CERTIFIED_MODERATOR: 1 << 18,
```suggestion
  DISCORD_CERTIFIED_MODERATOR: 1 << 18,
```

2021-05-19 07:00 UTC, iShibi commented on typings/index.d.ts
> +    | 'CERTIFIED_MODERATOR';
```suggestion
    | 'DISCORD_CERTIFIED_MODERATOR';
```

2021-05-19 15:53 UTC, Lulalaby commented
> 
> 
> We might as well wait until they rename it `EARLY_CERTIFIED_MODERATOR` because people try to abuse it again 😄

As I know, not every DMD member gets it, you have to earn it and it'll be manually assigned by discord staff.

2021-05-19 16:11 UTC, iCrawl commented
![image](https://user-images.githubusercontent.com/20760160/118847093-ad494a00-b8cd-11eb-9a55-49548c9b2e2e.png)

2021-05-29 11:28 UTC, iCrawl approved these changes

2021-05-29 12:58 UTC, vladfrangu approved these changes

2021-05-29 13:00 UTC, SpaceEEC approved these changes

2021-05-29 14:29 UTC, merged