cleanup(Client): guard emitting GMU and PU on user updates
discordjs/discord.js pull request #5655
Opened 2021-05-20 08:17 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

Attempt 2!

This is the continuation of #5161 in hopefully a much more accepted fashion.

GMU and PU are currently emitted regardless of the content of the update. Discord also send these events when the underlying user is updated. Since the library abstracts this away into `userUpdate` many PU and GMU events would contain the same exact data in both the old and new objects of their respective events. This simply guards against emitting the event when the objects are identical.

To note: GMU and PU are emitted by discord once for **every** guild the bot shares with a user normally, with this change, you will only get **1** `userUpdate` event, not 1 per guild.

I have not made any docs changes other than documenting `GuildMember#equals()` because the current docs still feel accurate. Feel free to suggest changes if you disagree!

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2021-05-20 17:51 UTC, kyranet requested changes

2021-05-20 17:51 UTC, kyranet commented on src/client/actions/GuildMemberUpdate.js
> +        if (!member.equals(old) && shard.status === Status.READY) client.emit(Events.GUILD_MEMBER_UPDATE, old, member);
Swap the order of the checks, the last one is a lot faster and can discard a much larger chain of operations.

2021-05-20 17:51 UTC, kyranet commented on src/client/actions/PresenceUpdate.js
> +    if (member && !member.presence.equals(oldPresence) && this.client.listenerCount(Events.PRESENCE_UPDATE)) {
Same here, place the equals check after the `listenerCount` one.

2021-05-20 17:51 UTC, kyranet commented on src/structures/GuildMember.js
> +   * comparison it is advisiable to just compare `member.id === member2.id` as it is significantly faster
```suggestion
   * comparison it is advisable to just compare `member.id === member2.id` as it is significantly faster
```

2021-05-20 17:51 UTC, kyranet commented on src/structures/GuildMember.js
> +   * @param {GuildMember} member the member to compare with
```suggestion
   * @param {GuildMember} member The member to compare with
```

2021-05-20 17:51 UTC, kyranet commented on src/structures/GuildMember.js
> +      member instanceof this.constructor &&
The truthy check is useless as the `instanceof` will always return `false` for nullish values.
```suggestion
      member instanceof this.constructor &&
```

2021-05-27 12:05 UTC, vladfrangu approved these changes

2021-05-27 14:27 UTC, kyranet approved these changes

2021-05-28 10:05 UTC, iCrawl approved these changes

2021-05-29 13:37 UTC, SpaceEEC approved these changes

2021-05-29 14:28 UTC, merged