fix(GuildMemberManager): allow moving members to any non-text channel
discordjs/discord.js pull request #5681
Opened 2021-05-27 00:47 UTC by AndyClausen

**Please describe the changes this PR makes and why it should be merged:**

This will allow moving members to channels with type `stage`. Closes #5673 🙂 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-05-27 01:23 UTC, tipakA commented
Technically, this way category channels are going to be an issue, since they return `false` from `isText()`
~~Is this a call for `isVoice()`?~~ 👀

2021-05-27 01:51 UTC, AndyClausen commented
> Technically, this way category channels are going to be an issue, since they return `false` from `isText()`
> ~Is this a call for `isVoice()`?~ 👀

Touché. I could change this to just add `stage` to the list of checks, but if an `isVoice` method is going to be added, I'd much rather wait for that 😅

2021-05-27 03:01 UTC, PraveshKunwar commented
> Technically, this way category channels are going to be an issue, since they return `false` from `isText()`
> ~Is this a call for `isVoice()`?~ 👀

would an isVoice method be needed?

2021-05-27 04:21 UTC, ThaTiemsz commented
> > Technically, this way category channels are going to be an issue, since they return `false` from `isText()`
> > ~Is this a call for `isVoice()`?~ 👀
> 
> Touché. I could change this to just add `stage` to the list of checks, but if an `isVoice` method is going to be added, I'd much rather wait for that 😅

Store channels will also be an issue.

2021-05-27 04:34 UTC, tipakA commented
Well, yes, i wasn't really trying to provide an extensive list of every single channel type this check will not work with, but simply give an example of why `isText()` isn't exactly the way here.

And my mention of `isVoice()` was made to avoid this issue in future in case discord would make new voice channel type. I'm definitely not saying whether it should be added or not, since it's a overall niche use case.

2021-05-27 04:39 UTC, ckohen commented
Since all applicable voice channels (dm channels technically have voice, but they don't count and not for bots anyways) extend `BaseGuildVoiceChannel`, and any future channel you could move people in a guild should probably follow suit, you can use `instance of BaseGuildVoiceChannel` I think.

2021-05-27 04:42 UTC, AndyClausen commented
I'll try that out tomorrow.

Now that I have you all here, should I rather make a new commit or amend the existing when it's such small changes? I've heard many different opinions from other repos.

2021-05-29 04:46 UTC, AndyClausen commented
Tested with `instanceof`, seems to work. Rebased and amended my commit.

2021-05-29 13:09 UTC, vladfrangu approved these changes

2021-05-29 16:49 UTC, kyranet requested changes

2021-05-29 16:49 UTC, kyranet commented on src/managers/GuildMemberManager.js
> +      if (!_data.channel || !(_data.channel instanceof BaseGuildVoiceChannel)) {
`null instanceof Class` returns `false`, so the falsy check is unneeded.

```suggestion
      if (!(_data.channel instanceof BaseGuildVoiceChannel)) {
```

2021-05-29 17:41 UTC, kyranet approved these changes

2021-05-30 10:02 UTC, vladfrangu approved these changes

2021-06-02 08:18 UTC, SpaceEEC approved these changes

2021-06-02 09:56 UTC, iCrawl approved these changes

2021-06-02 09:57 UTC, merged