Update Presence.js
discordjs/discord.js pull request #5846
Opened 2021-06-13 15:03 UTC by JMTK

**Please describe the changes this PR makes and why it should be merged:**
Add support for firing presence update events when the only thing that changes is an activity's state or details.

Fixes https://github.com/discordjs/discord.js/issues/5845

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-06-15 12:55 UTC, vladfrangu requested changes
Can you fix lint? Otherwise, if details isn't an object (in which case you'll need to check its keys), LGTM

2021-06-15 15:51 UTC, JMTK commented
Sorry about that! There was an extra space that the lint was complaining about that I had missed. Should be good now!

2021-06-18 13:41 UTC, iCrawl approved these changes

2021-06-18 14:45 UTC, kyranet approved these changes

2021-06-19 16:25 UTC, SpaceEEC approved these changes

2021-06-19 16:27 UTC, merged