Resolving subcommand and subcommand group for CommandInteractions
discordjs/discord.js pull request #5880
Opened 2021-06-19 11:08 UTC by jaydamani

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-06-19 11:51 UTC, monbrey commented
I don't see how this is necessary - there are no issues with sub command or sub command group options.

Why do you believe this change is needed?

2021-06-19 12:40 UTC, jaydamani commented
With this, lib would do the parsing and figure out the subcommand / subcommand group while options is just a map of arguments provided by the user. Not necessary but could be kinda handy.

2021-06-19 13:21 UTC, monbrey commented
It's not "parsing" anything though. Looks to me like you just hoist the options up a level, but then don't do any of the existing handling on them.

Just seems worse to me.

2021-07-02 05:51 UTC, monbrey commented
@jaydamani Hey, apologies, I think I completely misread the diff on this change. I've just tested your proposed changes and I think this could be beneficial. Do you want to reopen this for reviews?

2021-07-10 14:01 UTC, jaydamani commented
No problem, sorry for the delay ~~I should check my mail more often~~, kinda my bad as well, since I couldn't explain it properly

2021-07-14 00:38 UTC, NotSugden requested changes

2021-07-14 00:38 UTC, NotSugden commented on src/structures/CommandInteraction.js
> +      this.group = options[0].name;
isn"t there an enum for this?

2021-07-14 00:38 UTC, NotSugden commented on src/structures/CommandInteraction.js
> +       * @type {string}
...? description?

2021-07-14 00:38 UTC, NotSugden commented on src/structures/CommandInteraction.js
> +       * @type {string}
^

2021-07-15 10:03 UTC, iCrawl commented
This will be handled in #6107

2021-07-15 10:03 UTC, closed without merging