fix(Message): flags not being parsed on some edits
discordjs/discord.js pull request #5886
Opened 2021-06-20 07:47 UTC by monbrey

One of those rabbit hole bugs that made me change a few things.

To start with, `Message#suppressEmbeds` was broken. This is because:

1. Internally that method calls `Message#edit({ flags: 4 })`.
2. That method then calls `MessageManager#edit(this.id, options)`
3. `MessageManager#edit` constructs an `APIMessage` with `this` as the target.
4. `APIMessage#resolveData` only resolves `flags` if the `APIMessage#target` is a `Message` or `Interaction`.
https://github.com/discordjs/discord.js/blob/master/src/structures/APIMessage.js#L159-L164

So, I decided that:

1. `Message#edit` should pass `this` rather than `this.id`.
2. `MessageManager#edit` should pass the whole message to `APIMessage#target` if provided with one.
3. `APIMessage` should support `MessageManager` as a target also.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-06-20 14:48 UTC, iCrawl commented on src/managers/MessageManager.js
> -    message = this.resolveID(message);
No more mutation, hooray 🧹

2021-06-20 14:49 UTC, iCrawl approved these changes

2021-06-20 15:00 UTC, vladfrangu requested changes

2021-06-20 15:00 UTC, vladfrangu commented on src/managers/MessageManager.js
> +    if (this.cache.has(messageID)) {
Nit: instead of has/get, do one get and check that in the `if` check

2021-06-20 15:51 UTC, SpaceEEC approved these changes

2021-06-23 09:43 UTC, vladfrangu approved these changes

2021-06-23 10:26 UTC, kyranet approved these changes

2021-06-23 23:02 UTC, merged