refactor: rename `Constants.OPCode` to `Opcode`, moved objects to enums
discordjs/discord.js pull request #6065
Opened 2021-07-06 10:40 UTC by kyranet

**Please describe the changes this PR makes and why it should be merged:**

Renamed `Constants.OPCode` for consistency with recent changes, also moved enum-like objects to the enums file and added tests to ensure they don't receive properties that shouldn't exist.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2021-07-06 11:09 UTC, SpaceEEC requested changes

2021-07-06 11:09 UTC, SpaceEEC commented on typings/enums.d.ts
> +export enum ConstantsColors {
This is not an enum, but TS allows compiling something like `Colors[Colors.RED]`, yielding a `string`, however in runtime it's actually `undefined`.
We could make it an enum however, `createEnum` could be modified to accept objects too.

2021-07-06 11:09 UTC, SpaceEEC commented on typings/enums.d.ts
> +export enum ConstantsStatus {
This one too.

2021-07-06 11:09 UTC, SpaceEEC commented on typings/enums.d.ts
> +export enum ConstantsOpcodes {
This one too.

2021-07-06 11:09 UTC, SpaceEEC commented on typings/enums.d.ts
> +export enum ConstantsClientApplicationAssetTypes {
This one too.

2021-07-06 17:30 UTC, iCrawl approved these changes

2021-07-06 18:02 UTC, vladfrangu approved these changes

2021-07-07 09:20 UTC, SpaceEEC approved these changes

2021-07-07 12:40 UTC, merged