types(ApplicationCommand): fix option name
discordjs/discord.js pull request #6067
Opened 2021-07-06 18:29 UTC by DTrombett

**Please describe the changes this PR makes and why it should be merged:**
This PR just fixes an error in Typings where the option `permissionId` was types as `permissionsId`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-07-06 18:33 UTC, vladfrangu approved these changes

2021-07-06 18:34 UTC, Sasuke-7 commented
I'm fixing this, I don't recommend trying to send quick requests without at least checking the rest of the code

2021-07-06 20:19 UTC, kyranet approved these changes

2021-07-07 09:24 UTC, SpaceEEC requested changes
Could you also fix the name here?
https://github.com/discordjs/discord.js/blob/755c180659c125532fe6f8e33e6c3b56e275311b/src/managers/ApplicationCommandPermissionsManager.js#L350
~~nameof when~~

2021-07-07 09:39 UTC, DTrombett commented
> Could you also fix the name here?
> https://github.com/discordjs/discord.js/blob/755c180659c125532fe6f8e33e6c3b56e275311b/src/managers/ApplicationCommandPermissionsManager.js#L350
> 
> 
> ~nameof when~

Sure

2021-07-07 09:52 UTC, SpaceEEC approved these changes

2021-07-07 12:41 UTC, iCrawl approved these changes

2021-07-07 12:41 UTC, merged