fix(User): fetch force parameter
discordjs/discord.js pull request #6116
Opened 2021-07-15 10:20 UTC by advaith1

**Please describe the changes this PR makes and why it should be merged:**

Currently, User#fetch ignores the `force` parameter, always treating it as false. This PR fixes it.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-07-15 10:23 UTC, iCrawl approved these changes

2021-07-15 10:24 UTC, vladfrangu approved these changes

2021-07-15 10:27 UTC, DTrombett commented
While you're at it, could you fix the same problem with the other structures, like `Channel#fetch ()`?

2021-07-15 11:38 UTC, almeidx requested changes

2021-07-15 11:38 UTC, almeidx commented on src/structures/Channel.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 11:38 UTC, almeidx commented on src/structures/DMChannel.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 11:38 UTC, almeidx commented on src/structures/GuildBan.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 11:38 UTC, almeidx commented on src/structures/GuildMember.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 11:38 UTC, almeidx commented on src/structures/Message.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 11:38 UTC, almeidx commented on src/structures/User.js
>     * @param {boolean} [force=false] Whether to skip the cache check and request the API
```suggestion
   * @param {boolean} [force=true] Whether to skip the cache check and request the API
```

2021-07-15 12:36 UTC, DTrombett approved these changes

2021-07-16 09:14 UTC, kyranet approved these changes

2021-07-16 22:30 UTC, shinotheshino approved these changes

2021-07-17 11:14 UTC, SpaceEEC approved these changes

2021-07-17 11:25 UTC, merged