feat(GuildPreview): add createdAt & createdTimestamp
discordjs/discord.js pull request #6130
Opened 2021-07-17 10:40 UTC by GoldenAngel2

**Please describe the changes this PR makes and why it should be merged:**
GuildPreview is missing the `createdAt` & `createdTimestamp` fields since it doesn't extend the BaseGuild class, so this PR adds it.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-07-17 11:12 UTC, SpaceEEC requested changes
Otherwise LGTM

2021-07-17 11:12 UTC, SpaceEEC commented on src/structures/GuildPreview.js
> +
🧹 
```suggestion

```

2021-07-17 11:19 UTC, vladfrangu approved these changes

2021-07-17 13:47 UTC, kyranet approved these changes

2021-07-18 06:28 UTC, SpaceEEC approved these changes

2021-07-18 18:18 UTC, merged