fix(Typings): type attachments with never
discordjs/discord.js pull request #6162
Opened 2021-07-21 10:16 UTC by Milo123459

**Please describe the changes this PR makes and why it should be merged:**

Currently, if you want to remove attachments from a message you have to use `message.removeAttachments()`, and if you need to edit the content as well that is 2 API calls. Assigning `attachments: []` does work, but sparks errors in TypeScript that require `// @ts-ignore` - which is generally considered a bad practice. This PR fixes the typings allowing you to assign `attachments: []` without having to use ts-ignore.

**Status and versioning classification:**

I know how to update typings and have done so, or typings don't need updating

2021-07-21 10:18 UTC, DTrombett commented
```ts
const attachments: MessageAttachment[] = [];
msg.edit({ attachments, content: 'abc' });
```
This works without using TS ignore...

2021-07-21 10:20 UTC, Milo123459 commented
If that works then logically speaking I would expect `attachments: [] as MessageAttachment[]` to work but I still get the same error if I just gave it a blank array

2021-07-21 10:22 UTC, DTrombett commented on typings/index.d.ts
> +  attachments?: Array<MessageAttachment | never>;
```suggestion
  attachments?: (MessageAttachment | never)[];
```
Djs doesn't use the `Array<Type>` form.

2021-07-21 10:27 UTC, Milo123459 commented
Also, this error also pops up when using `<MessageComponentInteraction>.update({attachments: []})` - I can't seem to find an interface that corrosponds to the `attachments` field. It's all just chains of Omit's

2021-07-21 12:00 UTC, rmunro-uts commented
I can't replicate any error with this.
`message.edit({ attachments: [] });` isn't throwing any TypeScript errors for me.

2021-07-21 12:01 UTC, monbrey commented
I can't replicate any issue with `message.edit({ attachments: [] })`, TypeScript isnt complaining.

2021-07-21 12:03 UTC, Milo123459 commented
Odd. I also get this error when trying to update a MesaageComponentInteraction with no attachments.

2021-07-21 12:27 UTC, monbrey commented
`attachments` is not a valid property for `InteractionUpdateOptions`. We briefly discussed this in dev chats but never applied a fix. Ignoring the `Omit` typings, it's basically a chain.
 
`InteractionUpdateOptions > InteractionReplyOptions > WebhookMessageOptions > MessageOptions`

This isn't quite what it should be; `InteractionUpdateOptions` should probably be something more like:
```ts
export interface InteractionUpdateOptions extends Omit<WebhookEditMessageOptions, 'username' | 'avatarURL'> {
  fetchReply?: boolean;
}```
and WebhookEditMessageOptions probably needs to support editing attachments, so:
```ts
export interface WebhookEditMessageOptions extends Pick<
  WebhookMessageOptions,
  'content' | 'embeds' | 'files' | 'allowedMentions' | 'components'
> {
  attachments: MessageAttachment[];
}```

2021-07-21 12:32 UTC, Milo123459 commented
Picking from MessageOptions makes more sense. I'll try to implement a fix.

2021-07-21 12:34 UTC, Milo123459 commented
```
export interface WebhookEditMessageOptions extends Pick<
  WebhookMessageOptions,
  'content' | 'embeds' | 'files' | 'allowedMentions' | 'components'
> {
  attachments: MessageAttachment[];
}
```
From what you said, this implies that when you are assigning `attachments` it'll cause the same error this is PR trying to fix. I'll go with `attachments: (MessageAttachment | never)[]` as that's what this PR is fixing.

2021-07-21 12:37 UTC, monbrey commented
You're referring to an error I was unable to replicate on `message.edit`. I don't believe typing it as `never` is the correct fix for the issue you described, which does exist on `interaction.update` as no typings for `attachments` exist as all.

2021-07-21 12:39 UTC, Milo123459 commented
So all this has to do is type `attachments` for `InteractionUpdateOptions`?

2021-07-21 12:40 UTC, monbrey commented
> 
> 
> So all this has to do is type `attachments` for `InteractionUpdateOptions`?

I think so, yes. But as its a long chain of Omits as you pointed out, finding the right place/editing that chain is the tricky part.

Otherwise if you are running into the issue on `message.edit({ attachments: [] })`, where those typings do already exist, please provide a reproducible code sample because I wasn't able to get any errors.

2021-07-21 12:41 UTC, Milo123459 commented
Yea, I think it was something to do with Yarn's PnP and my workspace typescript version, that one seems to of been fixed, this PR should now focus on fixing `InteractionUpdateOptions`

2021-07-21 12:43 UTC, monbrey requested changes

2021-07-21 12:43 UTC, monbrey commented on typings/index.d.ts
> +export type InteractionUpdateOptions = MessageEditOptions;
This is now missing `fetchReply`

2021-07-21 12:44 UTC, Milo123459 commented on typings/index.d.ts
> +export type InteractionUpdateOptions = MessageEditOptions;
Oops

2021-07-21 13:00 UTC, Milo123459 commented
Anything else need to be changed?

2021-07-23 16:36 UTC, SpaceEEC approved these changes

2021-07-23 16:50 UTC, vladfrangu approved these changes

2021-07-23 19:18 UTC, iCrawl approved these changes

2021-07-23 19:18 UTC, merged