feat(MessageEmbed): add setFields method
discordjs/discord.js pull request #6186
Opened 2021-07-26 22:54 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**
This PR adds a setFields method to MessageEmbed that works similarly to addFields but it overwrites the current fields in the MessageEmbed.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-07-29 16:53 UTC, ImRodry commented
Changed it to use spliceFields internally so that the object isn't reassigned.

2021-07-30 01:27 UTC, PuneetGopinath commented
> Changed it to use spliceFields internally so that the object isn't reassigned.

Then update the title

2021-07-30 21:49 UTC, vladfrangu approved these changes

2021-07-31 12:06 UTC, iCrawl approved these changes

2021-07-31 12:06 UTC, SpaceEEC requested changes

2021-07-31 12:06 UTC, SpaceEEC commented on src/structures/MessageEmbed.js
> +    this.spliceFields(0, this.fields.length, this.constructor.normalizeFields(fields));
`MessageEmbed#spliceFields` is already normalizing the fields:
```suggestion
    this.spliceFields(0, this.fields.length, fields);
```

2021-07-31 12:09 UTC, SpaceEEC approved these changes

2021-07-31 12:14 UTC, kyranet approved these changes

2021-07-31 12:15 UTC, merged