fix: remove truthy check before isNaN check
discordjs/discord.js pull request #6358
Opened 2021-08-09 03:52 UTC by zaida04

[If an invalid string is passed into resolveColor, it never actually throws a `COLOR_CONVERT` error and will return NaN](https://user-images.githubusercontent.com/19440022/128658616-6420ae74-1021-4405-b2d0-3f8b5ca2c9ee.png). Why is this? Well because of this line:
https://github.com/discordjs/discord.js/blob/cd393fd4214e111f1cf6de779cfcc07315e80fbd/src/util/Util.js#L473

Because [NaN isn't a truthy value](https://cdn.discordapp.com/attachments/768856355255484469/874136189278519346/node_IBCxEagdZz.png), we don't get past that first condition to be able to check whether the color is NaN. This PR fixes that.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

2021-08-09 07:13 UTC, kyranet requested changes

2021-08-09 07:13 UTC, kyranet commented on src/util/Util.js
> +    else if (isNaN(color)) throw new TypeError('COLOR_CONVERT');
Just so `color` isn't casted to a number (even when it's a string):
```suggestion
    else if (Number.isNaN(color)) throw new TypeError('COLOR_CONVERT');
```

2021-08-10 10:00 UTC, kyranet approved these changes

2021-08-10 14:19 UTC, iCrawl approved these changes

2021-08-10 20:14 UTC, merged