fix(BaseClient): produce an error for non object options
discordjs/discord.js pull request #6453
Opened 2021-08-16 05:45 UTC by J-Human

**Please describe the changes this PR makes and why it should be merged:**

This throws an error to the user if the `options` provided is not an object. It prevents more confusing and misleading errors given by the process. For example, one may have something like this:
```ts
new WebhookClient('id', 'token');
```
Which is, in fact, an outdated way of creating Webhooks. I wouldn't say we *shouldn't* place it because it's the user's fault, though. Since the options parameter is a string, it cannot append the default arguments, hence producing a misleading error:
`cannot append property shardCount on string "..."`
I've seen lots of users in the server that have errors like the above. 

Furthermore, this prevents using the wrong data in other parts of client-related things. Some users don't have a proper IDE, hence they won't receive any feedback from the typings either, this does it for the interpreter.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-08-16 06:45 UTC, Keke27210 commented
Documentation is pretty clear on how to build each class, if people don't want to be bothered to check it, it's their problem.
discord.js is a beginner-friendly library (in spite of itself? e.g. the stricter Snowflake type) but its source code should not be containing extra-(useless)-code.

JavaScript being weakly typed is one of its forces, but also one of its drawbacks (which is why TypeScript was born), but imo it's not up to the library to check for those inputs. If people want to code "safely", they can switch to TypeScript, get a good linter, or even better (but maybe a little bit too much) read documentation.

All of this to say I'm not really a big fan of that, as it would probably start up a trend of implementing type checks everywhere in the source code that'd end up taking a little bit of performance at runtime.

2021-08-18 08:40 UTC, NotSugden commented on src/client/BaseClient.js
> +    if (typeof options === 'object') {
i think it would be cleaner to
```js
if (typeof options !== 'object' || options === null) {
  throw [...];
}

this.options = [...];
```

2021-08-18 10:25 UTC, kyranet approved these changes

2021-08-18 10:27 UTC, kyranet requested changes
Just noticed something, the `'INVALID_TYPE'` error is used exclusively with `TypeError` across the library.

2021-08-18 10:27 UTC, kyranet commented on src/client/BaseClient.js
> +      throw new Error('INVALID_TYPE', 'options', 'object', true);
```suggestion
      throw new TypeError('INVALID_TYPE', 'options', 'object', true);
```

2021-08-18 10:27 UTC, kyranet commented on src/client/BaseClient.js
> +const { Error } = require('../errors');
```suggestion
const { TypeError } = require('../errors');
```

2021-08-18 10:38 UTC, vladfrangu approved these changes
LGTM, although we should decide if we validate all inputs, just some, or none.. personally a fan of runtime validation (you can see that in builders)

2021-08-18 14:26 UTC, kyranet approved these changes

2021-08-23 14:22 UTC, SpaceEEC approved these changes

2021-10-02 11:58 UTC, iCrawl commented
This needs a rebase.

2021-10-02 23:53 UTC, J-Human commented
Done

2022-01-08 10:25 UTC, iCrawl approved these changes

2022-01-09 10:49 UTC, merged