feat: set methods for MessageActionRow and MessageSelectMenu
discordjs/discord.js pull request #6490
Opened 2021-08-21 13:35 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**
Following the [PR](https://github.com/discordjs/discord.js/pull/6186) that added the setFields method for MessageEmbeds, this PR adds two new methods: setOptions for MessageSelectMenu and setComponents for MessageActionRow.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-08-21 19:34 UTC, vladfrangu approved these changes
Sure

2021-08-23 12:37 UTC, SpaceEEC approved these changes

2021-08-23 12:38 UTC, SpaceEEC requested changes
This is actually missing the validation the `add___` methods have 😅

2021-08-23 12:43 UTC, ImRodry commented
> This is actually missing the validation the `add___` methods have 😅

No it’s not because the splice methods do that. That was something I included in the embed PR and was asked to change

2021-08-23 13:52 UTC, SpaceEEC approved these changes
Whoops the second then.
I must have mistaken that for a plain splice. 😓

2021-08-23 13:58 UTC, ImRodry commented
All good!

2021-08-23 17:06 UTC, kyranet approved these changes

2021-08-24 20:19 UTC, iCrawl approved these changes

2021-08-24 20:20 UTC, merged