chore(VSCode): add extension recommendations
discordjs/discord.js pull request #6666
Opened 2021-09-19 16:17 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**
This PR adds 2 extension recommendations to the .vscode folder. These are Prettier and ESLint, the formatter and linter used by discord.js. This is so that new users who install these extensions are able to notice errors before pushing and to fix them more easily in case they don't get automatically fixed by the pre-commit hook.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2021-10-31 11:14 UTC, ImRodry commented
Rebased and added back the .vscode folder to the gitignore since it can be annoying to have these files committed

2022-01-07 23:33 UTC, iCrawl requested changes

2022-01-07 23:33 UTC, iCrawl commented on .gitignore
> +!.vscode/extensions.json
Either remove this, or also add the settings.json as an exception here.

2022-01-07 23:33 UTC, iCrawl commented on .vscode/extensions.json
> +  "recommendations": ["esbenp.prettier-vscode", "dbaeumer.vscode-eslint"]
This should use tabs.

Also add:
- `tamasfe.even-better-toml`
- `github.vscode-pull-request-github`
- `codezombiech.gitignore`
- `eamodio.gitlens`
- `christian-kohler.npm-intellisense`
- `christian-kohler.path-intellisense`

2022-01-07 23:51 UTC, iCrawl approved these changes

2022-01-07 23:51 UTC, merged