fix(CachedManager): return updated data when cache is false
discordjs/discord.js pull request #6685
Opened 2021-09-24 15:17 UTC by iShibi

**Please describe the changes this PR makes and why it should be merged:**

fixes: #6667

Under the circumstances where a structure is present in the cache, `<Manager>_add()` returns stale data if `cache` is set to false instead of returning the updated data without caching it.

**Status and versioning classification:**

2021-09-24 15:22 UTC, SpaceEEC requested changes
`_patch` does not necessarily return the updated structure, you need to explicitly return the appropriate instance. 😅

2021-09-24 18:54 UTC, KokoNeot commented
Thanks for the fix!

2021-09-24 19:34 UTC, vladfrangu approved these changes

2021-09-26 19:38 UTC, iCrawl approved these changes

2021-09-27 10:37 UTC, SpaceEEC approved these changes

2021-09-27 11:49 UTC, merged