fix(Constants): allow undefined size
discordjs/discord.js pull request #6686
Opened 2021-09-24 18:04 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**
Fixes a bug accidentally introduced by #6637 where an error would be thrown when passing an undefined size (this is what happens when you only test the behavior you're looking for and not other scenarios 😅)

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-09-24 19:34 UTC, GoldenAngel2 approved these changes
👍

2021-09-24 19:35 UTC, vladfrangu requested changes

2021-09-24 19:35 UTC, vladfrangu commented on src/util/Constants.js
> +  if (size && typeof size !== 'number') throw new TypeError('INVALID_TYPE', 'size', 'number');
```suggestion
  if (typeof size !== 'undefined' && typeof size !== 'number') throw new TypeError('INVALID_TYPE', 'size', 'number');
```

2021-09-24 19:37 UTC, ImRodry commented on src/util/Constants.js
> +  if (size && typeof size !== 'number') throw new TypeError('INVALID_TYPE', 'size', 'number');
Does this work too? Looks cleaner imo
```suggestion
  if (!['undefined', 'number'].includes(typeof size)) throw new TypeError('INVALID_TYPE', 'size', 'number');
```

2021-09-24 19:39 UTC, vladfrangu commented on src/util/Constants.js
> +  if (size && typeof size !== 'number') throw new TypeError('INVALID_TYPE', 'size', 'number');
Sure, that works too

2021-09-24 19:42 UTC, vladfrangu approved these changes

2021-09-24 20:03 UTC, SpaceEEC approved these changes

2021-09-26 19:37 UTC, iCrawl approved these changes

2021-09-26 19:38 UTC, merged