feat: add animated banner guild feature
discordjs/discord.js pull request #6812
Opened 2021-10-11 02:52 UTC by iShibi

**Please describe the changes this PR makes and why it should be merged:**

- discord/discord-api-docs#3948

**Status and versioning classification:**

2022-01-10 23:08 UTC, Jiralite requested changes

2022-01-10 23:08 UTC, Jiralite commented on packages/discord.js/src/structures/Guild.js
> +
This should instead be modified in the `AnonymousGuild` class instead:

https://github.com/discordjs/discord.js/blob/ed0cfd91edc3a2b23a34a8ecd9db38baa12b52fa/packages/discord.js/src/structures/AnonymousGuild.js#L69-L76

Both an `InviteGuild` and a `Guild` can receive the animated hash.

2022-04-05 21:19 UTC, Jiralite commented
Upstream got merged. Are you able to continue, @iShibi?

2022-04-06 04:51 UTC, iShibi commented
> Upstream got merged. Are you able to continue, @iShibi?

it's been a long gap, you can takeover if it's fine with you

2022-04-06 18:34 UTC, Jiralite commented
I've looked over what needs to be done to support animated guild banners in discord.js.

For some reason, the `AnonymousGuild`'s `bannerURL()` method already supports dynamic hashes:

https://github.com/discordjs/discord.js/blob/402514ff323ccf1f8c95d295f044cf0bb5547c2e/packages/discord.js/src/structures/AnonymousGuild.js#L78-L85

https://github.com/discordjs/discord.js/blob/402514ff323ccf1f8c95d295f044cf0bb5547c2e/packages/discord.js/typings/index.d.ts#L268

All that's left is to bump discord-api-types to 0.31.0 so the typings are updated for the new guild feature. However, this is already being done in #7634, so it looks like no pull request is needed for this and support will naturally come!

2022-04-09 11:14 UTC, closed without merging

2022-04-09 11:14 UTC, SpaceEEC commented
See comment above ^