types: Strengthen autocomplete option types
discordjs/discord.js pull request #6950
Opened 2021-11-06 21:18 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Prevents combinations where `choices` and `autocomplete` are present, and instead makes them mutually exclusive props on `ApplicationCommandOptionData`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-11-08 11:36 UTC, kyranet requested changes

2021-11-08 11:36 UTC, kyranet commented on typings/tests.ts
> +  // @ts-ignore
Do we not want this instead?
```suggestion
  // @ts-expect-error
```

2021-11-11 18:06 UTC, vladfrangu approved these changes

2021-11-11 18:10 UTC, kyranet approved these changes

2021-11-11 18:15 UTC, SpaceEEC approved these changes

2021-11-11 18:38 UTC, merged