types(ApplicationCommandManager): Deprecate old `*Data` type usages and allow camel cased dapi types to be used
discordjs/discord.js pull request #6959
Opened 2021-11-09 00:00 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Ref: #6958 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-11-09 00:08 UTC, ImRodry commented
Do we really need to add a dependency for types only? Most people don't use typescript and the package offers much more than the type that is being imported, I believe we could simply create the type ourselves instead

2021-11-09 00:14 UTC, suneettipirneni commented
> Do we really need to add a dependency for types only? Most people don't use typescript and the package offers much more than the type that is being imported, I believe we could simply create the type ourselves instead

It's a dev dep, so why does it matter. And the camel case util type here is more sophisticated. It's not that simple to implement one our own that's as robust as this one.

2021-11-09 00:19 UTC, ImRodry commented
If it’s a dev dev then these types won’t even work at all because the package wouldn’t get installed. We can simply copy the type from them and add it ourselves

2021-11-09 16:25 UTC, almeidx requested changes

2021-11-09 16:25 UTC, almeidx commented on typings/index.d.ts
> +import type { CamelCasedPropertiesDeep } from 'type-fest';
```suggestion
```

2021-11-09 16:30 UTC, suneettipirneni commented
We won't be using our own version of Camelizer. We are going to stick with the package that was originally brought up in this PR.

2021-11-09 18:20 UTC, almeidx commented on typings/index.d.ts
> +export type foo = Camelize<RESTPostAPIApplicationCommandsJSONBody>['options'];
😕

2021-11-10 01:15 UTC, Jiralite commented on tslint.json
> +    "unified-signatures": false
With the introduction of `unified-signatures: false`, I believe these can be safely removed now:

https://github.com/discordjs/discord.js/blob/9d7152f0fdcd879cad654fe4fdd658fac57ceb02/typings/index.d.ts#L2341-L2345

https://github.com/discordjs/discord.js/blob/9d7152f0fdcd879cad654fe4fdd658fac57ceb02/typings/index.d.ts#L3095-L3099

2021-11-23 11:33 UTC, vladfrangu commented
Well what do ya know! This needs a rebase

2021-11-23 11:36 UTC, vladfrangu approved these changes
🎉

2021-11-23 11:36 UTC, vladfrangu commented on typings/tests.ts
> +}
What's the point of this test? You're just checking a discord-api-type 👀

2021-11-23 17:02 UTC, iCrawl commented
This needs another rebase for the new type testing PR that landed.

2021-11-27 11:36 UTC, SpaceEEC approved these changes

2021-11-29 10:17 UTC, merged