feat: add ThreadChannel#viewable
discordjs/discord.js pull request #6975
Opened 2021-11-12 04:04 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Closes #6969 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-11-12 10:03 UTC, Jiralite requested changes
Whilst this pull request _does_ fix the issue linked, it doesn't fix all instances of it.

Consider the scenario where a thread becomes locked or the client fetches a thread that happens to be locked without the manage threads permission. Then, consider the client fetching a message and running `Message#editable`. Through that, the result will be `true` but it should be `false` because the thread is locked and messages cannot be edited.

2021-11-12 10:16 UTC, suneettipirneni commented
> Whilst this pull request _does_ fix the issue linked, it doesn't fix all instances of it.
> 
> 
> 
> Consider the scenario where a thread becomes locked or the client fetches a thread that happens to be locked without the manage threads permission. Then, consider the client fetching a message and running `Message#editable`. Through that, the result will be `true` but it should be `false` because the thread is locked and messages cannot be edited.

Good catch! I'm thinking even if it's locked and you have manage_threads perms `editable` should probably still be `false`, simply because the current state of the thread is still archived, and I believe editing a message doesn't implicitly unarchive it.

2021-11-12 10:23 UTC, Jiralite commented
> I'm thinking even if it's locked and you have manage_threads perms `editable` should probably still be `false`

Right.

2021-11-12 12:28 UTC, iCrawl approved these changes

2021-11-13 14:41 UTC, Jiralite approved these changes

2021-11-16 15:36 UTC, SpaceEEC approved these changes

2021-11-16 19:07 UTC, kyranet approved these changes

2021-11-18 06:58 UTC, merged