Chore(ThreadMemberManager): make `#fetch` only take one object parameter
discordjs/discord.js pull request #6997
Opened 2021-11-17 03:21 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

@Jiralite pointed out this one out (and it's still not breaking!)

**Status and versioning classification:**

Please move lines that apply to you out of the comment:
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-11-17 07:09 UTC, ImRodry reviewed
Personally, I don’t agree with this. Despite the member parameter being optional, the options object is only ever used if a member is provided, so it wouldn’t make sense to do fetch({force:true}) or even fetch({cache:true}) as that can simply be replaced by fetch(true). Either way, just my two cents

2021-11-17 07:09 UTC, ImRodry commented on typings/index.d.ts
> +  rateLimitPerUser?: number;
Once again xD

2021-11-17 16:29 UTC, suneettipirneni commented
> Personally, I don’t agree with this. Despite the member parameter being optional, the options object is only ever used if a member is provided, so it wouldn’t make sense to do fetch({force:true}) or even fetch({cache:true}) as that can simply be replaced by fetch(true). Either way, just my two cents

Yeah I'm starting to agree with this, I think I'll just remove the deprecation on the boolean overload.

2021-11-23 17:03 UTC, iCrawl commented
This needs another rebase for the new type testing PR that landed.

2021-11-27 11:35 UTC, SpaceEEC commented
Isn't this breaking? The second parameter exists in stable (13.3.1)
https://github.com/discordjs/discord.js/blob/13.3.1/src/managers/ThreadMemberManager.js#L110-L121

2021-11-27 16:14 UTC, suneettipirneni commented
> Isn't this breaking? The second parameter exists in stable (13.3.1)
> 
> https://github.com/discordjs/discord.js/blob/13.3.1/src/managers/ThreadMemberManager.js#L110-L121

Welp, semver: major it is

2021-12-03 14:28 UTC, vladfrangu requested changes
Code doesn't align with implementation

2022-01-07 22:56 UTC, vladfrangu requested changes

2022-01-07 22:56 UTC, vladfrangu commented on packages/discord.js/src/managers/ThreadManager.js
> -    rateLimitPerUser,
Why was this removed?

2022-01-07 23:01 UTC, almeidx commented on packages/discord.js/src/managers/ThreadManager.js
> -   * @property {number} [rateLimitPerUser] The rate limit per user (slowmode) for the new channel in seconds
This should probably be added back too

2022-01-07 23:04 UTC, vladfrangu approved these changes

2022-01-07 23:17 UTC, iCrawl approved these changes

2022-01-08 11:22 UTC, SpaceEEC approved these changes

2022-01-08 11:42 UTC, merged