feat: add `UserContextMenuInteraction` and `MessageContextMenuInteraction`
discordjs/discord.js pull request #7003
Opened 2021-11-18 17:12 UTC by GrapeColor

**Please describe the changes this PR makes and why it should be merged:**
Add `UserContextMenuInteraction` and `MessageContextMenuInteraction`.

Currently, the context menu interaction is unified to `ContextMenuInteraction`.
Therefore, target users and messages must use `interaction.options.getUser('user')` and `interaction.options.getMessage('message')`.
This isn't intuitive, so we'll separate the classes and add getter functions.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-11-18 18:06 UTC, suneettipirneni reviewed
I might be missing something here, but where are these new classes being created in the lib? The typeguard is misleading if the actual runtime version of the class is still a `ContextMenuInteraction` and not a more specific type.

2021-11-18 18:40 UTC, ImRodry commented on src/structures/UserContextMenuInteraction.js
> +    return this.options.getMember(this.targetId);
```suggestion
    return this.options.getMember(‘user’);
```

2021-11-18 20:14 UTC, almeidx commented on src/structures/UserContextMenuInteraction.js
> +    return this.options.getMember(this.targetId);
```js
    return this.options.getMember('user');
```

2021-11-19 02:20 UTC, GrapeColor commented on src/structures/UserContextMenuInteraction.js
> +    return this.options.getMember(this.targetId);
That's right.
Thank you.

2021-11-19 02:43 UTC, GrapeColor commented
> I might be missing something here, but where are these new classes being created in the lib? The typeguard is misleading if the actual runtime version of the class is still a `ContextMenuInteraction` and not a more specific type.

I'm sorry.
Now I have added a new class to the `InteractionCreate`.

2021-11-19 18:41 UTC, suneettipirneni requested changes

2021-11-19 18:41 UTC, suneettipirneni commented on typings/index.d.ts
> +export class MessageContextMenuInteracion<Cached extends CacheType = CacheType> extends ContextMenuInteraction<Cached> {
typo
```suggestion
export class MessageContextMenuInteraction<Cached extends CacheType = CacheType> extends ContextMenuInteraction<Cached> {
```

2021-11-23 11:38 UTC, vladfrangu requested changes

2021-11-23 11:38 UTC, vladfrangu commented on typings/index.d.ts
> +  public targetMessage: CacheTypeReducer<Cached, Message, APIMessage>;
```suggestion
  public readonly targetMessage: CacheTypeReducer<Cached, Message, APIMessage>;
```

2021-11-23 11:38 UTC, vladfrangu commented on typings/index.d.ts
> +  public targetMember: CacheTypeReducer<Cached, GuildMember, APIInteractionGuildMember>;
```suggestion
  public readonly targetUser: User;
  public readonly targetMember: CacheTypeReducer<Cached, GuildMember, APIInteractionGuildMember>;
```

2021-11-23 13:11 UTC, GrapeColor commented
Thank you all for your helps.

2021-11-23 13:25 UTC, vladfrangu approved these changes

2021-11-24 13:31 UTC, kyranet approved these changes

2021-11-27 11:29 UTC, SpaceEEC approved these changes

2021-11-27 17:53 UTC, GrapeColor commented
I'm sorry for your review.
I forgot to add the classes to `index.js`.
Really sorry.

2021-11-27 17:54 UTC, SpaceEEC approved these changes

2021-11-27 17:59 UTC, vladfrangu approved these changes

2021-12-01 11:31 UTC, iCrawl approved these changes

2021-12-01 11:31 UTC, merged