feat(Client): add stickers method
discordjs/discord.js pull request #7075
Opened 2021-12-07 20:10 UTC by XEfnexX

**Add Sticker method (like <Client>.emojis) to Client**

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-12-07 20:29 UTC, XEfnexX commented
I hope I didn't do anything wrong or forgot something.
It's my first pull requests and I'm open for feedback.

2021-12-08 10:05 UTC, SpaceEEC requested changes
The new sticker classes aren't adding anything (except `deletable`, which could be moved to `Sticker`), so they should be removed.

2021-12-08 10:05 UTC, SpaceEEC commented on src/managers/BaseGuildStickerManager.js
> +class BaseGuildStickerManager extends CachedManager {
Maybe also rename it to `BaseStickerManager` and have `StickerManager` extend it.

2021-12-09 11:29 UTC, XEfnexX commented
Well, then my first tried commit was a flop...already thought that.
Thank you. I'll close it now.

2021-12-09 11:29 UTC, closed without merging