refactor(UserManager): Move methods to the manager
discordjs/discord.js pull request #7087
Opened 2021-12-09 01:21 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
This moves the following methods to the manager:

- createDM()
- deleteDM()
- fetchFlags()

The `User` class isn't needed for these requests which in turn only made these possible via doing:

```JavaScript
<Client>.users.fetch("user_id").then(async user => {
  const dmChannel = await user.createDM();
  // ...
});
```

But now, only one API call will be made:

```JavaScript
<Client>.users.createDM("user_id").then(dmChannel => {
  // ...
});
```

I haven't moved `.send()` so one can straight up send a message to a user even if they're not cached as I realised that this internally does (potentially) 2 API calls initially and would total to 3 API calls if added. If this is still desired, it can happen! But, I don't think I can do the magic of `TextBasedChannel.applyToClass()` as another parameter is needed, so it would have to be documented separately.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-12-09 12:32 UTC, kyranet approved these changes

2021-12-09 12:40 UTC, vladfrangu approved these changes

2021-12-10 09:09 UTC, iCrawl approved these changes

2021-12-14 18:04 UTC, SpaceEEC requested changes
Just a small nit

2021-12-14 18:04 UTC, SpaceEEC commented on src/managers/UserManager.js
> +   * The DM between the client's user and this user
```suggestion
   * The DM between the client's user and a user
```

2021-12-22 13:18 UTC, SpaceEEC submitted a review, later dismissed
Otherwise lgtm

2021-12-22 13:18 UTC, SpaceEEC commented on src/managers/UserManager.js
> +
```suggestion
```

2021-12-22 13:23 UTC, SpaceEEC approved these changes

2021-12-22 13:25 UTC, merged