refactor: import timers, `process`, and `Buffer` from `node:`
discordjs/discord.js pull request #7157
Opened 2021-12-27 15:04 UTC by kyranet

**Please describe the changes this PR makes and why it should be merged:**

Following [this Tweet](https://twitter.com/kt3k/status/1475391353375031301), this PR imports `process`, `Buffer`, and timers (`setTimeout`, `setInterval`, and `setImmediate`) from their respective modules.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2021-12-27 15:07 UTC, iCrawl approved these changes

2021-12-27 15:20 UTC, muchnameless commented on test/webhooktest.js
> +const { setTimeout: sleep } = require('node:timers');
```suggestion
const { setTimeout: sleep } = require('node:timers/promises');
```

2021-12-27 16:11 UTC, almeidx commented
Might be worth enabling the [no-restricted-globals eslint rule](https://eslint.org/docs/rules/no-restricted-globals) and disable `process`, `Buffer`, etc.

2021-12-27 19:22 UTC, almeidx requested changes

2021-12-27 19:22 UTC, almeidx commented on .eslintrc.json
> +        "message": "Import Buffer from `node:buffer` instead of using the global"
```suggestion
        "message": "Import Buffer from `node:buffer` instead"
```

2021-12-27 19:22 UTC, almeidx commented on .eslintrc.json
> +        "message": "Import process from `node:process` instead of using the global"
```suggestion
        "message": "Import process from `node:process` instead"
```

2021-12-27 19:22 UTC, almeidx commented on .eslintrc.json
> +        "message": "Import setTimeout from `node:timers` instead of using the global"
```suggestion
        "message": "Import setTimeout from `node:timers` instead"
```

2021-12-27 19:22 UTC, almeidx commented on .eslintrc.json
> +        "message": "Import setInterval from `node:timers` instead of using the global"
```suggestion
        "message": "Import setInterval from `node:timers` instead"
```

2021-12-27 19:22 UTC, almeidx commented on .eslintrc.json
> +        "message": "Import setImmediate from `node:timers` instead of using the global"
```suggestion
        "message": "Import setImmediate from `node:timers` instead"
```

2021-12-27 20:53 UTC, SpaceEEC approved these changes

2021-12-27 21:00 UTC, vladfrangu approved these changes

2021-12-28 09:15 UTC, merged

2021-12-31 08:25 UTC, blattersturm commented
I'm still missing `clearTimeout` being imported here in files such as `GuildMemberManager.js`. This may work well in pure Node runtimes, but elsewhere this may lead to a mismatch.

2021-12-31 08:37 UTC, kyranet commented
Oh. Good catch, I'll make a PR in a bit.

2022-01-14 11:30 UTC, blattersturm commented
@kyranet have you managed to get this fixed yet? People are still [hitting issues](https://forum.cfx.re/t/discord-js-13-0-0/4778143/14?u=d-bubble) in our embedded runtime.

2022-01-14 12:01 UTC, kyranet commented
Yes, I just opened https://github.com/discordjs/discord.js/pull/7269 to fix that, sorry for the delay, I have been busy with exams 😅