refactor: make `intersect` perform a true intersection
discordjs/discord.js pull request #7211
Opened 2022-01-08 01:55 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

See: 
- https://github.com/discordjs/collection/issues/58

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-01-08 01:59 UTC, vladfrangu approved these changes

2022-01-08 03:14 UTC, almeidx commented on packages/collection/src/index.ts
> +			if (v2 !== undefined && Object.is(v, v2)) {
What if `V` extends `undefined`? Probably want to use `this.has()` instead

2022-01-08 08:53 UTC, kyranet requested changes
Are you sure you meant to type the values of the resulting collection as `T | V`? I don't see any code that would set `V` into the collection, only `T`.

2022-01-08 08:53 UTC, kyranet commented on packages/collection/src/index.ts
> +			if (this.has(k) && Object.is(v, other.get(k))) {
Did you mean to do this instead?
```suggestion
			if (this.has(k) && Object.is(v, this.get(k))) {
```

`other.get(k)` (while iterating `other`) equals to `v`, so this statement will never be false.

2022-01-08 15:25 UTC, kyranet approved these changes

2022-01-08 21:59 UTC, iCrawl approved these changes

2022-01-11 11:04 UTC, SpaceEEC approved these changes

2022-01-11 11:29 UTC, merged