refactor: remove djs components and use /builders components instead
discordjs/discord.js pull request #7252
Opened 2022-01-11 21:55 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Components from builders are reexported for convenience. 

Prerequisite:
- #7195 

**Status and versioning classification:**
Please move lines that apply to you out of the comment:
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-01-13 16:58 UTC, iCrawl commented
Still having linting errors here.

2022-01-13 16:58 UTC, imranbarbhuiya commented on packages/discord.js/src/structures/MessagePayload.js
> +const { createComponent } = require('@discordjs/builders');
due to this import position

2022-01-14 12:21 UTC, kyranet commented
Please rebase, you have merge conflicts.

2022-01-14 17:05 UTC, iCrawl commented
This needs a rebase.

2022-01-15 00:36 UTC, vladfrangu requested changes

2022-01-15 00:36 UTC, vladfrangu commented on packages/discord.js/src/structures/Message.js
> +      this.components = data.components.map(createComponent);
From what I heard this is much more performant than passing the method directly

```suggestion
      this.components = data.components.map(c => createComponent(c));
```

2022-01-15 02:13 UTC, suneettipirneni commented
Don't merge yet, there's a performance pitfall that I need to address that occurs in the `MessagePayload` serialization. I'll fix this soon.

2022-01-15 17:57 UTC, vladfrangu approved these changes

2022-01-15 19:02 UTC, iCrawl approved these changes

2022-01-17 02:12 UTC, kyranet approved these changes

2022-01-17 12:09 UTC, SpaceEEC approved these changes

2022-01-17 12:13 UTC, merged