fix(ApplicationCommand): use new ApplicationCommandOptionType enums
discordjs/discord.js pull request #7257
Opened 2022-01-12 17:24 UTC by Koyamie

2022-01-12 17:25 UTC, vladfrangu approved these changes
This is why we use Enums for this...

2022-01-12 17:42 UTC, Koyamie commented
Fixed `ApplicationCommandOptionType` in `transformOption` too.

2022-01-12 18:02 UTC, Koyamie commented
Fixed components that were not using discord api types.

2022-01-13 16:28 UTC, ImRodry commented
> This is why we use Enums for this...

so why don't we change all of these instances in this PR to use enums? Would be quite easy

2022-01-13 16:56 UTC, iCrawl requested changes

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/ApplicationCommand.js
> -        option.required ?? (stringType === 'SUB_COMMAND' || stringType === 'SUB_COMMAND_GROUP' ? undefined : false),
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    if (this._hoistedOptions[0]?.type === 'SUB_COMMAND') {
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'CHANNEL', ['channel'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'BOOLEAN', ['value'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'INTEGER', ['value'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'NUMBER', ['value'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'USER', ['user'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'MENTIONABLE', ['user', 'member', 'role'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'ROLE', ['role'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/CommandInteractionOptionResolver.js
> -    const option = this._getTypedOption(name, 'USER', ['member'], required);
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/MessageActionRow.js
> -    super({ type: 'ACTION_ROW' });
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/MessageButton.js
> -    super({ type: 'BUTTON' });
Revert this.

2022-01-13 16:56 UTC, iCrawl commented on packages/discord.js/src/structures/MessageSelectMenu.js
> -    super({ type: 'SELECT_MENU' });
Revert this.

2022-01-13 16:58 UTC, Koyamie commented
I should close the PR at this point lol

2022-01-13 16:59 UTC, ImRodry commented
What’s the point of leaving all of that broken even if it’s going to be changed soon? The dev builds are unusable at the moment because of this

2022-01-13 17:00 UTC, iCrawl commented
@Koyamie The other fixes are still valid

2022-01-13 22:43 UTC, iCrawl approved these changes

2022-01-13 23:20 UTC, merged