feat(Collection): add merging functions
discordjs/discord.js pull request #7299
Opened 2022-01-18 22:16 UTC by 1Computer1

**Please describe the changes this PR makes and why it should be merged:**

#7211 removes a use-case from `intersection`, so might as well just cover them all with `merge`.
Then `combineEntries` is basically `merge` but for a bunch of entries instead of two collections.

Prior art [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:intersection) and [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Merge-Lazy.html#v:merge) and [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:fromListWith).

@suneettipirneni 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-01-24 19:12 UTC, iCrawl approved these changes

2022-01-24 19:51 UTC, SpaceEEC approved these changes

2022-01-24 21:21 UTC, vladfrangu requested changes

2022-01-24 21:21 UTC, vladfrangu commented on packages/collection/src/index.ts
> +			}
Can you cache the results of this.has/other.has, and re-use them? 
```suggestion
			const hasInSelf = this.has(k);
			const hasInOther = other.has(k);

			if (hasInSelf && hasInOther) {
				const r = whenInBoth(this.get(k)!, other.get(k)!, k);
				if (r.keep) coll.set(k, r.value);
			} else if (hasInSelf) {
				const r = whenInSelf(this.get(k)!, k);
				if (r.keep) coll.set(k, r.value);
			} else if (hasInOther) {
				const r = whenInOther(other.get(k)!, k);
				if (r.keep) coll.set(k, r.value);
			}
```

2022-01-26 10:13 UTC, kyranet approved these changes

2022-01-26 20:46 UTC, merged