feat: allow setting message flags when sending
discordjs/discord.js pull request #7312
Opened 2022-01-20 12:48 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
- https://github.com/discord/discord-api-docs/pull/4356
- https://github.com/discord/discord-api-docs/pull/4357

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-01-20 13:31 UTC, vladfrangu submitted a review, later dismissed

2022-01-20 13:31 UTC, vladfrangu commented on packages/discord.js/src/structures/interfaces/TextBasedChannel.js
> +   * Only `SUPPRESS_EMBEDS` and `EPHEMERAL` can be set.
This is wrong. Only suppress_embeds can be set here at this time

2022-01-20 13:57 UTC, vladfrangu commented
You need to document it for Interaction replies that EPHEMERAL can be used, which may be painful..

2022-01-20 16:48 UTC, suneettipirneni requested changes

2022-01-20 16:48 UTC, suneettipirneni commented on packages/discord.js/src/structures/MessagePayload.js
> +      flags |= MessageFlags.FLAGS.EPHEMERAL;
You can use -types `MessageFlag` here instead. I'll be removing the `FLAGS` prop from the bitfield in my other PR.

2022-01-24 19:42 UTC, SpaceEEC approved these changes

2022-01-24 21:17 UTC, vladfrangu approved these changes

2022-01-24 21:28 UTC, almeidx commented
Rebased

2022-01-25 07:39 UTC, iCrawl approved these changes

2022-01-25 19:05 UTC, almeidx commented
Upstream pull request has been merged

2022-01-25 20:23 UTC, merged