docs: add slash command builders example, fixes #7338
discordjs/discord.js pull request #7339
Opened 2022-01-25 10:35 UTC by sanjaybaskaran01

**Please describe the changes this PR makes and why it should be merged:**
Fixes #7338 and adds the example for slash command builder

**Status and versioning classification:**
Example taken from [here](https://github.com/discordjs/builders/blob/main/docs/examples/Slash%20Command%20Builders.md)

This PR **only** includes non-code changes, like changes to documentation, README

2022-01-25 12:37 UTC, iCrawl commented on packages/builders/.gitignore
> -!docs/README.md
?

2022-02-09 15:33 UTC, thebigwolfy approved these changes

2022-02-09 20:04 UTC, kyranet requested changes
Ran the examples thru prettier and also made some minor stylistic changes.

2022-02-09 20:04 UTC, kyranet commented on packages/builders/docs/examples/Slash Command Builders.md
> +);
```suggestion
const pointsCommand = new SlashCommandBuilder()
	.setName('points')
	.setDescription('Lists or manages user points')

	// Add a manage group
	.addSubcommandGroup((group) =>
		group
			.setName('manage')
			.setDescription('Shows or manages points in the server')
			.addSubcommand((subcommand) =>
				subcommand
					.setName('user_points')
					.setDescription("Alters a user's points")
					.addUserOption((option) =>
						option.setName('user').setDescription('The user whose points to alter').setRequired(true),
					)
					.addStringOption((option) =>
						option
							.setName('action')
							.setDescription('What action should be taken with the users points?')
							.addChoices([
								['Add points', 'add'],
								['Remove points', 'remove'],
								['Reset points', 'reset'],
							])
							.setRequired(true),
					)
					.addIntegerOption((option) => option.setName('points').setDescription('Points to add or remove')),
			),
	)

	// Add an information group
	.addSubcommandGroup((group) =>
		group
			.setName('info')
			.setDescription('Shows information about points in the guild')
			.addSubcommand((subcommand) =>
				subcommand.setName('total').setDescription('Tells you the total amount of points given in the guild'),
			)
			.addSubcommand((subcommand) =>
				subcommand
					.setName('user')
					.setDescription("Lists a user's points")
					.addUserOption((option) =>
						option.setName('user').setDescription('The user whose points to list').setRequired(true),
					),
			),
	);
```

2022-02-09 20:04 UTC, kyranet commented on packages/builders/docs/examples/Slash Command Builders.md
> +);
```suggestion
const boopCommand = new SlashCommandBuilder()
	.setName('boop')
	.setDescription('Boops the specified user, as many times as you want')
	.addUserOption((option) => option.setName('user').setDescription('The user to boop').setRequired(true))

	// Adds an integer option
	.addIntegerOption((option) =>
		option.setName('boop_amount').setDescription('How many times should the user be booped (defaults to 1)'),
	)

	// Supports choices too!
	.addIntegerOption((option) =>
		option
			.setName('boop_reminder')
			.setDescription('How often should we remind you to boop the user')
			.addChoice('Every day', 1)
			.addChoice('Weekly', 7)
			// Or, if you prefer adding more choices at once, you can use an array
			.addChoices([
				['Every three months', 90],
				['Yearly', 365],
			]),
	);
```

2022-02-13 11:41 UTC, iCrawl approved these changes

2022-02-13 11:42 UTC, merged