docs: correct intent docs
discordjs/discord.js pull request #7375
Opened 2022-01-31 16:20 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-01-31 16:32 UTC, vladfrangu approved these changes

2022-01-31 18:16 UTC, iCrawl approved these changes

2022-02-01 10:51 UTC, kyranet approved these changes

2022-02-01 11:07 UTC, SpaceEEC requested changes
![image](https://user-images.githubusercontent.com/24881032/151957219-fb2d959d-4d97-46cb-8042-9c6b68a0c578.png)
Very informative.

---

![image](https://user-images.githubusercontent.com/24881032/151957301-7b480013-528c-41f3-8030-e6ee7b0071e1.png)
How is a non-clickable type "correct"?

Much less since it's of the same type as `IntentsBitField.Flags`, we surely don't accept that in the constructor.

---

And lastly: I see nothing wrong with the type before the change, it seems to be accurate to me.

2022-02-01 12:45 UTC, ImRodry commented
> How is a non-clickable type "correct"?

Isn’t the goal to make a -types documentation website and have these links point there? There’s a bunch of types in the docs that come from the package already

2022-02-01 18:36 UTC, closed without merging