refactor: Make constants enums top level and `PascalCase`
discordjs/discord.js pull request #7379
Opened 2022-01-31 19:00 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-01-31 20:58 UTC, ImRodry requested changes
Two questions: why are these constants being moved to their own files if they're still constants? And why are they PascalCased if they're immutable constants, which are [usually](https://www.robinwieruch.de/javascript-naming-conventions/) UPPERCASED in JavaScript?

2022-01-31 21:01 UTC, suneettipirneni commented
> Two questions: why are these constants being moved to their own files if they're still constants? And why are they PascalCased if they're immutable constants, which are [usually](https://www.robinwieruch.de/javascript-naming-conventions/) UPPERCASED in JavaScript?

Just to be clear, enums themselves are namespaces of immutable constant values, and we use PascalCase for those. Whenever we migrate to typescript these constant objects will most definitely be converted to ts enums.

2022-01-31 21:37 UTC, ImRodry commented
The biggest benefit I see and the reason why they were there to begin with was organization, so that we can have all enums in one single place. They’re still all immutable constants so I think they should stay UPPERCASED like they were before

2022-02-01 10:49 UTC, kyranet commented
Namespaces and enums are and still should be PascalCased, including those that aren't but look like it, as @suneettipirneni said.

This change also brings consistency in the project, so yeah, that's a final say.

2022-02-01 10:50 UTC, kyranet approved these changes
Only thing I'd change would be changing `module.exports = createEnum(...);` to `exports.EnumName = createEnum(...);` so we have 1 thing less to do when we rewrite to TypeScript, but this is fine too.

2022-02-01 11:11 UTC, SpaceEEC approved these changes

2022-02-02 10:02 UTC, iCrawl approved these changes

2022-02-02 10:29 UTC, vitorlops commented on packages/discord.js/src/client/websocket/handlers/THREAD_UPDATE.js
> +    client.emit(Events.ThreadCreate, old, updated);
```suggestion
    client.emit(Events.ThreadUpdate, old, updated);
```
Isn't it supposed to be `ThreadUpdate`?

2022-02-02 10:29 UTC, vitorlops commented on packages/discord.js/src/structures/InteractionCollector.js
> +      this.client.on(Events.MessageDelete, bulkDeleteListener);
```suggestion
      this.client.on(Events.MessageBulkDelete, bulkDeleteListener);
```

2022-02-03 07:29 UTC, iCrawl commented
This needs a rebase.

2022-02-04 19:41 UTC, vladfrangu requested changes

2022-02-04 19:41 UTC, vladfrangu commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +const Opcodes = require('../../util/Opcodes');
Isn't this an enum in -types?

2022-02-04 19:41 UTC, vladfrangu commented on packages/discord.js/src/managers/RoleManager.js
> +   *   color: 'Blue',
🤔

2022-02-04 19:41 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
> +export enum Colors {
This isn't an actual enum but an object

2022-02-04 19:41 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
> +export enum Events {
Ditto

2022-02-05 18:21 UTC, vladfrangu approved these changes

2022-02-05 18:56 UTC, merged