refactor: make public builder props getters
discordjs/discord.js pull request #7422
Opened 2022-02-07 14:52 UTC by suneettipirneni

This is a replacement for the previous pr since gh is having trouble loading the diffs.

**Please describe the changes this PR makes and why it should be merged:**

Stores raw api data in a `data` object and allows access to builder properties via getters.

### Rationale

There's quite a few benefits in using getters for builders:

- Currently builders relies on `Reflect#set` which is much slower than direct prop assignment, in one benchmark [I did it was waaay slower than direct assignment](https://www.measurethat.net/Benchmarks/ShowResult/263962). Beyond performance `Reflect#set` is less typesafe since property keys are strings and it allows values to be set as `any`. This PR removes the usage of these methods, and preserves the `readonly` nature of the fields.

- The classes are now more flexible. For example, right now if we decided to add a field to any builder class, it would be outputted in `toJSON` simply because `toJSON` just spreads `this`: `{ ...this }`. In addition, since we now have getters we can do any computation *before* a value is returned unlike a regular field.

- Constructor assignment is easy, in some cases it's just assigning `this.data = data`. `toJSON` is straightforward as well, as it's essentially just returning a copy of `this.data`.

- Allows for idiomatic js/ts class field naming. The props are simply retrieved from `this.data` so they're not constrained to any naming conventions used by the API.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-02-07 15:10 UTC, almeidx requested changes

2022-02-07 15:10 UTC, almeidx commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +		this.data.fields?.splice(index, deleteCount, ...UnsafeEmbed.normalizeFields(...fields));
```suggestion
		this.data.fields ??= [];
		this.data.fields.splice(index, deleteCount, ...UnsafeEmbed.normalizeFields(...fields));
```

2022-02-07 19:34 UTC, kyranet requested changes

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/components/ActionRow.ts
> +		}
```suggestion
		const { components, ...initData } = data ?? {};
		super({ type: ComponentType.ActionRow, ...initData });
```

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/components/ActionRow.ts
> +		this.components = (data?.components?.map(createComponent) ?? []) as T[];
```suggestion
		this.components = (components?.map(createComponent) ?? []) as T[];
```

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
> +		this.options = data?.options?.map((o) => new UnsafeSelectMenuOption(o)) ?? [];
```suggestion
		const { options, ...initData } = data ?? {};
		super({ type: ComponentType.SelectMenu, ...initData });

		this.options = options?.map((o) => new UnsafeSelectMenuOption(o)) ?? [];
```

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/messages/embed/Embed.ts
> +		validateFieldLength(this.fields ?? [], fields.length);
`validateFieldLength` should be tweaked to support undefined as first parameter, so no extra allocations are needed.

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +			(this.data.fields ?? []).reduce((prev, curr) => prev + curr.name.length + curr.value.length, 0) +
One allocation less:
```suggestion
			(this.data.fields?.reduce((prev, curr) => prev + curr.name.length + curr.value.length, 0) ?? 0) +
```

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +		this.data.fields.push(...UnsafeEmbed.normalizeFields(...fields));
We can do this to make this faster:

```suggestion
		fields = UnsafeEmbed.normalizeFields(...fields);
	
		if (this.data.fields) this.data.fields.push(...fields);
		else this.data.fields = fields;
```

2022-02-07 19:34 UTC, kyranet commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +		this.data.fields.splice(index, deleteCount, ...UnsafeEmbed.normalizeFields(...fields));
More optimization! `Array#splice` sets all the elements passed via rest when the source array is empty, so we can optimize this by just making the fields array be the passed fields.
```suggestion
		fields = UnsafeEmbed.normalizeFields(...fields);

		if (this.data.fields) this.data.fields.splice(index, deleteCount, ...fields);
		else this.data.fields = fields;
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/Component.ts
> +	 * The api data associated with this component
```suggestion
	 * The API data associated with this component
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/button/UnsafeButton.ts
> +	 * Whether or not this button is disabled
```suggestion
	 * Whether this button is disabled
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/button/UnsafeButton.ts
> +	 * The custom ID of this button (only defined on non-link buttons)
```suggestion
	 * The custom id of this button (only defined on non-link buttons)
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/button/UnsafeButton.ts
>  	 * @param customId The custom ID to use for this button
```suggestion
	 * @param customId The custom id to use for this button
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
> +	 * The custom ID of this select menu
```suggestion
	 * The custom id of this select menu
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
> +	 * Whether or not this select menu is disabled
```suggestion
	 * Whether this select menu is disabled
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
>  	 * @param customId The custom ID to use for this select menu
```suggestion
	 * @param customId The custom id to use for this select menu
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/selectMenu/UnsafeSelectMenuOption.ts
> +	 * Whether or not this option is selected by default
```suggestion
	 * Whether this option is selected by default
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/components/selectMenu/UnsafeSelectMenuOption.ts
>  	 * @param isDefault Whether or not this option is selected by default
```suggestion
	 * @param isDefault Whether this option is selected by default
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +	 * The url of the icon
```suggestion
	 * The URL of the icon
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +	 * The proxy url of the icon
```suggestion
	 * The proxy URL of the icon
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
>  	 * The embed url
```suggestion
	 * The embed URL
```

2022-02-08 16:40 UTC, Jiralite commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
>  	 * The timestamp of the embed in the ISO format
```suggestion
	 * The timestamp of the embed in an ISO 8601 format
```

2022-02-09 17:18 UTC, kyranet approved these changes

2022-02-09 18:06 UTC, iCrawl approved these changes

2022-02-10 18:58 UTC, vladfrangu requested changes

2022-02-10 18:58 UTC, vladfrangu commented on packages/builders/__tests__/components/selectMenu.test.ts
> +				// @ts-expect-error
Whats the reason for this? is it just because selectWithoutOptions doesn't have options defined?

2022-02-10 18:58 UTC, vladfrangu commented on packages/builders/src/components/ActionRow.ts
> +		this.components = (components?.map(createComponent) ?? []) as T[];
Please don't .map like that, but only with the args you need

2022-02-10 18:58 UTC, vladfrangu commented on packages/builders/src/components/Component.ts
> +	protected data: DataType;
You don't set this.data again right, just its properties? If so, mark it as readonly

```suggestion
	protected readonly data: DataType;
```

2022-02-10 18:58 UTC, vladfrangu commented on packages/builders/src/components/button/UnsafeButton.ts
> +export interface ButtonComponentData extends Omit<APIButtonComponent, 'type'> {
Partial it

2022-02-10 18:58 UTC, vladfrangu commented on packages/builders/src/messages/embed/Assertions.ts
> +export function validateFieldLength(fields: APIEmbedField[] | undefined, amountAdding: number): void {
```suggestion
export function validateFieldLength(fields?: APIEmbedField[], amountAdding: number): void {
```

2022-02-10 19:02 UTC, vladfrangu commented on packages/builders/src/components/ActionRow.ts
> +	type?: ComponentType.ActionRow;
I meant in the constructor, and also that would technically be correct type wise

2022-02-10 19:06 UTC, almeidx commented on packages/builders/src/messages/embed/Assertions.ts
> +export function validateFieldLength(fields: APIEmbedField[] | undefined, amountAdding: number): void {
Can't have a required parameter after an optional parameter

2022-02-12 20:21 UTC, vladfrangu commented
This needs a rebase

2022-02-12 20:22 UTC, vladfrangu requested changes

2022-02-12 20:22 UTC, vladfrangu commented on packages/builders/src/components/ActionRow.ts
> +		} as APIActionRowComponent;
Why is this cast needed? 👀

2022-02-13 11:49 UTC, vladfrangu approved these changes

2022-02-13 12:06 UTC, merged