fix: properly serialize `undefined` values
discordjs/discord.js pull request #7497
Opened 2022-02-18 20:51 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

This fixes an issue where if a value is explicitly set to `undefined`, it would be serialized as `{}`.

Closes #7510 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-02-18 20:53 UTC, vladfrangu requested changes

2022-02-18 20:53 UTC, vladfrangu commented on packages/discord.js/src/util/Transformers.js
> +        typeof value === 'undefined' ? value : Transformers.toSnakeCase(value),
you should just remove the default of `obj = {}` instead

2022-02-18 21:03 UTC, vladfrangu approved these changes

2022-02-18 21:23 UTC, kyranet approved these changes

2022-02-20 12:41 UTC, iCrawl approved these changes

2022-02-20 12:41 UTC, merged