feat: add Partials class
discordjs/discord.js pull request #7503
Opened 2022-02-19 00:49 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**

This PR transforms Partials into a class that extends BitField so that we can have properties like All, which adds all partials into an array, and other methods from the inherited class

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-02-19 02:11 UTC, ItsJackson reviewed
There’s a error running the ESLint check, with code style issues in these file(s)

2022-02-19 14:54 UTC, ItsJackson approved these changes

2022-02-19 15:28 UTC, vladfrangu commented
And what exactly is the benefit from this? It feels like overcomplicating for no reason 🤔

2022-02-19 15:29 UTC, ImRodry commented
Quoting from the pr description:
> so that we can have properties like All, which adds all partials into an array, and other methods from the inherited class

2022-02-19 15:33 UTC, almeidx commented
> so that we can have properties like All, which adds all partials into an array

Is `Partials.All` something that is actually wanted though? Perhaps not, for the same reasoning as to why `Intents.ALL` was removed (#6050)

2022-02-19 15:35 UTC, ImRodry commented
> > so that we can have properties like All, which adds all partials into an array
> 
> Is `Partials.All` something that is actually wanted though? Perhaps not, for the same reasoning as to why `Intents.ALL` was removed (#6050)

Intents.All wasn't wanted because people are not supposed to have all intents and they should specify the ones they want individually. The same doesn't apply to Partials, where you can have all partials enabled with no issues

2022-02-19 15:45 UTC, vladfrangu commented
You can have all intents enabled too and you won't have issues, so I don't get why that matters 👀

2022-02-19 15:47 UTC, ImRodry commented
That's not what I meant. You're not supposed to have all intents enabled because you often won't need all of them, but you may need all partials and there's nothing wrong with having them all enabled

2022-02-19 18:05 UTC, xHyroM commented
I'm leaning towards deleting Partials.All. It's useless, you rarely need all partials.

2022-02-19 18:13 UTC, almeidx commented
> and there's nothing wrong with having them all enabled

I disagree. Let's say a new partial is added and your bot is dependent on events/caches of that structure. It now might receive partial structures and you very likely will need to adapt your code if you were accessing data that can be missing (which could not be missing previously).

And besides that, `Partials.All` doesn't actually tell you *what* partials are enabled, and you'd likely need to go to the documentation to find out what partials exist. As opposed to passing all the partials that you need, which is more verbose and doesn't require an external service (e.g. the documentation) to know what is it you're enabling (as is the case for the intents)

2022-02-19 18:18 UTC, ImRodry commented
I assume you’d only enable all partials if you knew what partials there were to begin with. Not only that but new partials are only ever added when new structures are added (for example when scheduled events came out) so you wouldn’t need to adapt your code since you wouldn’t have event listeners for something that just came out

2022-02-20 02:32 UTC, monbrey commented
I feel like this change is a little counter-intuitive and doesn't really deliver any benefit over the base enum/constant.

Partials aren't (or weren't) a calculated Bitfield and I don't see the need for them to be. Is this all just to have `Partials.All` added?

2022-02-20 02:35 UTC, ImRodry commented
Mainly yes but if we want to move away from strings and partials are now treated as numbers and not strings, it would make sense to treat Partials as a Bitfield IMO

2022-02-20 02:44 UTC, vladfrangu commented
So, in a nutshell, this PR...

1. Adds a Partials.All which is not even checked by the rest of the flags (like ADMINISTRATOR is checked for permissions), because adding all the 4 partials we have that you need to an array is..annoying?
2. Changes an enum of Strings -> numbers to a bitfield class with a Flags property (which we moved away from); the enum was consistent with the general move in v14 from strings to numbers as is, and there were no more magic numbers/strings
3. Goes against intents where you're supposed to only use the ones you need

I don't know what the other maintainers think, but to me this sounds like bloat and overcomplicating an already complex concept. Do note that this is *my personal* opinion, and now saying this in the name of the entire team. But I don't see any real benefit from this 😅

2022-02-20 03:12 UTC, ImRodry commented
So let me address each one of those points individually
1. Partials.All being an array of numbers is correct (this also made me realize there was a bug which I just fixed) because when you access an enum property it's returned as a number, so all properties of that enum would be an array of all the numbers. Also you have 6, not 4 partial types, and most of the time you do want all of them to make sure you get all the data from events. This would also not be an issue when a new partial type is added because, as mentioned previously, this only happens when a new structure is added, so you'd need to add event listeners for that anyway
2. The flags property is literally the exact same as the current Flags enum, I just copied the code over so it's the exact same
3. I don't understand the comparison with intents because there is an actual downside to using all intents, whereas the same doesn't apply to partials, as mentioned previously

2022-02-20 12:31 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +export enum PartialsFlags {
Doesn't look like this is exported

2022-02-20 12:34 UTC, ImRodry commented on packages/discord.js/typings/index.d.ts
> +export enum PartialsFlags {
I’ll just not export this then

2022-02-20 13:25 UTC, almeidx requested changes

2022-02-20 13:25 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +  public static All: number[];
```suggestion
  public static All: PartialsFlags[];
```

2022-06-05 07:41 UTC, closed without merging

2022-06-05 09:21 UTC, ImRodry commented
@iCrawl would appreciate an explanation on why this was closed

2022-06-05 09:23 UTC, iCrawl commented
Explanations were given above.