refactor: use `Readonly` types in builders where applicable
discordjs/discord.js pull request #7511
Opened 2022-02-19 19:02 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Changes return types and some parameter types to use readonly inputs/outputs.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-02-19 21:34 UTC, almeidx commented
Would `readonly T[]` syntax be preferred over `ReadonlyArray<T>` given that `T[]` is already being used instead of `Array<T>`?

2022-02-19 21:37 UTC, suneettipirneni commented
> Would `readonly T[]` syntax be preferred over `ReadonlyArray<T>` given that `T[]` is already being used instead of `Array<T>`?

Pretty sure `readonly T[]` isn't a valid syntax.

2022-02-19 21:39 UTC, almeidx commented
> Pretty sure `readonly T[]` isn't a valid syntax.

It is ([handbook](https://www.typescriptlang.org/docs/handbook/2/objects.html#the-readonlyarray-type))

2022-02-19 21:40 UTC, suneettipirneni commented
> > Pretty sure `readonly T[]` isn't a valid syntax.
> 
> It is ([handbook](https://www.typescriptlang.org/docs/handbook/2/objects.html#:~:text=Just%20as%20TypeScript%20provides%20a%20shorthand%20syntax%20for%20Array%3CType%3E%20with%20Type%5B%5D%2C%20it%20also%20provides%20a%20shorthand%20syntax%20for%20ReadonlyArray%3CType%3E%20with%20readonly%20Type%5B%5D.))

Ah ok I'll adjust them then.

2022-02-20 12:33 UTC, iCrawl approved these changes

2022-02-20 15:06 UTC, kyranet requested changes

2022-02-20 15:06 UTC, kyranet commented on packages/builders/src/components/ActionRow.ts
> +	public addComponents(...components: ReadonlyArray<Readonly<T>>) {
```suggestion
	public addComponents(...components: readonly Readonly<T>[]) {
```

2022-02-20 15:06 UTC, kyranet commented on packages/builders/src/messages/embed/Assertions.ts
> +export function validateFieldLength(amountAdding: number, fields?: ReadonlyArray<Readonly<APIEmbedField>>): void {
```suggestion
export function validateFieldLength(amountAdding: number, fields?: readonly Readonly<APIEmbedField>[]): void {
```

2022-02-20 15:06 UTC, kyranet commented on packages/builders/src/messages/embed/UnsafeEmbed.ts
> +	public setTimestamp(timestamp: number | Readonly<Date> | null = Date.now()): this {
We really need [ReadonlyDate](https://github.com/microsoft/TypeScript/issues/29274), heh.

`Readonly<Date>` is a bit useless here, it doesn't have public fields, only methods.

2022-04-18 09:08 UTC, BenPatersonxx commented
@suneettipirneni

2022-04-18 19:30 UTC, closed without merging