types: use discord-api-types `Locale`
discordjs/discord.js pull request #7541
Opened 2022-02-24 07:59 UTC by Syjalo

**Please describe the changes this PR makes and why it should be merged:**

This PR replaces locale types definitions from `string` to `Locale` from discord-api-types.

**Status and versioning classification:**

Please move lines that apply to you out of the comment:
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-02-24 09:20 UTC, SpaceEEC approved these changes

2022-02-24 10:43 UTC, Jiralite requested changes

2022-02-24 10:43 UTC, Jiralite commented on packages/discord.js/typings/index.d.ts
> +  public guildLocale: CacheTypeReducer<Cached, Locale>;
What's the reason for this always being possibly `null`?

2022-02-24 12:19 UTC, vladfrangu requested changes

2022-02-24 12:19 UTC, vladfrangu commented on packages/discord.js/typings/index.d.ts
> +  Locale,
Can you export this in index.js too?

2022-02-24 15:26 UTC, Syjalo commented on packages/discord.js/typings/index.d.ts
> +  Locale,
Done

2022-02-24 15:35 UTC, ImRodry commented on packages/discord.js/src/index.js
> +exports.Locale = require('discord-api-types/v9').Locale;
this isn't re-exported

2022-02-24 15:40 UTC, Syjalo commented on packages/discord.js/src/index.js
> +exports.Locale = require('discord-api-types/v9').Locale;
Thanks

2022-02-24 19:59 UTC, kyranet approved these changes

2022-02-25 15:04 UTC, vladfrangu approved these changes

2022-02-26 10:13 UTC, iCrawl approved these changes

2022-02-26 10:13 UTC, merged