fix: only check `instanceof Component` once
discordjs/discord.js pull request #7546
Opened 2022-02-25 00:19 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Previously a check was done for each component type. This simplifies the logic to one check for a class-based component.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-02-25 08:13 UTC, ImRodry commented on packages/builders/src/components/Components.ts
> +	}
Surely you could make this into 1 line right?

2022-02-25 10:05 UTC, kyranet requested changes

2022-02-25 10:05 UTC, kyranet commented on packages/builders/src/components/Components.ts
> +	}
```suggestion
	if (data instanceof Component) return data;
```

2022-02-25 11:36 UTC, SpaceEEC approved these changes

2022-02-25 12:55 UTC, vladfrangu commented on packages/builders/src/components/Components.ts
> +	}
I don't agree with this change 😂

2022-02-25 12:55 UTC, vladfrangu approved these changes

2022-02-25 13:21 UTC, kyranet approved these changes

2022-02-25 14:19 UTC, ImRodry commented on packages/builders/src/components/Components.ts
> +	}
🤔

2022-02-26 10:14 UTC, iCrawl approved these changes

2022-02-26 10:14 UTC, merged