feat(MessageDeleteBulkAction): add channel parameter to event emitter
discordjs/discord.js pull request #7577
Opened 2022-02-28 06:52 UTC by Syjalo

**Please describe the changes this PR makes and why it should be merged:**

In `messageDeleteBulk` event to get channel that the messages were deleted in you need to do
```js
client.on("messageDeleteBulk", (messages) => {
  messages.first().channel;
});
```
This PR adds new parameter `channel`
```js
client.on("messageDeleteBulk", (messages, channel) => {
  channel;
});
```

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-03-07 18:06 UTC, kyranet commented
This PR needs a rebase, there are merge conflicts.

2022-03-11 12:41 UTC, vladfrangu approved these changes

2022-03-11 13:55 UTC, Jiralite requested changes

2022-03-11 13:55 UTC, Jiralite commented on packages/discord.js/src/client/actions/MessageDeleteBulk.js
> +       * @param {Channel} channel The channel that the messages were deleted in
This can be more accurate.

```suggestion
       * @param {TextBasedChannels} channel The channel that the messages were deleted in
```

2022-03-11 23:01 UTC, iCrawl approved these changes

2022-03-14 20:54 UTC, kyranet approved these changes

2022-04-09 08:46 UTC, SpaceEEC approved these changes

2022-04-09 09:35 UTC, merged