feat: backport handle zombie connection
discordjs/discord.js pull request #7626
Opened 2022-03-09 19:43 UTC by legendhimslef

**Please describe the changes this PR makes and why it should be merged:**
Backports the following pull requests to version 14: #7581 
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-03-09 19:59 UTC, almeidx requested changes

2022-03-09 19:59 UTC, almeidx commented on packages/discord.js/src/util/ShardEvents.js
> +  ZombieConnection: 'zombieConnection',
This was not added to the typings

2022-03-09 21:33 UTC, muchnameless requested changes

2022-03-09 21:33 UTC, muchnameless commented on packages/discord.js/src/client/websocket/WebSocketShard.js
>      this.status = Status.Disconnected;
```suggestion
```
🧹

2022-03-09 22:40 UTC, vladfrangu approved these changes

2022-04-19 14:02 UTC, iCrawl commented
The needs a rebase.

2022-04-19 19:24 UTC, Monix362 commented
![DiscordCanary_CvGumNjs2z](https://user-images.githubusercontent.com/61246713/164079941-61227d9b-08a5-438e-9bd3-461b5c029c4e.png)

Are there any options to fix this connection? I had to disable the GUILD_PRESENCE intention to get my bot to reconnect to the gateway and function normally.

2022-04-19 21:56 UTC, legendhimslef commented
> ![DiscordCanary_CvGumNjs2z](https://user-images.githubusercontent.com/61246713/164079941-61227d9b-08a5-438e-9bd3-461b5c029c4e.png)
> 
> Are there any options to fix this connection? I had to disable the GUILD_PRESENCE intention to get my bot to reconnect to the gateway and function normally.

I fixed it but I guess I messed up fetching upstream. This pr now has 227 files changed ;-;
@Monix362 The issue was, `this.connection.terminate` successfully closed the connection which emitted the onClose event, and thus `this.connection` is now null.

2022-04-20 05:58 UTC, Monix362 commented
It doesn't work. My bot has 34 shards, of which 2 tried to connect to the gateway, and the rest simply hung up and no longer want to connect. Zombie connection is handled, only nothing changes, reconnect=hang=reconnect.

This happens when I have the GUILD_PRESENCE intention enabled, but without it it works as usual.

2022-04-20 07:12 UTC, legendhimslef commented
> happens

can you show me the debug logs and have you implemented all the changes done in this pr in your code? Like all the 3 files as it is.
Also, my bot has around 24 shards. Only one shard appears to get into a zombie connection and it seems to be handled perfectly on my side for weeks now.

2022-04-20 09:17 UTC, Monix362 commented
![Image](https://user-images.githubusercontent.com/61246713/164194956-0720de17-11ec-4250-a49d-924db08d9886.png)

I still get a readyState error.

2022-04-20 09:50 UTC, legendhimslef commented
> ![Image](https://user-images.githubusercontent.com/61246713/164194956-0720de17-11ec-4250-a49d-924db08d9886.png)
> 
> I still get a readyState error.

I have already fixed this issue, Please update your code

2022-04-20 15:11 UTC, Monix362 commented
Still the bot can not connect to the gateway, giving a lot of unavailable guilds and reconnects. 

Even if some shards have successfully connected, but there are 60-70 guilds left out of 1000 available guilds. So the bot will simply take a long time to connect to the gateway, leading to a huge amount of downtime.


Again, this happens when the bot has GUILD_PRESENCE intent... I didn't use it before, but now it is necessary for correct functioning of some bot services.

![idea64_GjhYuBcR6N](https://user-images.githubusercontent.com/61246713/164263418-cd62b881-a3e0-4659-b4dc-007a830c0b33.png)
![ShareX_AMw89NjJsr](https://user-images.githubusercontent.com/61246713/164263430-1a2ceff6-b379-4c92-95a7-adcec36ea878.png)

2022-05-20 09:00 UTC, SpaceEEC approved these changes

2022-05-29 20:02 UTC, kyranet approved these changes

2022-06-05 09:12 UTC, BenPatersonxx commented
@legendhimslef Since your pull request got approved for v13.7, could you finish this PR?

2022-06-06 10:18 UTC, iCrawl approved these changes

2022-06-06 10:21 UTC, merged