fix(GuildEditData): some fields can be null for v13
discordjs/discord.js pull request #7633
Opened 2022-03-10 12:37 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Backports the following pull request to v13:
- #7632

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-03-14 03:52 UTC, Gary50613 requested changes
Code formatting

2022-03-14 03:52 UTC, Gary50613 commented on src/structures/Guild.js
> +    if (typeof data.preferredLocale !== 'undefined') _data.preferred_locale = data.preferredLocale;
```suggestion
    if (typeof data.preferredLocale !== 'undefined') {
      _data.preferred_locale = data.preferredLocale;
    }
```

2022-04-17 12:55 UTC, vladfrangu approved these changes

2022-04-18 11:14 UTC, SpaceEEC approved these changes

2022-04-19 14:01 UTC, iCrawl approved these changes

2022-04-19 14:01 UTC, merged