feat: move `me` and `fetchOwner()` to `GuildMemberManager` manager
discordjs/discord.js pull request #7669
Opened 2022-03-15 04:09 UTC by Syjalo

**Please describe the changes this PR makes and why it should be merged:**
This PR moves `Guild#me` and `Guild#fetchOwner()` to `GuildMemberManager` manager, because that is related to GuildMembers.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-03-15 04:14 UTC, muchnameless requested changes

2022-03-15 04:14 UTC, muchnameless commented on packages/discord.js/src/managers/GuildMemberManager.js
> +    return this.fetch({ ...options, user: this.ownerId });
```suggestion
    return this.fetch({ ...options, user: this.guild.ownerId });
```

2022-03-15 04:33 UTC, imranbarbhuiya commented
Owner is a guild property. It's a member ik but owner of `GuildMemberManager` doesn't makes sense atleast for me.

2022-03-15 05:06 UTC, Syjalo commented
> Owner is a guild property. It's a member ik but owner of `GuildMemberManager` doesn't makes sense atleast for me.

`GuildMemberManager` is members manager of a guild. So we fetch owner of a guild as `GuildMember` from `GuildMemberManager`.

2022-04-03 14:19 UTC, vladfrangu commented
1. This needs a rebase
2. While I can sorta agree with moving `guild.me` to `guild.members.me`, fetchOwner should stay on the guild object imo (shortcut to guild.members.fetchGuildOwner?)

2022-04-03 20:33 UTC, Syjalo commented
While I can sorta agree with moving `guild.me` to `guild.members.me`, fetchOwner should stay on the guild object imo (shortcut to guild.members.fetchGuildOwner?)

Why fetchOwner on GuildMembersManager? fetchOwner returns a GuildMember of a guild. All GuildMebers related thing should be in GuildMembersManager imo.
Why fetchOwner isn't called fetchGuildOwner? Because this placed on **_Guild_** Members Manager.

2022-04-03 20:51 UTC, almeidx requested changes

2022-04-03 20:51 UTC, almeidx commented on packages/discord.js/src/managers/GuildMemberManager.js
> +    if (!this.ownerId) {
```suggestion
    if (!this.guild.ownerId) {
```

2022-04-03 20:51 UTC, almeidx commented on packages/discord.js/src/managers/GuildMemberManager.js
> +    const member = await this.members.fetch({ ...options, user: this.ownerId });
```suggestion
    const member = await this.fetch({ ...options, user: this.guild.ownerId });
```

2022-04-03 20:51 UTC, almeidx commented on packages/discord.js/src/managers/ThreadMemberManager.js
> +      const existing = this.members.cache.get(this.ownerId);
```suggestion
      const existing = this.cache.get(this.thread.ownerId);
```

2022-04-03 20:51 UTC, almeidx commented on packages/discord.js/src/managers/ThreadMemberManager.js
> +    const members = await this.members.fetch(cache);
```suggestion
    const members = await this.fetch(cache);
```

2022-04-03 20:51 UTC, almeidx commented on packages/discord.js/src/managers/ThreadMemberManager.js
> +    return members.get(this.ownerId) ?? null;
```suggestion
    return members.get(this.thread.ownerId) ?? null;
```

2022-04-03 21:03 UTC, almeidx commented
Missed this one: 
https://github.com/Syjalo/discord.js/blob/709ff22efd0733eff4c890bffba5893730991255/packages/discord.js/src/managers/GuildEmojiManager.js#L156

2022-04-03 21:11 UTC, Syjalo commented
> Missed this one: https://github.com/Syjalo/discord.js/blob/709ff22efd0733eff4c890bffba5893730991255/packages/discord.js/src/managers/GuildEmojiManager.js#L156

Thanks

2022-04-16 18:15 UTC, splatterxl commented
`owner_id` is sent by Discord in the guild object so it makes sense that it stays in the top level. Moving `.me` is fine IMO.

2022-04-17 16:29 UTC, Syjalo commented
> `owner_id` is sent by Discord in the guild object so it makes sense that it stays in the top level. Moving `.me` is fine IMO.

It sent in guild object because the API can't sent it in members property for some reason. `GuildMemberManager` is related to specific `Guild`.

2022-04-17 16:35 UTC, splatterxl commented
`GuildMemberManager` is a concept specific to Discord.js. The API sends an array of members in `members`, because that's what it is; a list of members.

The owner's member object is, of course, included in that list. However, `owner_id` isn't information related
to the members. It's related to the _guild_. Also, `owner_id` is still sent without the guild members intent, even when `members` isn't.
________________________________
From: Synbulat Biishev ***@***.***>
Sent: Sunday, April 17, 2022 5:29:41 PM
To: discordjs/discord.js ***@***.***>
Cc: Splatterxl ***@***.***>; Comment ***@***.***>
Subject: Re: [discordjs/discord.js] feat: move `me` and `fetchOwner()` to `GuildMemberManager` manager (PR #7669)


owner_id is sent by Discord in the guild object so it makes sense that it stays in the top level. Moving .me is fine IMO.

It sent in guild object because the API can't sent it in members property for some reason. GuildMemberManager is related to specific Guild.

—
Reply to this email directly, view it on GitHub<https://github.com/discordjs/discord.js/pull/7669#issuecomment-1100911077>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQESWNFCO6UGKEQCZMUMVMTVFQ37LANCNFSM5QXOWSTQ>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-04-17 16:44 UTC, Syjalo commented
Yes. `GuildMemberManager` is a concept specific to discord.js that manages members of a guild. Discord can't sent `guild_id` in `members` property and say us that it is the guild owner, so it sent it in guild object. A guild owner is a member so it should be in something guild members related what is the `GuildMemberManager`.

2022-04-17 17:45 UTC, splatterxl commented
I'll put it quite simply. It's the "guild owner", not the "guild member owner".

2022-04-17 19:59 UTC, Syjalo commented
> 

Yes it is. But all member related things of a guild are in `GuildMemberManager`.

2022-04-18 01:14 UTC, splatterxl commented
I simply don't see how the owner of a guild is in any way related to the members?

2022-04-18 01:50 UTC, monbrey commented
This is getting into a silly back and forth discussion when a maintainer has already made their position clear.

`GuildMemberManager#me` is fine.
`GuildMemberManager#fetchMe()` is probably fine too.

`Guild#owner_id` is where the property is, and `Guild#fetchOwner()` should exist there. You are fetching the owner of the Guild. This makes logical sense.

If you want to have a method on the manager also, it should be called `GuildMemberManager#fetchGuildOwner()`. The method has been abstracted one level away from the guild, and this should be bridged in the nomenclature.

2022-04-18 02:26 UTC, Syjalo commented
> `GuildMemberManager#fetchGuildOwner()`. The method has been abstracted one level away from the guild, and this should be bridged in the nomenclature.

Doesn't `GuildMemberManager` already say that it related to a guild? I think it can still be abstract.

2022-04-18 02:31 UTC, monbrey commented
> > `GuildMemberManager#fetchGuildOwner()`. The method has been abstracted one level away from the guild, and this should be bridged in the nomenclature.
> 
> Doesn't `GuildMemberManager` already say that it related to a guild? I think it can still be abstract.

But why when you can name it something less abstract, more verbose, and easier to understand?

2022-04-18 02:40 UTC, Syjalo commented
Ok, I'll revert it later

2022-04-25 14:17 UTC, vladfrangu approved these changes

2022-05-12 18:40 UTC, SpaceEEC approved these changes
🥫

2022-05-12 20:51 UTC, iCrawl approved these changes

2022-05-12 20:51 UTC, merged