feat(CommandInteraction): add support for localized slash commands
discordjs/discord.js pull request #7684
Opened 2022-03-17 16:51 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Add support for localized names and descriptions in slash command payloads.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-03-17 20:04 UTC, ImRodry commented
Discord API docs PR https://github.com/discord/discord-api-docs/pull/4653

2022-03-18 18:07 UTC, ImRodry requested changes
Missed the edit methods in ApplicationCommand (also please provide some examples in those)

2022-03-21 18:14 UTC, Smidul commented on packages/discord.js/src/managers/ApplicationCommandManager.js
> +      description_localizations: command.descriptionLocalizations,
Shouldn't both also check their variants in `snake_case`?

2022-03-21 18:53 UTC, ImRodry commented on packages/discord.js/src/structures/ApplicationCommand.js
> +   *   'en-US': 'ping',
wouldn't en-US be the one in `name`? This should probably have a different locale

2022-03-26 21:27 UTC, FedorLap2006 requested changes
LGTM. However, docs state that behaviour of `GET` endpoints is changed, therefore they won't return `name_localizations` & `description_localizations` by default, instead they will return `name_localized` & `description_localized`, which are not included in the PR. The way this behaviour could be altered is by supplying `?with_localizations=true`. Not sure what's the best solution here though.

2022-03-26 21:28 UTC, suneettipirneni commented
> LGTM. However, docs state that behaviour of `GET` endpoints is changed, therefore they won't return `name_localizations` & `description_localizations` by default, instead they will return `name_localized` & `description_localized`, which are not included in the PR. The way this behaviour could be altered is by supplying `?with_localizations=true`. Not sure what's the best solution here though.

I can add it as an option in the `ApplicationCommandManager`

2022-03-26 21:31 UTC, FedorLap2006 commented
> > LGTM. However, docs state that behaviour of `GET` endpoints is changed, therefore they won't return `name_localizations` & `description_localizations` by default, instead they will return `name_localized` & `description_localized`, which are not included in the PR. The way this behaviour could be altered is by supplying `?with_localizations=true`. Not sure what's the best solution here though.
> 
> I can add it as an option in the `ApplicationCommandManager`

Problem is, when it's set to false (i.e. endpoint provides `localized` fields) you would need to pass an additional header to alter the language. Which I'm not sure where would be the best to put

2022-03-27 08:20 UTC, xHyroM requested changes

2022-03-27 08:20 UTC, xHyroM commented on packages/discord.js/src/structures/ApplicationCommand.js
> +       * @type {?Object<string, string>}
You can use `LocaleString` from `discord-api-types`

2022-03-27 19:57 UTC, mafineeek approved these changes

2022-04-03 14:34 UTC, vladfrangu approved these changes

2022-04-03 14:34 UTC, vladfrangu commented on packages/discord.js/src/managers/ApplicationCommandManager.js
> +      query: withLocalizations ? new URLSearchParams({ with_localizations: withLocalizations }) : undefined,
Nit
```suggestion
      query: typeof withLocalizations === 'boolean' ? new URLSearchParams({ with_localizations: withLocalizations }) : undefined,
```

2022-04-09 11:01 UTC, SpaceEEC approved these changes

2022-04-10 06:52 UTC, kyranet approved these changes

2022-04-10 06:53 UTC, kyranet commented
There are merge conflicts, please update or rebase your branch.

2022-04-10 16:25 UTC, Jiralite commented on packages/discord.js/src/managers/ApplicationCommandManager.js
> +   * @property {boolean} [withLocalizations] Whether or not to fetch all localization data
```suggestion
   * @property {boolean} [withLocalizations] Whether to fetch all localization data
```

2022-04-12 15:20 UTC, merged