fix(ActionRow): toJSON should include components
discordjs/discord.js pull request #7739
Opened 2022-04-03 22:32 UTC by muchnameless

**Please describe the changes this PR makes and why it should be merged:**
`Component#toJSON` only clones `this.data`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-04-03 22:37 UTC, suneettipirneni requested changes

2022-04-03 22:37 UTC, suneettipirneni commented on packages/discord.js/src/structures/ActionRow.js
> +   * @returns {APIMessageComponent}
```suggestion
   * @returns {APIActionRowComponent}
```

2022-04-05 20:38 UTC, HerrTxbias commented
I think the Typings also need an update here:
https://github.com/discordjs/discord.js/blob/main/packages/discord.js/typings/index.d.ts#L249-L252

```js
export class ActionRow<T extends MessageActionRowComponent | ModalActionRowComponent> {
  private constructor(data: APIActionRowComponent<APIMessageActionRowComponent>);
  public readonly components: T[];
  public toJSON(): APIActionRowComponent;
}
```

2022-04-09 11:20 UTC, SpaceEEC approved these changes

2022-04-10 06:40 UTC, kyranet approved these changes

2022-04-11 21:54 UTC, vladfrangu approved these changes

2022-04-12 15:14 UTC, iCrawl approved these changes

2022-04-12 15:14 UTC, merged