feat(modal): add `awaitModalSubmit`
discordjs/discord.js pull request #7751
Opened 2022-04-05 21:46 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Adds the ability to `await` modal submissions via `MessageComponentInteraction#awaitModalSubmit`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-04-05 21:56 UTC, monbrey commented
Shouldn't this also be on the ApplicationCommand classes?

2022-04-05 22:06 UTC, suneettipirneni commented
> Shouldn't this also be on the ApplicationCommandInteraction classes?

fixed

2022-04-05 22:51 UTC, Mateo-tem requested changes

2022-04-05 22:51 UTC, Mateo-tem commented on packages/discord.js/src/structures/CommandInteraction.js
> +  awaitModal() {}
awaitModal or awaitModalSubmit?

```suggestion
  awaitModalSubmit() {}
```

2022-04-05 23:00 UTC, Mateo-tem approved these changes

2022-04-05 23:00 UTC, Mateo-tem approved these changes

2022-04-07 09:51 UTC, Jiralite commented on packages/discord.js/src/structures/interfaces/InteractionResponses.js
> +   * An object containing the same properties as CollectorOptions, but a few more:
This isn't more, it's [less](https://discord.js.org/#/docs/discord.js/main/typedef/CollectorOptions)!

2022-04-07 16:17 UTC, Jiralite commented on packages/discord.js/src/structures/interfaces/InteractionResponses.js
> +   * An object containing the same properties as CollectorOptions, but a few less:
Might as well link to this for those curious about what `CollectorOptions` is.

```suggestion
   * An object containing the same properties as {@link CollectorOptions}, but a few less:
```

2022-04-09 11:24 UTC, SpaceEEC approved these changes

2022-04-10 06:39 UTC, kyranet approved these changes

2022-04-11 21:53 UTC, vladfrangu approved these changes

2022-04-12 15:13 UTC, iCrawl approved these changes

2022-04-12 15:13 UTC, merged