feat(VoiceChannel): Support `video_quality_mode` (v13)
discordjs/discord.js pull request #7785
Opened 2022-04-13 00:07 UTC by Jiralite

Backports #7722 to version 13.

2022-04-13 11:04 UTC, vladfrangu requested changes

2022-04-13 11:04 UTC, vladfrangu commented on src/structures/VoiceChannel.js
> +      this.videoQualityMode = data.video_quality_mode;
Consistency with v13 this should be converted to a string

2022-04-13 11:17 UTC, vladfrangu approved these changes

2022-04-13 19:21 UTC, SpaceEEC approved these changes

2022-04-14 10:43 UTC, iCrawl approved these changes

2022-04-14 10:43 UTC, merged