feat(builders): improve embed errors
discordjs/discord.js pull request #7795
Opened 2022-04-13 23:20 UTC by monbrey

Improves the error output of some EmbedBuilder methods by using an object validator rather than validating params individually.

This provides much better output for the most common errors seen due to old v13 style code such as `<EmbedBuilder>.setAuthor("Monbrey")`, which will now throw `Expected the value to be an object, but received string instead`.

I didn't see anywhere else this needed doing but feel free to point out any spots and I'll do the same.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-04-14 09:14 UTC, SpaceEEC approved these changes
:+1:

2022-04-14 10:41 UTC, iCrawl approved these changes

2022-04-15 17:58 UTC, Syjalo requested changes

2022-04-15 17:58 UTC, Syjalo commented on packages/builders/src/messages/embed/Assertions.ts
> +	iconURL: urlPredicate,
```suggestion
	iconURL: imageURLPredicate,
```
Fixes #7800

2022-04-15 18:07 UTC, Syjalo requested changes

2022-04-15 18:07 UTC, Syjalo commented on packages/builders/src/messages/embed/Assertions.ts
> +	iconURL: urlPredicate,
```suggestion
	iconURL: imageURLPredicate,
```
Also can be set by attachment

2022-04-17 13:04 UTC, vladfrangu approved these changes

2022-04-19 13:58 UTC, merged