fix(ApplicationCommand): equal nameLocalizations and descriptionLocalizations
discordjs/discord.js pull request #7802
Opened 2022-04-16 14:25 UTC by xHyroM

**Please describe the changes this PR makes and why it should be merged:**
Fix https://github.com/discordjs/discord.js/issues/7801

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-04-16 14:52 UTC, ImRodry approved these changes
Thanks!

2022-04-16 16:31 UTC, kyranet approved these changes

2022-04-19 08:38 UTC, vladfrangu requested changes

2022-04-19 08:38 UTC, vladfrangu commented on packages/discord.js/src/structures/ApplicationCommand.js
> +      !isEqual(command.descriptionLocalizations ?? {}, this.descriptionLocalizations ?? {})
This should also check snake_case variants like the other properties

2022-04-19 08:38 UTC, vladfrangu commented on packages/discord.js/src/structures/ApplicationCommand.js
> +            isEqual(choice.nameLocalizations ?? {}, option.choices[index].nameLocalizations ?? {}),
Ditto

2022-04-20 13:48 UTC, vladfrangu requested changes

2022-04-20 18:01 UTC, vladfrangu approved these changes

2022-04-21 08:55 UTC, iCrawl approved these changes

2022-04-21 17:02 UTC, SpaceEEC approved these changes

2022-04-21 17:06 UTC, merged