feat(builders): add new command permissions v2
discordjs/discord.js pull request #7861
Opened 2022-04-28 16:43 UTC by vladfrangu

**Please describe the changes this PR makes and why it should be merged:**

Adds support for command permissions v2 in builders

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-04-28 16:53 UTC, SuperchupuDev reviewed
Shouldn't it be `setDMPermission` instead of `setDmPermission`? It's used like that pretty much everywhere in discord.js

2022-04-28 18:43 UTC, vladfrangu commented
> Shouldn't it be `setDMPermission` instead of `setDmPermission`? It's used like that pretty much everywhere in discord.js

🤷 . Leaving it for the core maintainers to decide, I think its fine as is

2022-04-28 18:49 UTC, kyranet commented
we should switch to `setDMPermissions`. While I dislike having 3 continuous uppercase letters, it's not unseen in JavaScript (`URLSearchParams` for example).

2022-04-28 18:53 UTC, vladfrangu commented
If the other two maintainers agree, I'll do the change :D

2022-04-30 16:58 UTC, xHyroM requested changes

2022-04-30 16:58 UTC, xHyroM commented on packages/builders/src/interactions/contextMenuCommands/Assertions.ts
> +export function validateDefaultMemberPermission(permissions: unknown) {
```suggestion
export function validateDefaultMemberPermissions(permissions: unknown) {
```

2022-05-01 09:46 UTC, SuperchupuDev commented on packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts
> +	 * You should use `setDefaultMemberPermissions` or `setDmEnabled` instead.
```suggestion
	 * You should use `setDefaultMemberPermissions` or `setDMPermission` instead.
```

2022-05-01 09:46 UTC, SuperchupuDev commented on packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
> +	 * You should use `setDefaultMemberPermissions` or `setDmEnabled` instead.
```suggestion
	 * You should use `setDefaultMemberPermissions` or `setDMPermission` instead.
```

2022-05-01 09:46 UTC, SuperchupuDev commented on packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
> +	 * @deprecated Use `setDefaultMemberPermissions` and `setDMPermission` instead.
```suggestion
	 * @deprecated Use `setDefaultMemberPermissions` or `setDMPermission` instead.
```
consistency with the other `@deprecated` tags

2022-05-01 09:46 UTC, SuperchupuDev commented on packages/builders/src/interactions/contextMenuCommands/Assertions.ts
> +export function validateDmPermission(value: unknown): asserts value is boolean | null | undefined {
Shouldn't this be `validateDMPermission`?

2022-05-12 18:59 UTC, SpaceEEC approved these changes

2022-05-12 20:49 UTC, iCrawl approved these changes

2022-05-12 20:50 UTC, iCrawl commented
This needs a rebase.

2022-05-13 08:50 UTC, pierluigizagaria commented
Please approve this merge!

2022-05-13 09:33 UTC, merged