fix(SlashCommandSubcommandBuilders): add localizations for these too
discordjs/discord.js pull request #7862
Opened 2022-04-28 17:00 UTC by vladfrangu

**Please describe the changes this PR makes and why it should be merged:**

Small bug woopsies

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-04-28 17:06 UTC, kyranet approved these changes

2022-04-28 21:20 UTC, kyranet requested changes

2022-04-28 21:20 UTC, kyranet commented on packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts
> +			validateNameLocalizationsMap(name_localizations);
L31 does `choicesPredicate.parse(choices);`, where `choicesPredicate` includes validation for the `name_localizations` property.

Doing it again is unnecessary.

2022-04-28 21:45 UTC, kyranet approved these changes

2022-05-02 07:38 UTC, iCrawl approved these changes

2022-05-12 08:32 UTC, merged

2023-03-30 11:52 UTC, Technical-13 commented
<https://discord.js.org/#/docs/discord.js/main/typedef/ApplicationCommandOptionChoiceData> suggests that:
```JavaScript
.addChoices(
  { name: 'All logs', nameLocalizations: {
    de: 'Alle Protokolle'
  }, value: 'default' },
  { name: 'Requests to /react', nameLocalizations: {
    de: 'Anfragen zu /Reagieren'
  }, value: 'react' },
  { name: 'Requests to /reply', nameLocalizations: {
    de: 'Bitten um /Antwort'
  }, value: 'reply' },
  { name: 'Requests to /say', nameLocalizations: {
    de: 'Anfragen zu /sagen'
  }, value: 'say' }
)
```

Should work; however, `nameLocalizations` and `name_localizations` (I've tried both) do not seem to work.
To see full code, <https://github.com/Technical-13/ShoeBot/blob/main/deployCommands.js#L116-L165>

![image](https://user-images.githubusercontent.com/4294498/228827220-2dbb9caa-e73f-47f8-921e-42d242cb436d.png)

2023-03-30 12:59 UTC, TetieWasTaken commented
For questions, please head to [the support discord server](https://discord.com/invite/djs) or [github discussions](https://github.com/discordjs/discord.js/discussions)—PRs/Issues are not the right place for asking questions. And you wont get an answer here