chore(deps): update `discord-api-types` and /voice
discordjs/discord.js pull request #7934
Opened 2022-05-16 16:00 UTC by kyranet

**Please describe the changes this PR makes and why it should be merged:**

This PR updates all packages' version of `discord-api-types` to `0.33.0`.

Also removes the `music-bot` example from `/voice`, since it uses the YouTube API.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-05-16 16:20 UTC, ImRodry commented
> Also removes the music-bot example from /voice, since it uses the YouTube API.

Couldn't you replace it with something like Spotify?

2022-05-16 16:24 UTC, amishshah approved these changes

2022-05-16 16:30 UTC, kyranet commented
> Couldn't you replace it with something like Spotify?

My experience with Spotify is that it was impossible to make music bots that consume it. Could be wrong, but it could also be under the same legal issues as consuming YouTube's media, and it's not something we want to get into.

Furthermore, there are other examples which do not use ytdl.

2022-05-16 16:30 UTC, vladfrangu requested changes

2022-05-16 16:31 UTC, kyranet commented on packages/voice/examples/recorder/package.json
> +		"discord-api-types": "^0.30.0",
Depends on discord.js v13.7.0, which uses 0.30.0:

https://github.com/discordjs/discord.js/blob/e3cbd45e7de069432818148b9dedda03f630f9f7/package.json#L58

2022-05-18 15:29 UTC, vladfrangu approved these changes

2022-05-18 17:54 UTC, merged

2022-05-24 18:58 UTC, paulpv commented
@kyranet You also need to remove the entry from the readme.md

Even though it did use the YouTube API, the example was useful and perhaps the code could have been kept and the youtube specific stuff just replaced with a generic "insert your player here" type of comment.

2022-05-24 21:23 UTC, kyranet commented
> You also need to remove the entry from the readme.md

Want to open a PR for it, @paulpv?

> Even though it did use the YouTube API, the example was useful and perhaps the code could have been kept and the youtube specific stuff just replaced with a generic "insert your player here" type of comment.

We have an entire guide in which, [we practically spoonfeed the entire player thing](https://discordjs.guide/voice/audio-player.html#cheat-sheet), there's no need to keep identical code examples in two places.