chore: add external links for dapi-types
discordjs/discord.js pull request #7966
Opened 2022-05-24 22:24 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Adds external links for references to dapi-types in discord.js

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-05-28 09:31 UTC, SpaceEEC approved these changes

2022-05-28 17:55 UTC, kyranet approved these changes

2022-05-29 19:06 UTC, vladfrangu requested changes

2022-05-29 19:06 UTC, vladfrangu commented on packages/discord.js/src/util/APITypes.js
> + * @see {@link https://discord-api-types.dev/api/discord-api-types-v10/enum/ActivityType}
Well this link is wrong

2022-05-29 19:06 UTC, vladfrangu commented on packages/discord.js/src/util/APITypes.js
> + * @see {@link https://discord-api-types.dev/api/discord-api-types-v10/interface/APIGuild}
Also wrong

2022-05-29 19:06 UTC, vladfrangu commented on packages/discord.js/src/util/APITypes.js
> + * @see {@link https://discord-api-types.dev/api/next/discord-api-types-rest/common/enum/RESTJSONErrorCodes}
Shouldn't use `next` version in string
```suggestion
 * @see {@link https://discord-api-types.dev/api/discord-api-types-rest/common/enum/RESTJSONErrorCodes}
```

2022-05-29 23:06 UTC, vladfrangu approved these changes

2022-06-04 07:02 UTC, iCrawl approved these changes

2022-06-04 07:03 UTC, merged