feat: add support for nsfw commands
discordjs/discord.js pull request #7976
Opened 2022-05-28 02:53 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Adds support for nsfw commands, pending official release.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-10-18 18:39 UTC, ParthJadhav approved these changes

2022-11-09 23:54 UTC, Jiralite commented on packages/discord.js/typings/index.d.ts
> +  nsfw?: boolean;
Upstream has the valid types for this as "all". I think this should belong in the base, then?

2022-11-19 20:38 UTC, vladfrangu requested changes

2022-11-19 20:38 UTC, vladfrangu commented on packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
> +	public setNSFW(nsfw = true) {
Iirc we don't do default values in builders

2022-11-19 20:45 UTC, vladfrangu approved these changes

2022-11-19 20:45 UTC, kyranet approved these changes

2022-12-16 02:01 UTC, iCrawl approved these changes

2022-12-16 02:04 UTC, merged