fix: add static method `from` in builders
discordjs/discord.js pull request #7990
Opened 2022-06-02 07:43 UTC by imranbarbhuiya

**Please describe the changes this PR makes and why it should be merged:**
Some builders were missing `from` method. This pr adds them.
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-06-04 20:15 UTC, SpaceEEC requested changes
`SelectMenuOptionBuilder.from` needs to be added to the typings.
The other one was apparently already there.

2022-06-05 08:26 UTC, kyranet approved these changes

2022-06-05 12:18 UTC, vladfrangu approved these changes

2022-06-05 16:33 UTC, iCrawl approved these changes

2022-06-05 16:33 UTC, merged