refactor: clean up modal submissions
discordjs/discord.js pull request #7994
Opened 2022-06-02 19:50 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Originally it made sense to serialize modal submit components as djs message components, however in hindsight this is the wrong approach. The API is just returning the data associated with the component and not the components themselves. Therefore this PR changes the types and serialization to not use message component classes.

**Status and versioning classification:**
Please move lines that apply to you out of the comment:
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-06-02 19:55 UTC, vladfrangu approved these changes

2022-06-02 21:58 UTC, kyranet approved these changes

2022-06-03 13:08 UTC, DraftProducts approved these changes

2022-06-03 23:36 UTC, SpaceEEC requested changes

2022-06-03 23:41 UTC, Jiralite commented on packages/discord.js/src/structures/ModalSubmitFields.js
> +    return his.getField(customId, ComponentType.TextInput).value;
```suggestion
    return this.getField(customId, ComponentType.TextInput).value;
```

2022-06-04 06:56 UTC, iCrawl approved these changes

2022-06-04 06:57 UTC, merged