refactor(ThreadMemberManager): Consistent thread member fetching
discordjs/discord.js pull request #8021
Opened 2022-06-06 11:19 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
`ThreadMemberManager#fetch()` has been made consistent with other managers, such as `MessageManager#fetch()` and `GuildBanManager#fetch()`. This also fixes an issue (by removing it) in which passing only a boolean was ignored and was deemed always `true`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-06-07 14:54 UTC, imranbarbhuiya requested changes
u pushed the conflict

2022-06-07 14:54 UTC, imranbarbhuiya commented on packages/discord.js/typings/index.test-d.ts
> +>>>>>>> main
```suggestion
  if (channel.isThread()) {
    const fetchedMember = await channel.members.fetch('12345678');
    const fetchedMember2 = await channel.members.fetch({ member: '12345678', cache: false, force: true });
```

2022-06-09 08:37 UTC, iCrawl approved these changes

2022-06-09 12:08 UTC, kyranet approved these changes

2022-06-09 17:40 UTC, SpaceEEC approved these changes

2022-06-09 18:52 UTC, merged