feat(guild): add support for setting MFA level
discordjs/discord.js pull request #8024
Opened 2022-06-06 14:04 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

- https://github.com/discord/discord-api-docs/pull/5032

Pending:
- https://github.com/discordjs/discord-api-types/pull/476

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes

2022-06-09 08:36 UTC, iCrawl approved these changes

2022-06-09 12:09 UTC, kyranet requested changes

2022-06-09 12:09 UTC, kyranet commented on packages/discord.js/src/structures/Guild.js
> +  async setMFALevel(level, reason) {
Since we're going forward with #8026, we should consolidate this into a single parameter.

2022-06-09 17:53 UTC, SpaceEEC requested changes

2022-06-09 17:53 UTC, SpaceEEC commented on packages/discord.js/typings/index.d.ts
> +  public setMFALevel(level: GuildMFALevel): Promise<Guild>;
Reason is missing in the typings:
```suggestion
  public setMFALevel(level: GuildMFALevel, reason?: string): Promise<Guild>;
```

2022-06-09 17:53 UTC, SpaceEEC commented on packages/discord.js/src/structures/Guild.js
> +   * @param {string} reason Reason for changing the guild's MFA level
The parameter should be optional:
```suggestion
   * @param {string} [reason] Reason for changing the guild's MFA level
```

2022-06-10 07:25 UTC, didinele requested changes
I know Kyra pointed out otherwise in an earlier review, but regarding #8026, we opted not updating `set*` methods as `setX({ x: value })` seems redundant.

Other than that, LGTM

2022-06-10 07:25 UTC, didinele commented on packages/discord.js/src/structures/Guild.js
> +  async setMFALevel({ level, reason }) {
```suggestion
  async setMFALevel(level, reason) {
```

Also update the JSDoc and remove the `GuildMFALevel` typedef above

2022-06-10 07:25 UTC, didinele commented on packages/discord.js/typings/index.d.ts
> +  public setMFALevel(options: GuildMFALevelOptions): Promise<Guild>;
```suggestion
  public setMFALevel(level: GuildMFALevel, reason?: string): Promise<Guild>;
```

Also get rid of the `GuildMFALevelOptions` interface.

2022-06-10 15:14 UTC, iCrawl approved these changes

2022-06-10 16:30 UTC, vladfrangu approved these changes

2022-06-10 19:23 UTC, SpaceEEC approved these changes

2022-06-10 19:26 UTC, merged