fix: select menu options to accept both rest and array
discordjs/discord.js pull request #8032
Opened 2022-06-07 03:07 UTC by imranbarbhuiya

**Please describe the changes this PR makes and why it should be merged:**
followup of  #7874 
**Status and versioning classification:**

2022-06-09 18:51 UTC, SpaceEEC requested changes
The original PR inlined the normalization where possible or shadowed options where it wasn't.
I think it'd be good to keep it like that:

(I can't merge those suggestions because there is a deleted line there :( )

2022-06-09 18:51 UTC, SpaceEEC commented on packages/discord.js/src/structures/SelectMenuBuilder.js
> +    const _options = normalizeArray(options);
```suggestion
```

2022-06-09 18:51 UTC, SpaceEEC commented on packages/discord.js/src/structures/SelectMenuBuilder.js
> +      _options.map(({ emoji, ...option }) => ({
```suggestion
      normalizeArray(options).map(({ emoji, ...option }) => ({
```

2022-06-09 18:51 UTC, SpaceEEC commented on packages/discord.js/src/structures/SelectMenuBuilder.js
> +    const _options = normalizeArray(options);
```suggestion
```

2022-06-10 18:59 UTC, kyranet approved these changes

2022-06-10 19:14 UTC, SpaceEEC approved these changes

2022-06-10 19:21 UTC, iCrawl approved these changes

2022-06-10 19:22 UTC, merged