chore: cancel previous run in workflow
discordjs/discord.js pull request #8075
Opened 2022-06-12 04:36 UTC by imranbarbhuiya

**Please describe the changes this PR makes and why it should be merged:**
Cancel previously running tests when a new commit gets added.
**Status and versioning classification:**

2022-06-12 11:12 UTC, ImRodry commented
You can just use this https://docs.github.com/en/actions/using-jobs/using-concurrency

2022-07-04 01:31 UTC, ArjunSharda requested changes
I've added two suggestions, as the current version you are proposing for is outdated.

2022-07-04 01:31 UTC, ArjunSharda commented on .github/workflows/test.yml
> +        uses: styfle/cancel-workflow-action@0.9.1
```suggestion
        uses: styfle/cancel-workflow-action@0.10.0
```

2022-07-04 01:31 UTC, ArjunSharda commented on .github/workflows/documentation.yml
> +        uses: styfle/cancel-workflow-action@0.9.1
```suggestion
        uses: styfle/cancel-workflow-action@0.10
```

2022-07-20 21:07 UTC, iCrawl commented
I'll close this for now, this might conflict tags and branch docs. And I think we don't have a huge issue with too many CIs running.

2022-07-20 21:07 UTC, closed without merging