revert: refactor: move eslint.tsconfig.json to root
discordjs/discord.js pull request #8159
Opened 2022-06-22 21:03 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

.eslintrc.json is smart and loads from the local config based on the project parameter at root, tsconfig.eslint.json is not so smart, so it was ignoring the tsconfig from any given package

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-06-22 21:44 UTC, kyranet requested changes

2022-06-22 21:44 UTC, kyranet commented on packages/actions/tsconfig.eslint.json
> +	},
I don't think we should need this option for TypeScript-only packages, only `discord.js` would use this.

2022-06-22 21:52 UTC, imranbarbhuiya commented
You can make a js file just like `tsup.config.ts` and use that instead of copying full config file.

2022-06-23 10:36 UTC, iCrawl approved these changes

2022-06-23 10:36 UTC, merged