feat(applicationCommand): add max min length in string option
discordjs/discord.js pull request #8215
Opened 2022-07-02 04:33 UTC by imranbarbhuiya

**Please describe the changes this PR makes and why it should be merged:**
this pr adds min-max length support for string option
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-07-02 10:57 UTC, vladfrangu approved these changes

2022-07-02 12:29 UTC, SpaceEEC approved these changes

2022-07-02 15:00 UTC, MidSpike approved these changes

2022-07-02 17:09 UTC, Mateo-tem requested changes
https://github.com/discordjs/discord.js/blob/c604804ba0933b6b822fdd93cf2995b4eabeff8c/packages/discord.js/src/structures/ApplicationCommand.js#L492-L514

Here you can document the properties (`minLength` and `maxLength`).

2022-07-02 17:11 UTC, almeidx requested changes

2022-07-02 17:11 UTC, almeidx commented on packages/discord.js/typings/index.d.ts
> +  type: Exclude<ApplicationCommandOptionType.String, ApplicationCommandOptionType>;
```suggestion
  type: ApplicationCommandOptionType.String;
```

2022-07-03 13:34 UTC, iCrawl approved these changes

2022-07-03 13:34 UTC, merged