chore: ignore index files in coverage
discordjs/discord.js pull request #8293
Opened 2022-07-15 15:07 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Ignores all the `index.ts` files, as they only contain exports from other files

Because of that, I moved the Collection source into a separate file and exported it in `index.ts`. We could also make the main entry point the new file(?) instead of re-exporting in an index file, however, I don't think it matters given that `tsup` bundles everything into a single file anyway

cc: @ckohen 

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-07-16 07:16 UTC, ckohen requested changes

2022-07-16 07:16 UTC, ckohen commented on vitest.config.ts
> +				'**/index.ts',
```suggestion
				// All index files that *should* only contain exports from other files
				'**/index.{js,ts}',
```

2022-07-17 11:34 UTC, vladfrangu approved these changes

2022-07-17 16:50 UTC, iCrawl approved these changes

2022-07-17 16:51 UTC, merged