refactor(embed): deprecate addField
discordjs/discord.js pull request #8318
Opened 2022-07-18 21:32 UTC by nyapat

**Please describe the changes this PR makes and why it should be merged:**
should have been done before 14 released 

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- Code changes have been tested against the Discord API, or there are no code changes

2022-07-18 21:37 UTC, Jiralite commented on src/structures/MessageEmbed.js
> +   * @deprecated This method is a wrapper for {@link MessageEmbed.addFields}, use that instead.
The `.` references static methods.

```suggestion
   * @deprecated This method is a wrapper for {@link MessageEmbed#addFields}. Use that instead.
```

2022-07-20 22:49 UTC, ArjunSharda requested changes

2022-07-20 22:49 UTC, ArjunSharda commented on src/structures/MessageEmbed.js
> +        'MessageEmbed#addField is deprecated and removed in the next major. Use MessageEmbed#addFields instead.',
```suggestion
        'MessageEmbed#addField is deprecated and will be removed in the next major update. Use MessageEmbed#addFields instead.',
```

2022-07-20 22:49 UTC, ArjunSharda commented on typings/index.d.ts
> +  /** @deprecated This method is a wrapper for {@link MessageEmbed.addFields}, use that instead. */
```suggestion
  /** @deprecated This method is a wrapper for {@link MessageEmbed.addFields}. Use that instead. */
```

2022-07-21 19:38 UTC, almeidx requested changes

2022-07-21 19:38 UTC, almeidx commented on typings/index.d.ts
> +  /** @deprecated This method is a wrapper for {@link MessageEmbed#addFields}. Use that instead. */
```suggestion
  /** @deprecated This method is a wrapper for {@link MessageEmbed#addFields}. Use that instead. */
  public addField(name: string, value: string, inline?: boolean): this;
```

2022-07-22 14:37 UTC, ArjunSharda approved these changes

2022-07-22 18:00 UTC, kyranet approved these changes

2022-07-23 16:22 UTC, iCrawl approved these changes

2022-07-23 16:25 UTC, SpaceEEC approved these changes

2022-07-23 21:39 UTC, merged