fix(selectMenu): allow json to be used for select menu options
discordjs/discord.js pull request #8322
Opened 2022-07-19 20:18 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Fixes an issue where select menu builders would say json options were invalid despite allowing json types.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-07-19 20:27 UTC, suneettipirneni commented
CI failing for reasons outside of this PR

2022-07-21 06:48 UTC, vladfrangu requested changes

2022-07-21 06:48 UTC, vladfrangu commented on packages/builders/__tests__/components/selectMenu.test.ts
> +			expect(() => selectMenu().addOptions(selectMenuOption().setLabel('test').setValue('test')));
I expect it. but expect what

2022-07-23 21:50 UTC, SpaceEEC approved these changes

2022-07-23 21:52 UTC, favna approved these changes

2022-07-23 22:02 UTC, iCrawl approved these changes

2022-07-24 13:14 UTC, merged