feat: Add channel & message URL formatters
discordjs/discord.js pull request #8371
Opened 2022-07-26 17:57 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Adds `channelLink()` and `messageLink()` which formats a link to a channel or message respectively.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-07-26 18:02 UTC, imranbarbhuiya requested changes

2022-07-26 18:02 UTC, imranbarbhuiya commented on packages/builders/src/messages/formatters.ts
> +export function messageLink<C extends Snowflake, M extends Snowflake, G extends Snowflake>(
U can use these formatters in https://github.com/discordjs/discord.js/blob/798466a696babd0857454c1dac921605cf5894b2/packages/discord.js/src/structures/BaseChannel.js#L57

2022-07-26 18:04 UTC, almeidx reviewed
These should be re-exported in discord.js and used in the Message#url and Channel#url getters

2022-07-26 18:16 UTC, Jiralite commented
> These should be re-exported in discord.js and used in the Message#url and Channel#url getters

This should be done with c19f6d9a9b046dc7c6e8f17983f07f4cfa6da8e3.

2022-07-26 18:20 UTC, Syjalo commented
Maybe you will add also for users?
`https://discord.com/users/:id`

2022-07-27 10:08 UTC, iCrawl approved these changes

2022-07-28 18:11 UTC, kyranet approved these changes

2022-07-28 19:29 UTC, SpaceEEC approved these changes

2022-07-29 08:47 UTC, merged