fix(MessageMentions): infinite loop in `parsedUsers` getter
discordjs/discord.js pull request #8430
Opened 2022-08-04 08:46 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Fixes #8426 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-08-04 15:15 UTC, iCrawl approved these changes

2022-08-04 19:29 UTC, SpaceEEC requested changes

2022-08-04 19:29 UTC, SpaceEEC commented on packages/discord.js/typings/index.d.ts
> +  private static GlobalUsersPattern: RegExp;
Mind moving this (and the `GlobalChannelsPattern`) above the `ChannelsPattern`?

2022-08-07 11:47 UTC, vladfrangu approved these changes

2022-08-08 09:06 UTC, iCrawl approved these changes

2022-08-08 09:10 UTC, merged