feat(WebSocketShard): support new resume url
discordjs/discord.js pull request #8480
Opened 2022-08-12 13:07 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
See https://github.com/discord/discord-api-docs/pull/5282

Also bumps `discord-api-types` across the repo since.. I needed it.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-08-12 14:04 UTC, Syjalo requested changes

2022-08-12 14:04 UTC, Syjalo commented on packages/ws/src/ws/WebSocketManager.ts
> +	resumeUrl: string;
For consistency with the rest of the lib
```suggestion
	resumeURL: string;
```

2022-08-12 15:50 UTC, kyranet approved these changes

2022-08-12 18:51 UTC, SpaceEEC approved these changes

2022-08-14 10:01 UTC, iCrawl approved these changes

2022-08-14 10:01 UTC, merged