fix(WebSocketManager#connect): check if we have enough sessions
discordjs/discord.js pull request #8481
Opened 2022-08-12 13:18 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-08-12 13:23 UTC, vladfrangu requested changes

2022-08-12 13:23 UTC, vladfrangu commented on packages/ws/src/ws/WebSocketManager.ts
> +				} remaining; resets in ${Date.now() + data.session_start_limit.reset_after}ms`,
Thats not true, you probably wanted reset_after - Date.now() for one, and ms is really not useful... Maybe just toISOString() it

2022-08-15 13:57 UTC, vladfrangu approved these changes

2022-08-16 15:07 UTC, SpaceEEC approved these changes

2022-08-16 15:22 UTC, iCrawl approved these changes

2022-08-16 15:28 UTC, merged