feat: deprecate `ActionRow.from()`
discordjs/discord.js pull request #8504
Opened 2022-08-16 18:34 UTC by Syjalo

**Please describe the changes this PR makes and why it should be merged:**
This PR adds a depreciation warning for `ActionRow.from()`

**Status and versioning classification:**\
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-08-16 18:55 UTC, Jiralite requested changes
Simply adding this after the class will do the trick:

```JavaScript
ActionRow.from = deprecate(
  ActionRow.from,
  'ActionRow.from() is deprecated. Use ActionRowBuilder.from() instead.',
);
```

Note the change of the deprecation message to be consistent with the `Formatters` class.

2022-08-16 18:55 UTC, Jiralite commented on packages/discord.js/src/structures/ActionRow.js
> +   * @deprecated Use {@link ActionRowBuilder.from()} instead
```suggestion
   * @deprecated Use {@link ActionRowBuilder.from()} instead.
```

2022-08-17 19:53 UTC, iCrawl approved these changes

2022-08-18 07:01 UTC, kyranet approved these changes

2022-08-18 07:06 UTC, merged