types(webhook): avatar can be null
discordjs/discord.js pull request #8541
Opened 2022-08-22 09:46 UTC by DTrombett

**Please describe the changes this PR makes and why it should be merged:**

`Webhook#avatar` can be null if the webhook hasn't any avatar. The documentation is correct, and `Webhook#avatarURL()` handles it correctly, but types were missing the `null` type.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-08-22 09:50 UTC, SpaceEEC approved these changes

2022-08-22 10:14 UTC, iCrawl approved these changes

2022-08-22 12:16 UTC, Syjalo requested changes

2022-08-22 12:16 UTC, Syjalo commented on packages/discord.js/typings/index.d.ts
> +  public avatar: string | null;
Shouldn't it be set to `null` in the code then?

2022-08-30 17:46 UTC, vladfrangu approved these changes

2022-09-02 15:30 UTC, merged