types(GuildChannelManager): correct `fetch` return type
discordjs/discord.js pull request #8549
Opened 2022-08-23 19:41 UTC by RedGuy12

**Please describe the changes this PR makes and why it should be merged:**

The documentation for `/channels/channelId` says:
> Get a channel by ID. Returns a [channel](https://discord.com/developers/docs/resources/channel#channel-object) object. If the channel is a thread, a [thread member](https://discord.com/developers/docs/resources/channel#thread-member-object) object is included in the returned result.

This causes me to believe that this route, and `GuildChannelManager#fetch`, can fetch threads. I tested it and it works.

Note that the bulk fetch type doesn't need to be updated, as the documentation for that specifically mentions the exclusion of threads:
> Returns a list of guild [channel](https://discord.com/developers/docs/resources/channel#channel-object) objects. Does not include threads.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-08-23 19:47 UTC, Jiralite requested changes
The documentation needs to be updated too:

https://github.com/discordjs/discord.js/blob/249ba0a9a6a19e9685869f87bf935f3a0f6d55e3/packages/discord.js/src/managers/GuildChannelManager.js#L316-L332

[`GuildChannel`](https://discord.js.org/#/docs/discord.js/main/class/GuildChannel) doesn't include thread channels.

2022-08-23 20:20 UTC, RedGuy12 commented
> The documentation needs to be updated too:
> 
> [`GuildChannel`](https://discord.js.org/#/docs/discord.js/main/class/GuildChannel) doesn't include thread channels.

Done.

2022-08-23 21:53 UTC, almeidx requested changes

2022-08-23 21:53 UTC, almeidx commented on packages/discord.js/src/managers/GuildChannelManager.js
> +   * @returns {Promise<?(GuildChannel|ThreadChannel)|Collection<Snowflake, GuildChannel>>}
```suggestion
   * @returns {Promise<?(GuildChannel|ThreadChannel|Collection<Snowflake, GuildChannel>)>}
```

2022-08-25 13:12 UTC, Jiralite reviewed
Fetching multiple channels actually calls `ChannelManager#_add()` so it appears even channels in the collection may be `null`.

2022-08-25 13:12 UTC, Jiralite commented on packages/discord.js/src/managers/GuildChannelManager.js
> +   * @returns {Promise<?(GuildChannel|ThreadChannel|Collection<Snowflake, GuildChannel>)>}
```suggestion
   * @returns {Promise<?GuildChannel|ThreadChannel|Collection<Snowflake, ?GuildChannel>>}
```

2022-08-25 13:12 UTC, Jiralite commented on packages/discord.js/typings/index.d.ts
>    public fetch(id?: undefined, options?: BaseFetchOptions): Promise<Collection<Snowflake, NonThreadGuildBasedChannel>>;
```suggestion
  public fetch(id?: undefined, options?: BaseFetchOptions): Promise<Collection<Snowflake, NonThreadGuildBasedChannel | null>>;
```

2022-09-11 18:10 UTC, kyranet approved these changes

2022-09-11 18:13 UTC, vladfrangu approved these changes

2022-09-11 18:19 UTC, SpaceEEC approved these changes

2022-09-11 18:29 UTC, merged