add MESSAGE_CONTENT intent (v13)
discordjs/discord.js pull request #8580
Opened 2022-09-01 08:44 UTC by JsCoder2022

**Please describe the changes this PR makes and why it should be merged:**
https://discord.com/channels/222078108977594368/992166350640386090/1014655744597033040

**Status and versioning classification:**

2022-09-01 08:46 UTC, kyranet approved these changes

2022-09-01 09:00 UTC, lolollllo approved these changes

2022-09-01 12:08 UTC, Jiralite requested changes
This is missing typings.

2022-09-02 09:10 UTC, Jiralite approved these changes

2022-09-02 15:22 UTC, merged