feat(Message): add `position` for message
discordjs/discord.js pull request #8594
Opened 2022-09-04 17:26 UTC by dager-mohamed

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

2022-09-04 17:52 UTC, almeidx requested changes

2022-09-04 17:52 UTC, almeidx commented on packages/discord.js/src/structures/Message.js
> +    if (data.position) {
```suggestion

    if (typeof data.position !== 'undefined') {
```

2022-09-04 18:52 UTC, almeidx requested changes

2022-09-04 18:52 UTC, almeidx commented on packages/discord.js/src/structures/Message.js
> +    if (typeof data.position !== 'undefined') {
Actually, should be like this to be consistent with the rest of the properties
```suggestion
    if ('positon' in data) {
```

2022-09-11 18:21 UTC, vladfrangu approved these changes

2022-09-17 14:26 UTC, closed without merging