feat(ForumChannel): add `defaultSortOrder`
discordjs/discord.js pull request #8633
Opened 2022-09-18 14:40 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Needs an enum for the sort order modes in discord-api-types

- discord/discord-api-docs#5475

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-09-20 20:07 UTC, almeidx commented
Closing this since
- https://github.com/discord/discord-api-docs/pull/5480

Will reopen/remake when/if they document it again

2022-09-25 18:35 UTC, vladfrangu requested changes

2022-09-25 18:35 UTC, vladfrangu commented on packages/discord.js/src/structures/ForumChannel.js
> +   * @param {SortOrderMode} defaultSortOrder The default sort order mode to set on this channel
This should allow `null` too

2022-10-01 13:56 UTC, SpaceEEC approved these changes

2022-10-01 13:56 UTC, kyranet approved these changes

2022-10-01 14:00 UTC, merged