chore(proxy-container): update README for proper request forwarding
discordjs/discord.js pull request #8692
Opened 2022-09-30 20:17 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
Internal discussion thread: https://canary.discord.com/channels/222078108977594368/1020044900282138744/1020044900282138744

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updatin

2022-09-30 20:17 UTC, SpaceEEC approved these changes

2022-09-30 20:24 UTC, imranbarbhuiya requested changes

2022-09-30 20:24 UTC, imranbarbhuiya commented on packages/proxy-container/README.md
>  const client = new Client({
You can now remove the `ProxyAgent` imprted above

2022-09-30 22:24 UTC, kyranet approved these changes

2022-10-01 13:31 UTC, vladfrangu approved these changes

2022-10-01 13:40 UTC, merged