feat(scripts): Add script to create `@discordjs` package
discordjs/discord.js pull request #8711
Opened 2022-10-06 15:15 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Streamlines the process of creating new packages under the `@discordjs` org.

To use simply run `yarn createPackage <package-name>` in the root directory.

2022-10-06 15:20 UTC, imranbarbhuiya commented on packages/scripts/src/template/template.package.json
> +		"zlib-sync": "^0.1.7"
```suggestion
		"@discordjs/docgen": "workspace:^",
		"@favware/cliff-jumper": "^1.8.7",
		"@microsoft/api-extractor": "^7.31.2",
		"@types/node": "^16.11.60",
		"@vitest/coverage-c8": "^0.23.4",
		"cross-env": "^7.0.3",
		"downlevel-dts": "^0.10.1",
		"eslint": "^8.24.0",
		"eslint-config-neon": "^0.1.33",
		"prettier": "^2.7.1",
		"tsup": "^6.2.3",
		"typescript": "^4.8.3",
		"undici": "^5.10.0",
		"vitest": "^0.23.4"
```

2022-10-06 15:36 UTC, iCrawl commented on packages/scripts/package.json
> +		"toml": "^3.0.0",
2 toml packages?

2022-10-06 15:50 UTC, iCrawl requested changes
Missed a few things

2022-10-06 15:50 UTC, iCrawl commented on packages/scripts/src/template/template.package.json
> +		"format": "prettier --write . && cross-env TIMING=1 eslint src __tests__ --ext mjs,js,ts --fix",
Have to re-add the `cross-env` package as a dev-dep for this to work.

2022-10-06 19:55 UTC, SpaceEEC approved these changes
This formats `.github/labeler.yml` and `.github/labels.yml` (removes unneeded quotes), which is probably fine.

So LGTM

2022-10-06 20:00 UTC, iCrawl commented on packages/scripts/src/template/template.package.json
> +	"description": "",
This is not actually filling in any values 👀

2022-10-06 22:40 UTC, iCrawl requested changes
Last batch before merge.

2022-10-06 22:40 UTC, iCrawl commented on package.json
> +		"createPackage": "node packages/scripts/src/packageScript.mjs"
```suggestion
		"create-package": "node packages/scripts/src/packageScript.mjs"
```

2022-10-06 22:40 UTC, iCrawl commented on packages/scripts/src/template/template.package.json
> +		"docs": "downlevel-dts dist docs/dist --to=3.7 && docgen -i src/index.ts -c docs/index.json -o docs/docs.json --typescript && api-extractor run --local",
```suggestion
		"docs": "downlevel-dts dist docs/dist --to=3.7 && api-extractor run --local",
```

2022-10-06 22:40 UTC, iCrawl commented on packages/scripts/src/template/template.package.json
> +		"@discordjs/docgen": "workspace:^",
```suggestion
```

2022-10-06 22:40 UTC, iCrawl commented on packages/scripts/src/template/template.package.json
> +		"cross-env": "^7.0.3"
This should be sorted correctly.

2022-10-07 00:38 UTC, iCrawl approved these changes

2022-10-07 00:38 UTC, merged