refactor(Embed): use `embedLength` function from builders
discordjs/discord.js pull request #8735
Opened 2022-10-11 14:45 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Uses the [`embedLength()`](https://discordjs.dev/docs/packages/builders/main/embedLength:Function) function from /builders in `Embed#length` to reduce code duplication

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-10-11 14:47 UTC, kyranet approved these changes

2022-10-11 14:49 UTC, imranbarbhuiya requested changes

2022-10-11 14:49 UTC, imranbarbhuiya commented on packages/discord.js/src/structures/Embed.js
> +    return embedLength(this.data);
imo this alias should be removed and `embedLength` should be used by the user. So this method should be deprecated. 
Also `length` prop in builder does make sense to check length before adding more fields but not not in received data

2022-10-12 09:39 UTC, iCrawl approved these changes

2022-10-12 09:39 UTC, merged