fix issue with ratelimits not working correctly
discordjs/discord.js pull request #8779
Opened 2022-10-22 19:43 UTC by hackermondev

related to #8757

The ``ref`` option doesn't require the Node.js event loop to remain active when waiting for the timeout causing the program to end if there isn't an active gateway connection.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-10-22 23:30 UTC, Jiralite requested changes

2022-10-22 23:30 UTC, Jiralite commented on packages/rest/src/lib/handlers/SequentialHandler.ts
> +		await sleep(time, undefined);
```suggestion
		await sleep(time);
```

2022-10-22 23:30 UTC, Jiralite commented on packages/rest/src/lib/handlers/SequentialHandler.ts
> +				await sleep(sublimitTimeout, undefined);
```suggestion
				await sleep(sublimitTimeout);
```

2022-10-23 05:46 UTC, didinele approved these changes

2022-10-23 07:47 UTC, vladfrangu approved these changes

2022-10-23 09:05 UTC, ckohen approved these changes
Adding context:
These were initially added so that a client that was .destroy()ed would not continue waiting for requests.

I think the chances of hitting a rate limit near the time of calling such method are actually quite low AND in the cases where destroy is called at all (cause lets be honest most people just kill the process) there will likely be additional cleanup happening anyways that takes some time.

Given that, I am okay removing these unrefs.

Worth considering whether this is really patch or major, because hitting cloudflare ratelimits on startup will have vastly different behavior now and this was an intentional design decision originally.

2022-10-23 09:09 UTC, didinele commented
> Worth considering whether this is really patch or major, because hitting cloudflare ratelimits on startup will have vastly different behavior now and this was an intentional design decision originally.

Considering its only now intended behavior, this should def. be a patch IMO. For most people the behavior won't even change - i.e. if they also have a postgres/redis/whatever connection open, which is probably why we didn't find this issue earlier.

2022-10-23 10:05 UTC, kyranet approved these changes

2022-10-23 10:44 UTC, SpaceEEC approved these changes

2022-10-23 10:45 UTC, merged