feat: support resume urls
discordjs/discord.js pull request #8784
Opened 2022-10-25 10:59 UTC by Deivu

**Please describe the changes this PR makes and why it should be merged:**
Resume urls was not added in v14 despite on changelogs saying it is, was only added only on `@discordjs/ws`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-10-25 13:20 UTC, almeidx requested changes

2022-10-27 08:36 UTC, didinele approved these changes

2022-10-27 08:40 UTC, didinele requested changes
Actually, in hindsight, you aren't supposed to use the resume URL in case of a full reconnect. You should be clearing it in `destroy` if `reset` is true.

2022-10-27 08:42 UTC, Syjalo requested changes

2022-10-27 08:42 UTC, Syjalo commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +    this.resumeUrl = null;
```suggestion
    this.resumeURL = null;
```

2022-10-27 08:42 UTC, Syjalo commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +    const gateway = this.resumeUrl ?? this.manager.gateway;
```suggestion
    const gateway = this.resumeURL ?? this.manager.gateway;
```

2022-10-27 08:42 UTC, Syjalo commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +        this.resumeUrl = packet.d.resume_gateway_url;
```suggestion
        this.resumeURL = packet.d.resume_gateway_url;
```

2022-10-27 08:42 UTC, Syjalo commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +        this.debug(`[READY] Session ${this.sessionId} | Resume url ${this.resumeUrl}.`);
```suggestion
        this.debug(`[READY] Session ${this.sessionId} | Resume url ${this.resumeURL}.`);
```

2022-10-27 08:42 UTC, Syjalo commented on packages/discord.js/typings/index.d.ts
> +  private resumeUrl: string | null;
```suggestion
  private resumeURL: string | null;
```

2022-10-27 08:45 UTC, Deivu commented
Discord.JS uses pascal case so why we need url to be all capital?

2022-10-27 08:49 UTC, didinele commented
> Discord.JS uses pascal case so why we need url to be all capital?

We always uppercase abbreviations, e.g. `REST`, or https://discord.js.org/#/docs/discord.js/main/typedef/WebhookClientDataURL - you can find plenty of examples of this.

2022-10-27 08:54 UTC, Deivu commented
Ok, then applied the changes you requested

2022-10-27 08:56 UTC, didinele approved these changes

2022-10-27 10:24 UTC, SpaceEEC approved these changes

2022-10-27 10:25 UTC, kyranet approved these changes

2022-10-27 12:13 UTC, Jiralite commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +     * The resume url for this shard
```suggestion
     * The resume URL for this shard
```

2022-10-27 12:13 UTC, Jiralite commented on packages/discord.js/src/client/websocket/WebSocketShard.js
> +    // Step 5: Reset the sequence, resume url and session id if requested
```suggestion
    // Step 5: Reset the sequence, resume URL and session id if requested
```

2022-10-31 18:03 UTC, iCrawl approved these changes

2022-10-31 18:03 UTC, merged