fix: backport allow deletion of ephemeral messages to v13
discordjs/discord.js pull request #8811
Opened 2022-11-04 10:11 UTC by Raraph84

**Please describe the changes this PR makes and why it should be merged:**
Backport allow deletion of ephemeral messages to v13 from [this commit](https://github.com/discordjs/discord.js/commit/fc107744618857bf28c2167f204253baf690ede8)
It's my first pull request to discord.js so I don't know if I did it right

**Status and versioning classification:**
> None

2022-11-04 11:33 UTC, MrMythicalYT requested changes
The error properties, like in #8774, should be deprecated.

2022-11-04 12:57 UTC, Raraph84 commented
> The error properties, like in #8774, should be deprecated.

In the precedents commits of the file Messages.js, the properties was removed, so I've just removed the concerned property

2022-11-04 13:21 UTC, MrMythicalYT commented on src/errors/Messages.js
> -  INTERACTION_EPHEMERAL_REPLIED: 'Ephemeral responses cannot be deleted.',
It should not be removed, it should be deprecated. Removing it would be a breaking change

2022-11-07 22:26 UTC, MrMythicalYT approved these changes

2022-11-19 20:19 UTC, kyranet approved these changes

2022-11-19 20:51 UTC, vladfrangu approved these changes

2022-11-25 17:24 UTC, iCrawl approved these changes

2022-11-25 17:35 UTC, merged