chore: use generator for range utility
discordjs/discord.js pull request #8825
Opened 2022-11-08 20:34 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

Aside from using a generator, this changes the range function in the following ways:

- `range` is no longer end-inclusive. This is because we mainly work with 0-based indexing which ends at length - 1.
- The function accepts an object or a just a number. The object contains the parameters for start, end, and step. The sole number parameter indicates the range 0...(n-1).

This is *techinically* a breaking change, but also not really because `range` is more for internal uses rather than it being a member of the public API.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-11-08 20:49 UTC, almeidx commented on packages/util/src/functions/range.ts
> + * range(5); // [0, 1, 2, 3, 4]
Isn't this comment inaccurate? Perhaps the example should be tweaked?

2022-11-09 09:22 UTC, almeidx commented on packages/util/src/functions/range.ts
> + * Yields the numbers in the given range as an array.
Like in my previous review, this does not return an array

2022-11-19 20:55 UTC, vladfrangu requested changes

2022-11-19 20:55 UTC, vladfrangu commented on packages/util/__tests__/range.test.ts
> +	test('GIVEN valid range and then valid numbers are returned', () => {
```suggestion
	test('GIVEN valid range THEN valid numbers are returned', () => {
```

2022-11-25 17:21 UTC, iCrawl approved these changes

2022-12-02 12:57 UTC, vladfrangu approved these changes

2022-12-25 20:38 UTC, SpaceEEC approved these changes

2022-12-25 20:43 UTC, merged