feat (InteractionResponses) v13: add message parameter
discordjs/discord.js pull request #8838
Opened 2022-11-15 17:02 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
Backboards #8773

2022-11-16 17:15 UTC, MrMythicalYT commented on src/structures/interfaces/InteractionResponses.js
>     * // Delete the reply to this interaction
```suggestion
   * // Delete the initial reply to this interaction
```

2022-11-16 17:30 UTC, jaw0r3k commented on src/structures/interfaces/InteractionResponses.js
>     * // Fetch the reply to this interaction
isnt purpose of pr to fetch any reply?

2022-11-16 17:31 UTC, jaw0r3k commented on src/structures/interfaces/InteractionResponses.js
>     * Edits the initial reply to this interaction.
why?

2022-11-16 17:38 UTC, MrMythicalYT commented on src/structures/interfaces/InteractionResponses.js
>     * Edits the initial reply to this interaction.
The "Edits the initial reply to this interaction.". Not sure why it's there

2022-11-16 17:39 UTC, jaw0r3k commented on src/structures/interfaces/InteractionResponses.js
>     * // Fetch the reply to this interaction
So if I add some id, it will be good?

2022-11-16 17:42 UTC, MrMythicalYT commented on src/structures/interfaces/InteractionResponses.js
>     * // Fetch the reply to this interaction
The example should be quick and easy, adding the ID isn't needed. You should just show that this fetches the initial reply

2022-11-16 18:30 UTC, jaw0r3k commented on src/structures/interfaces/InteractionResponses.js
>     * Edits the initial reply to this interaction.
```suggestion
   * Edits the reply to this interaction.
```

2022-11-19 19:58 UTC, kyranet requested changes

2022-11-19 19:58 UTC, kyranet commented on src/structures/interfaces/InteractionResponses.js
> +   * Options that can be passed into editReply.
Same as https://github.com/discordjs/discord.js/pull/8840#discussion_r1027134946

2022-11-20 12:07 UTC, jaw0r3k commented on src/structures/interfaces/InteractionResponses.js
> +   * Options that can be passed into editReply.
```suggestion
   * Options that can be passed into {@link InteractionResponses#editReply}.
```

2022-11-20 13:02 UTC, kyranet approved these changes

2022-11-25 17:18 UTC, iCrawl commented on typings/index.d.ts
>  export interface WebhookFetchMessageOptions {
```suggestion
}

export interface WebhookFetchMessageOptions {
```

2022-11-25 17:19 UTC, iCrawl approved these changes

2022-11-25 17:19 UTC, merged