feat(ClientApplication): add role connections
discordjs/discord.js pull request #8855
Opened 2022-11-22 01:57 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Upstream;
- discord/discord-api-docs#5668

Pending:
- discordjs/discord-api-types#651

**Status and versioning classification:**

2022-12-15 16:12 UTC, kyranet requested changes

2022-12-15 16:12 UTC, kyranet commented on packages/discord.js/src/structures/ApplicationRoleConnectionMetadata.js
> +    }
This pattern is only applicable for `_patch`, in the constructor it should be:

```suggestion
this.nameLocalizations = data.name_localizations ?? null;
```

2022-12-15 16:12 UTC, kyranet commented on packages/discord.js/src/structures/ApplicationRoleConnectionMetadata.js
> +    }
Same applies below.

2022-12-15 16:33 UTC, kyranet approved these changes

2022-12-15 19:11 UTC, Jiralite requested changes

2022-12-15 19:11 UTC, Jiralite commented on packages/discord.js/src/structures/ClientApplication.js
> +   * @typedef {Object} ApplicationRoleConnectionMetadataData
Shouldn't this be `ApplicationRoleConnectionMetadataEditOptions` per #8901?

2022-12-16 02:02 UTC, iCrawl approved these changes

2022-12-24 07:57 UTC, vladfrangu approved these changes

2022-12-24 08:00 UTC, merged