feat: add `@discordjs/formatters`
discordjs/discord.js pull request #8889
Opened 2022-11-30 20:40 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

This PR simply moves formatters out of builders into it's own package. This allows users who use formatters to not have to install the entirely of `/builders`.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2022-11-30 20:45 UTC, SpaceEEC approved these changes

2022-11-30 20:49 UTC, Jiralite requested changes

2022-11-30 20:49 UTC, Jiralite commented on .github/labeler.yml
> +  - packages:formatters/**/*
```suggestion
packages:formatters:
  - packages/formatters/*
  - packages/formatters/**/*
```

2022-11-30 20:53 UTC, Jiralite commented on packages/formatters/README.md
> +nudge in the right direction, please don't hesitate to join our official [discord.js Server][discord].
```suggestion
If you don't understand something in the documentation, you are experiencing problems, or you just need a gentle nudge in the right direction, please don't hesitate to join our official [discord.js Server][discord].
```

2022-12-01 09:14 UTC, Jiralite approved these changes

2022-12-01 10:14 UTC, kyranet requested changes
<details>
<summary>The evergrowing list of packages...</summary>

![image](https://user-images.githubusercontent.com/24852502/205025952-854138b2-9886-4901-b9ff-8488cff7da59.png)
<sup>*List goes brrr*</sup>

</details>

I have been considering a couple of things after this PR:

1. Replace some of the overloads with dynamic returns.
2. Moving sanitizers/cleaners (from mainlib) into this package.
3. Maybe sanitize all input before formatting. (@favna and I once discussed removing formatters from Sapphire, but he told me he won't unless Discord.js's formatters sanitize their input like Sapphire does).

2022-12-01 10:14 UTC, kyranet commented on packages/formatters/LICENSE
> +
Missing those lines:

https://github.com/discordjs/discord.js/blob/f13ff5c6d35d778c372f7fbb60d3fd947e594404/packages/builders/LICENSE#L178-L179

```suggestion

   Copyright 2021 Noel Buechler
   Copyright 2021 Vlad Frangu

```

2022-12-01 10:14 UTC, kyranet commented on packages/formatters/package.json
> +	"version": "1.0.0",
Are we releasing as v1 instead of v0.1?

2022-12-01 10:14 UTC, kyranet commented on packages/builders/src/index.ts
> +export * from '@discordjs/formatters';
We can make a follow-up PR once this one merges, to remove it, so we can include that change once we start preparing v15.

2022-12-02 12:55 UTC, merged