feat(ForumChannel): add `defaultForumLayout`
discordjs/discord.js pull request #8895
Opened 2022-12-01 16:40 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Upstream:
- discord/discord-api-docs#5693
Depends on:
- discordjs/discord-api-types#658

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

2022-12-01 22:25 UTC, Mateo-tem requested changes

2022-12-01 22:25 UTC, Mateo-tem commented on packages/discord.js/src/managers/CategoryChannelChildManager.js
> +   * @property {FormLayoutType} [defaultForumLayout] The default layout used to display posts (forum only).
```suggestion
   * @property {ForumLayoutType} [defaultForumLayout] The default layout used to display posts (forum only).
```

2022-12-15 15:48 UTC, kyranet approved these changes

2022-12-16 02:03 UTC, iCrawl approved these changes

2022-12-16 11:10 UTC, SpaceEEC approved these changes

2022-12-16 13:27 UTC, merged