feat: add links to each routes documentation
discordjs/discord.js pull request #8898
Opened 2022-12-01 18:21 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Adds links to the route documentation on each method

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-12-01 23:17 UTC, kyranet requested changes

2022-12-01 23:23 UTC, almeidx commented on packages/core/src/api/interactions.ts
> +	 * @see {@link https://discord.com/developers/docs/interactions/receiving-and-responding#delete-followup-message}
#8896 😅

2022-12-01 23:27 UTC, kyranet approved these changes

2022-12-01 23:28 UTC, kyranet commented on packages/core/src/api/interactions.ts
> +	 * @see {@link https://discord.com/developers/docs/interactions/receiving-and-responding#delete-followup-message}
🙏🏼 Thanks! I'll leave this unresolved for visibility.

2022-12-02 12:48 UTC, vladfrangu approved these changes

2022-12-07 13:58 UTC, SpaceEEC approved these changes

2022-12-07 16:32 UTC, merged