docs: Fix deprecated `isStringSelectMenu()` link
discordjs/discord.js pull request #8907
Opened 2022-12-04 05:01 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
The link was going nowhere. Now it does!

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2022-12-04 05:18 UTC, MrMythicalYT requested changes
https://github.com/discordjs/discord.js/blob/fb70df817c6566ca100d57ec1878a4573489a43d/packages/discord.js/src/structures/BaseInteraction.js#L278-L280
Shouldn't this file be updated too? `Interaction#isStringSelectMenu` is nonexistent

2022-12-04 05:30 UTC, Jiralite commented
That seems to not work also. Expanded on this pull request to fix that (and another link) too!

2022-12-04 11:09 UTC, SpaceEEC approved these changes

2022-12-06 10:19 UTC, vladfrangu approved these changes

2022-12-06 16:30 UTC, merged