feat(InteractionResponse): createdTimestamp
discordjs/discord.js pull request #8917
Opened 2022-12-09 03:40 UTC by BenjammingKirby

**Please describe the changes this PR makes and why it should be merged:**
InteractionResponses have IDs, we can just destructure it and get createdAt and createdTimestamp, (it's a getter because other such properties on other classes were getters)
Close #8916 
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-12-09 03:59 UTC, MrMythicalYT requested changes

2022-12-09 03:59 UTC, MrMythicalYT commented on packages/discord.js/src/structures/InteractionResponse.js
> +   * The timestamp the interaction's response was created at
```suggestion
   * The timestamp the interaction response was created at
```

2022-12-09 03:59 UTC, MrMythicalYT commented on packages/discord.js/src/structures/InteractionResponse.js
> +   * The time the interaction's response was created at
```suggestion
   * The time the interaction response was created at
```

2022-12-09 08:51 UTC, MaksiRose commented
As far as I know, `createdTimestamp` is normally a normal property rather than a method. Is there a reason this is different here?

2022-12-09 08:52 UTC, imranbarbhuiya commented
This isn't a method but a getter that behaves like a property but u can return result dynamically

2022-12-09 11:44 UTC, imranbarbhuiya commented
using property will store the `Date` and `number` in memory and using getter, it'll generate when needed without storing. Ig this is the reason for not using property but not sure tho

2022-12-09 13:51 UTC, Qjuh commented
> using property will store the `Date` and `number` in memory and using getter, it'll generate when needed without storing. Ig this is the reason for not using property but not sure tho

That, but also that it doesn’t have to be calculated at all if it isn’t used.

2022-12-12 08:19 UTC, kyranet approved these changes

2022-12-14 21:17 UTC, SpaceEEC approved these changes

2022-12-14 21:25 UTC, vladfrangu approved these changes

2022-12-14 21:35 UTC, merged