refactor: moved escapeX funcs from discord.js to @discord.js/formatters
discordjs/discord.js pull request #8957
Opened 2022-12-21 17:22 UTC by Cl00e9ment

## Changes

- moved the escapeX functions from `discord.js` to `@discord.js/formatters`
- converted the code from JS to TS (including JSDoc and TSDoc)
- made the linter happy
- modified the `escapeHeading`'s RegExp to pass the linter's RegExp safety test
- `escapeBulletedList` now conserves the bullet style (`-` or `*`)

## Reason

`@discord.js/formatters` provides the `italic`, `bold`, etc... functions so it's natural to have the `escapeItalic`, `escapeBold`, etc... functions here too.

With this modification, it's possible to use these functions without having to require `discord.js`. That's why I did this PR: I'm currently trying to get rid of `discord.js` and directly use `@discord.js/ws` and other packages like `@discord.js/formatters`.

## Breaking change?

I don't know if this is a breaking change. The functions are no longer in `Util`, but importing them directly from `discord.js` should still works since it re-exports the `@discord.js/formatters` functions. Maybe there is some edge case to take into account.

About the documentation, again I don't know if there is something to update or not.

2022-12-21 17:57 UTC, almeidx requested changes
Need to remove these
https://github.com/discordjs/discord.js/blob/429dbccc85cabd9986b2e8bf443bf384e4ddc61a/packages/discord.js/typings/index.d.ts#L3033-L3045

2022-12-21 17:57 UTC, almeidx commented on packages/formatters/src/escapers.ts
> +/* eslint-enable prefer-named-capture-group */
```suggestion
```

2022-12-24 07:31 UTC, vladfrangu approved these changes

2022-12-24 22:22 UTC, Jiralite requested changes
#8945 should be factored into this.

2022-12-25 00:03 UTC, Cl00e9ment commented
I added the changes made by @almeidx in #8945 and rebased the branch.

2022-12-25 00:10 UTC, Cl00e9ment commented
oops I messed up the reviewer list. I don't know if I can add again the reviewers.

2022-12-26 15:42 UTC, almeidx commented
This needs a rebase

2022-12-26 17:47 UTC, Cl00e9ment commented
> This needs a rebase

done

2022-12-26 18:43 UTC, almeidx approved these changes

2023-01-10 10:00 UTC, iCrawl approved these changes

2023-01-13 10:26 UTC, kyranet approved these changes

2023-01-13 16:17 UTC, SpaceEEC approved these changes

2023-01-13 16:21 UTC, merged