feat(Guild): add safety alerts channel and mention raid protection
discordjs/discord.js pull request #8959
Opened 2022-12-22 01:24 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Upstream:
- discord/discord-api-docs#5778

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2022-12-22 01:41 UTC, Jiralite requested changes

2022-12-22 01:41 UTC, Jiralite commented on packages/discord.js/src/structures/Guild.js
> +   *  .catch(console.error);
This is missing the `@example` tag. That aside, does this really need one?

2022-12-24 07:28 UTC, vladfrangu approved these changes

2022-12-25 19:52 UTC, kyranet approved these changes

2022-12-25 20:26 UTC, SpaceEEC approved these changes

2023-01-02 20:02 UTC, DraftProducts approved these changes

2023-05-05 18:36 UTC, Jiralite requested changes

2023-05-05 18:36 UTC, Jiralite commented on packages/discord.js/src/structures/Guild.js
> +   *  .then(updated => console.log(`Updated guild safety alerts channel to ${guild.safetyAlertsChannel.name}`))
For consistency, this should use the `updated` variable:

```suggestion
   *  .then(updated => console.log(`Updated guild safety alerts channel to ${updated.safetyAlertsChannel.name}`))
```

2023-05-05 18:36 UTC, Jiralite approved these changes

2023-05-05 18:39 UTC, merged