types: Swap message reaction and emoji identifier types
discordjs/discord.js pull request #8969
Opened 2022-12-25 01:20 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Resolves #8968 by somewhat swapping the types for `EmojiIdentifierResolvable` and `MessageReactionResolvable`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-12-25 11:09 UTC, DraftProducts approved these changes

2022-12-25 19:04 UTC, kyranet requested changes

2022-12-25 19:04 UTC, kyranet commented on packages/discord.js/typings/index.d.ts
> +  | `<a:${string}:${Snowflake}>`
You can simplify the two into a single one:
```suggestion
  | `<${'' | 'a'}:${string}:${Snowflake}>`
```

That being said, this is all union'd with `string`, so the string template types are... ignored.

2022-12-25 19:04 UTC, kyranet commented on packages/discord.js/typings/index.d.ts
> +  | `${string}:${Snowflake}`
Seeing `a:name:id` is supported according to the jsdoc:
```suggestion
  | `${'' | 'a:'}${string}:${Snowflake}`
```

2022-12-25 19:31 UTC, kyranet approved these changes

2022-12-25 19:47 UTC, DraftProducts approved these changes

2022-12-25 20:20 UTC, SpaceEEC approved these changes

2022-12-31 00:15 UTC, vladfrangu approved these changes

2022-12-31 00:33 UTC, merged