types: Swap message reaction and emoji identifier types
discordjs/discord.js pull request #8970
Opened 2022-12-25 01:38 UTC by Jiralite

Backports #8969 to version 13.

2022-12-25 19:37 UTC, kyranet requested changes

2022-12-25 19:37 UTC, kyranet commented on typings/index.d.ts
> +  | `<a:${string}:${Snowflake}>`
```suggestion
  | `${'' | 'a:'}${string}:${Snowflake}`
  | `<${'' | 'a'}:${string}:${Snowflake}>`
```

2022-12-25 19:49 UTC, kyranet approved these changes

2022-12-25 20:24 UTC, SpaceEEC approved these changes

2022-12-31 00:14 UTC, vladfrangu approved these changes

2023-01-01 17:28 UTC, iCrawl approved these changes

2023-01-01 17:28 UTC, merged