typings(Attachment): remove attachment property
discordjs/discord.js pull request #8982
Opened 2022-12-26 22:01 UTC by net-tech

**Please describe the changes this PR makes and why it should be merged:**

Removes `<Attachment>.attachment`. This isn't documented anywhere in the [docs](https://discord.js.org/#/docs/discord.js/main/class/Attachment) and from my testing returns a URL like `https://cdn.discordapp.com/ephemeral-attachments/XXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXX/message.txt`. If this is here on purpose then the typing should be `string`, not `BufferResolvable | Stream`.

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.
- Code changes have been tested against the Discord API, or there are no code changes

2022-12-26 22:10 UTC, Jiralite commented
I cannot seem to find where this is referenced:

https://github.com/discordjs/discord.js/blob/3160ab0fc75946041cbe7a093032ea10503dfd8c/packages/discord.js/src/structures/Attachment.js#L17

Perhaps it's remnants of an old refactor - possibly from being split into a builder? That property can be removed too. Pretty sure.

2022-12-26 22:23 UTC, Jiralite commented
Okay, I just found out how and where this is being used.

Let's say a message is created and it has an attachment. They would be created as an `Attachment`. The property `this.attachment = data.url;` is being defined here.

We modify that via `AttachmentBuilder.from()`. For example: `const attachment = AttachmentBuilder.from(message.attachments.first());`

Without that property, it looks like the `AttachmentBuilder` will not be properly created. Definitely something funny is going on here, but for now, I would keep that property as it is and remove only the typing.

2022-12-26 22:37 UTC, net-tech commented
@Jiralite Wait, revert structures change and keep the typing removed entirely or revert structures change and keep the typing but change it to `string`?

2022-12-26 22:38 UTC, Jiralite commented
Probably best to remove the typings altogether since there is no documentation for it.

2022-12-27 06:04 UTC, Syjalo commented
Isn't it better to make that property private?

2023-01-04 17:23 UTC, net-tech commented
> Isn't it better to make that property private?

Done.

2023-01-08 13:12 UTC, Idris1401 commented
Maybe you should change the return type too, if it actually returns a `string` (or it doesn't matter?).

2023-01-13 10:45 UTC, kyranet requested changes

2023-01-13 10:45 UTC, kyranet commented on packages/discord.js/typings/index.d.ts
> +  private attachment: BufferResolvable | Stream;
Considering it's initially set to `data.url`, which is a string:
```suggestion
  private attachment: BufferResolvable | Stream | string;
```

2023-01-13 13:56 UTC, kyranet approved these changes

2023-02-17 14:33 UTC, Jiralite approved these changes
Do you mind also modifying the pull request title to reflect the changes too?

2023-02-17 19:35 UTC, iCrawl approved these changes

2023-02-17 19:40 UTC, vladfrangu approved these changes

2023-02-17 20:28 UTC, SpaceEEC approved these changes

2023-02-17 21:52 UTC, merged