chore: init discord.js-next
discordjs/discord.js pull request #8988
Opened 2022-12-28 22:21 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

Simple init of the typescript rewrite package to allow its parallel development.

All places that have per-package things have been updated, however

1. Will we actually have prereleases for this? If yes is it @discordjs/discord.js-next@dev or discord.js@next?
2. Do we actually want separate labels and such for this? I think yes at least for now, but thoughts appreciated.

Furthermore, one more little kink to iron out with this,
Every package re-exports -types causing a clash in reexporting these subpackages, solved at the moment by disabling import/export. This doesn't feel elegant, and there has to be a better way.
Furthermore, we cannot reexport both ws and core in full as star exports because core has an overwritten events map with the same name.

One solution to this is to reexport with named exports, so each subpackage has its name. Not perfect but it seems better. Again, thoughts appreciated.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2022-12-29 17:48 UTC, SuperchupuDev commented on packages/discord.js-next/package.json
> +	"description": "A powerful typescript library for interacting with the Discord API",
```suggestion
	"description": "A powerful TypeScript library for interacting with the Discord API",
```

2023-01-07 00:09 UTC, suneettipirneni commented
Should TSR use node 18?

2023-01-10 11:50 UTC, iCrawl commented
@suneettipirneni Yes, 18 is LTS so we can def push for that.

2023-01-10 22:12 UTC, JuanPablo2655 requested changes

2023-01-10 22:12 UTC, JuanPablo2655 commented on packages/actions/src/uploadCoverage/action.yml
> +        flags: mext
```suggestion
        flags: next
```

2023-01-10 22:44 UTC, ckohen commented on packages/actions/src/uploadCoverage/action.yml
> +        flags: mext
beat me to it lol

2023-01-11 14:15 UTC, SuperchupuDev commented on packages/next/README.md
> +[documentation]: https://discord.js.org/#/docs/util
```suggestion
[documentation]: https://discord.js.org/#/docs/next
```

2023-01-11 14:15 UTC, SuperchupuDev commented on packages/next/README.md
> +[npm]: https://www.npmjs.com/package/@discordjs/util
```suggestion
[source]: https://github.com/discordjs/discord.js/tree/main/packages/next
[npm]: https://www.npmjs.com/package/@discordjs/next
```

2023-01-12 09:27 UTC, merged