refactor(website): extract layouts and use more server components
discordjs/discord.js pull request #9027
Opened 2023-01-07 20:34 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

This PR does a large amount of refactoring the website components and associated pages and layouts.

Firstly, server components are used where they are deemed effective. This is usually for components that are static and don't rely on client-side state. A positive side-effect of this change is the amount of serialization has been reduce dramatically. In our current website we have to serialize *all* `ApiItems` directly when pages are generated. This was because the network boundary was between `page.tsx` and every other component. With the refactor the network boundary is between a server component and and client component which means we can pass class instances directly to server components. 

Secondly, layouts have been extracted or rather "moved up". Currently our main documentation layout rerenders anytime a new item is selected. This result in things like the sidebar and nav bar flickering and scroll state being reset. This occurs because we used [...slug] as a catch-all route, meaning next considered any changes to parameter in this route a signal to re-render the documentation shell. To fix this I simply pulled routes up that have persistent layouts (for example the documentation shell). This resulted in scroll states being persisted between elements and less re-renders for items that use the same props.

>  **Note**
> When looking at the code you may think that we are doing a lot of redundant fetches for each of the nested layouts, however this actually isn't the case. The same fetches use across layouts are deduped, so the requests only happen once as described [here](https://beta.nextjs.org/docs/data-fetching/fundamentals#automatic-fetch-request-deduping)

Finally, I added some requested changes to the website (scope creep). `@see` block rendering and proper documentation for classes that use mixins.

Closes #8920 
Closes #8997

2023-01-07 20:50 UTC, almeidx commented on packages/ui/vite.config.ts.timestamp-1672422498444.mjs
> +// vite.config.ts
This file shouldn't be here. Should probably also add it to the root .gitignore

2023-01-07 21:38 UTC, kyranet submitted a review, later dismissed

2023-01-07 21:38 UTC, kyranet commented on packages/api-extractor-utils/src/tsdoc/LinkTagCommentNode.ts
> +	console.log(item);
👀

2023-01-07 21:38 UTC, kyranet commented on apps/website/package.json
> +		"next": "latest",
I don't think we should use `latest`, but rather, a specific version.

2023-01-10 09:43 UTC, iCrawl requested changes

2023-01-10 09:43 UTC, iCrawl commented on apps/website/next.config.js
> +	productionBrowserSourceMaps: true,
🔕

2023-01-10 09:43 UTC, iCrawl commented on apps/website/design.txt
> +function DocumentationHeader(item={APIItem}) { // Server
Whats this

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docAPI.ts
> +		// next: { revalidate: 3_600 },
No revalidation?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/package.json
> +		"next": "canary",
Should pin a specific canary version, if you aren't waiting for something specific that is.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx
> +export const dynamicParams = true;
This is the default value for `dynamicParams` already.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx
> +		<div>
Is that wrapper `div` necessary here?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/layout.tsx
> +import vercelLogo from '../../../../../assets/powered-by-vercel.svg';
```suggestion
import vercelLogo from '~/assets/powered-by-vercel.svg';
```

Maybe?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/layout.tsx
> +export const dynamicParams = true;
Default value is true already.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/layout.tsx
> +		<div>
Wrapper `div` can be a `Fragment/<>` instead?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/page.tsx
> +	const res = await fetch(`https://docs.discordjs.dev/api/info?package=${pkg}`, {});
No revalidation?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/page.tsx
> +						href={`/docs/packages/${params.package}/${version}/`}
Trailing slash?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/docs/packages/page.tsx
> +						href={`/docs/packages/${pkg}/`}
Trailing slash?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/app/layout.tsx
> +export const dynamicParams = true;
Default value is true.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/Anchor.tsx
> +			aria-label="Anchor"
I don't think that is necessary, native HTML elements already have proper ARIA tags applied.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/ExcerptText.tsx
> +						<ItemLink className="color-blurple" itemURI={resolveItemURI(item)} key={item.containerKey}>
```suggestion
						<ItemLink className="text-blurple" itemURI={resolveItemURI(item)} key={item.containerKey}>
```

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/ExcerptText.tsx
> +						<ItemLink className="color-blurple" itemURI={resolveItemURI(item)} key={item.containerKey}>
Double check all instances where we use `color-` instead of `text-`

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/Header.tsx
> +					{/* <div className="hidden md:flex md:flex-row md:overflow-hidden">{breadcrumbs}</div> */}
?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/Panel.tsx
> +export function Panel({ children }: { children: React.ReactNode }) {
```suggestion
import type { PropsWithChildren } from 'react';

export function Panel({ children }: PropsWithChildren) {
```

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/Scrollbars.tsx
> +	return <ReactScrollBars2 {...props} />;
```suggestion
import { Scrollbars as ReactScrollbars2 } from 'react-custom-scrollbars-2';

export function Scrollbars(props: ScrollbarProps) {
	return <ReactScrollbars2 {...props} />;
```

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/documentation/ExtendsText.tsx
> +import { type ApiClass, ApiItemKind } from '@microsoft/api-extractor-model';
```suggestion
import type { ApiClass, ApiInterface, Excerpt } from '@microsoft/api-extractor-model';
import { ApiItemKind } from '@microsoft/api-extractor-model';
```

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/documentation/ImplementsText.tsx
> +export function ImplementsText({ item }: { item: ApiClass }) {}
Is this incomplete still?

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/model/method/MethodName.tsx
> +					aria-label="Anchor"
Mentioned above already, not needed.

2023-01-10 09:43 UTC, iCrawl commented on apps/website/src/components/model/method/MethodName.tsx
> +					aria-label="Anchor"
Also I saw a component like this earlier, can probably re-use it?

2023-01-10 17:25 UTC, merged