refactor: Move `me` and add `fetchMe()`
discordjs/discord.js pull request #9029
Opened 2023-01-08 03:07 UTC by Jiralite

Backports the following pull requests to version 13:

- #7526
- #7669
- #8258

In addition, a deprecation warning now emits for `Guild#me`.

2023-01-08 12:20 UTC, jaw0r3k commented
is it really needed ?

2023-01-08 13:14 UTC, kyranet approved these changes

2023-01-08 14:30 UTC, Qjuh requested changes
Typings are missing `GuildMemberManager#me`.

2023-01-08 17:10 UTC, SpaceEEC approved these changes

2023-01-09 05:25 UTC, Qjuh approved these changes

2023-01-10 09:49 UTC, merged