feat(Sticker): add support for gif stickers
discordjs/discord.js pull request #9038
Opened 2023-01-10 19:16 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Upstream:
- discord/discord-api-docs#5833

Depends on:
- discordjs/discord-api-types#688

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

2023-01-12 20:31 UTC, vladfrangu approved these changes

2023-01-12 20:48 UTC, SpaceEEC approved these changes

2023-01-13 09:29 UTC, kyranet reviewed
Minor nits, the map is a pseudo-enum, so it needs to be named in PascalCase, as the rest of the constants from the Constants file (https://github.com/discordjs/discord.js/blob/05a1cbfe5479195b0bc9b6f0971fe39f6af6fd77/packages/discord.js/src/util/Constants.js).

Also, shouldn't we export this (in the `Constants` file) so users can map the extensions themselves?

2023-01-13 09:29 UTC, kyranet commented on packages/discord.js/src/structures/Sticker.js
> +const stickerFormatExtensionMap = {
```suggestion
const StickerFormatExtensionMap = {
```

2023-01-13 09:29 UTC, kyranet commented on packages/discord.js/src/structures/Sticker.js
> +    return this.client.rest.cdn.sticker(this.id, stickerFormatExtensionMap[this.format]);
```suggestion
    return this.client.rest.cdn.sticker(this.id, StickerFormatExtensionMap[this.format]);
```

2023-01-13 09:30 UTC, kyranet requested changes
Sorry, I <kbd>Ctrl+Enter</kbd>'d instead of clicking "Request changes". ↑

2023-01-13 15:15 UTC, kyranet approved these changes

2023-01-13 15:29 UTC, merged