feat(core): Adds `getChannel()` function for webhooks
discordjs/discord.js pull request #9043
Opened 2023-01-11 06:16 UTC by dager-mohamed

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

This function requests the Discord API to fetch all webhooks associated with a specific channel. It does this by using the `id` parameter, which specifies the id of the channel for which the webhooks are to be retrieved. The `Routes.channelWebhooks(id)` method is used to construct the URL of the API endpoint that retrieves the webhooks for the specified channel. The function then makes a GET request to that URL using the `rest.get()` method, and the result of that request is returned as a promise, which will resolve to an object of type `RESTGetAPIWebhookResult`.

This request allows the retrieval of all webhooks created in a specific channel. It's possible to have multiple webhooks associated with a channel and they will be returned in an array in response to the request.

2023-01-11 18:19 UTC, Qjuh commented
This should be a `getWebhooks` method on the channel API, since you don’t get a channel from a webhook but the other way around.
And while you‘re at it: a similar method is also missing on the guild API to fetch all guild webhooks.

2023-01-11 23:49 UTC, dager-mohamed commented
> This should be a `getWebhooks` method on the channel API, since you don’t get a channel from a webhook but the other way around. And while you‘re at it: a similar method is also missing on the guild API to fetch all guild webhooks.

done added `getWebhooks()` function for the guild and channel, added for the guild to list of guild webhooks object, and for channel API to get the webhooks of the channel.

2023-01-12 00:25 UTC, almeidx requested changes

2023-01-12 00:25 UTC, almeidx commented on packages/core/src/api/channel.ts
> +		return this.rest.get(Routes.channelWebhooks(id)) as Promise<RESTGetAPIWebhookResult>;
```suggestion
		return this.rest.get(Routes.channelWebhooks(id)) as Promise<RESTGetAPIChannelWebhooksResult>;
```

2023-01-12 00:25 UTC, almeidx commented on packages/core/src/api/channel.ts
> +	type RESTGetAPIWebhookResult,
```suggestion
	type RESTGetAPIChannelWebhooksResult,
```

2023-01-12 00:25 UTC, almeidx commented on packages/core/src/api/guild.ts
> +	type RESTGetAPIWebhookResult,
```suggestion
	type RESTGetAPIGuildWebhooksResult,
```

2023-01-12 00:25 UTC, almeidx commented on packages/core/src/api/guild.ts
> +		return this.rest.get(Routes.guildWebhooks(id)) as Promise<RESTGetAPIWebhookResult>;
```suggestion
		return this.rest.get(Routes.guildWebhooks(id)) as Promise<RESTGetAPIGuildWebhooksResult>;
```

2023-01-12 20:30 UTC, vladfrangu approved these changes

2023-01-12 20:34 UTC, Jiralite reviewed
Consistency with other descriptions!

2023-01-12 20:34 UTC, Jiralite commented on packages/core/src/api/guild.ts
> +	 * Fetches guild webhooks
```suggestion
	 * Fetches webhooks for a guild
```

2023-01-13 00:08 UTC, suneettipirneni approved these changes

2023-01-13 09:23 UTC, kyranet requested changes

2023-01-13 09:23 UTC, kyranet commented on packages/core/src/api/channel.ts
> +	type RESTGetAPIChannelWebhooksResult,
This import is not sorted, it should be on line 15 (`RESTGetAPIChannelUsersThreadsArchivedResult` → `RESTGetAPIChannelWebhooksResult` → `RESTPatchAPIChannelJSONBody`).

2023-01-13 09:23 UTC, kyranet commented on packages/core/src/api/guild.ts
> +	type RESTGetAPIGuildWebhooksResult,
This import isn't sorted, it should be on line 41 (`RESTGetAPIGuildMembersSearchQuery` → `RESTGetAPIGuildWebhooksResult` → `RESTGetAPIGuildWelcomeScreenResult`).

2023-01-13 09:36 UTC, dager-mohamed commented
done, the imported types has been sorted
@kyranet

2023-01-13 10:39 UTC, kyranet approved these changes

2023-01-17 19:32 UTC, dager-mohamed commented
@SpaceEEC
@iCrawl

2023-02-17 22:40 UTC, SpaceEEC approved these changes

2023-02-17 23:35 UTC, merged