feat v13: add `INVITES_DISABLED` flag
discordjs/discord.js pull request #9051
Opened 2023-01-12 16:10 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**
Adds  `INVITES_DISABLED` flag
And backports #8801
**Status and versioning classification:**

2023-01-12 19:33 UTC, Jiralite requested changes

2023-01-12 19:33 UTC, Jiralite commented on src/structures/Guild.js
> +  /**
```suggestion

  /**
```

2023-01-12 20:27 UTC, vladfrangu approved these changes

2023-01-12 20:31 UTC, SpaceEEC approved these changes

2023-01-13 09:33 UTC, kyranet approved these changes

2023-02-17 21:45 UTC, merged