feat(Client): `auditLogEntryCreate` event
discordjs/discord.js pull request #9058
Opened 2023-01-13 00:16 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Upstream:
- discord/discord-api-docs#5849

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

2023-01-13 10:17 UTC, SpaceEEC approved these changes

2023-01-13 10:39 UTC, kyranet approved these changes

2023-01-13 17:15 UTC, Jiralite reviewed
Should update the list of intents too via the issue tracker.

2023-01-14 03:31 UTC, Jiralite requested changes
This doesn't work because the gateway event is called `GUILD_AUDIT_LOG_ENTRY_CREATE` but this is looking for `AUDIT_LOG_ENTRY_CREATE`.

2023-01-14 03:31 UTC, Jiralite commented on packages/discord.js/src/client/actions/AuditLogEntryCreate.js
> +       * @param {AuditLogEntry} auditLogEntry The entry that was created
I believe `AuditLogEntry` is more important and should be emitted as the first parameter. It would also be consistent with other events.

2023-01-14 04:08 UTC, Jiralite commented
I seem to have found a bug with this event. Use this very basic bot:

```TypeScript
import { Client, Events, GatewayIntentBits } from "discord.js";

const client = new Client({ intents: GatewayIntentBits.Guilds | GatewayIntentBits.GuildBans });

client.on("raw", console.log);
client.on(Events.AuditLogEntryCreate, console.log);

client.login();
```

Upon pinning a message, this event will be received:

```JavaScript
{
  t: 'GUILD_AUDIT_LOG_ENTRY_CREATE',
  s: 6,
  op: 0,
  d: {
    user_id: 'user_id',
    target_id: 'target_id',
    options: {
      message_id: 'message_id',
      channel_id: 'channel_id'
    },
    id: 'id',
    action_type: 74,
    guild_id: 'guild_id'
  }
}
```

When discord.js constructs a `GuildAuditLogsEntry` out of it, `GuildAuditLogsEntry#executor` and `GuildAuditLogsEntry#target` are both `undefined`.

You can see how these are defined here:

https://github.com/discordjs/discord.js/blob/13ce78af6e3aedc793f53a099a6a615df44311f7/packages/discord.js/src/structures/GuildAuditLogsEntry.js#L127-L131

https://github.com/discordjs/discord.js/blob/13ce78af6e3aedc793f53a099a6a615df44311f7/packages/discord.js/src/structures/GuildAuditLogsEntry.js#L292-L297

When audit logs are fetched (as they have been all this time), Discord sends across the user objects that the audit log references and we store them safely away. However, the gateway **does not** do this. These are now potentially `undefined` and the same may go for application commands, auto moderation rules, scheduled events, integrations, threads, and webhooks. Currently, these are typed as always present.

2023-02-17 19:43 UTC, vladfrangu approved these changes

2023-02-17 20:11 UTC, merged