fix(MessageReaction): `toJSON()` infinite recursion
discordjs/discord.js pull request #9070
Opened 2023-01-15 21:05 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Fixes #9067

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2023-01-17 18:55 UTC, vladfrangu requested changes

2023-01-17 18:55 UTC, vladfrangu commented on packages/discord.js/src/structures/MessageReaction.js
> +    return this.id;
This doesn't exist 🤔

2023-02-08 12:39 UTC, vladfrangu approved these changes

2023-02-08 22:02 UTC, kyranet approved these changes

2023-02-17 14:39 UTC, Jiralite approved these changes

2023-02-17 19:37 UTC, iCrawl approved these changes

2023-02-17 19:51 UTC, merged