feat(website): render syntax and mdx on the server
discordjs/discord.js pull request #9086
Opened 2023-01-23 16:40 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

By rendering on the server we put less CPU load on the client, and also decrease bundle size.

2023-02-19 00:00 UTC, NotSugden requested changes

2023-02-19 00:09 UTC, almeidx commented on apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx
> +		const modelJSONFiles = await Promise.all(PACKAGES.map(async (pkg) => fetchModelJSON(pkg, branchName)));
It is due to the ESLint config

2023-02-19 16:11 UTC, NotSugden commented on apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx
> +		const modelJSONFiles = await Promise.all(PACKAGES.map(async (pkg) => fetchModelJSON(pkg, branchName)));
why does eslint want it to be async

2023-03-23 12:31 UTC, iCrawl commented on apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx
> +	return entry.members.map((member: any) => ({
😠

2023-03-23 21:17 UTC, merged