feat: v13 `guildAuditLogEntryCreate` event
discordjs/discord.js pull request #9092
Opened 2023-01-25 18:33 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**
 Backports:
 - #9058
 
**Status and versioning classification:**

2023-02-12 18:15 UTC, aiko-chan-ai commented on src/client/actions/GuildAuditLogEntryCreate.js
> +const Events = require('../../util/Events');
```suggestion
const { Events } = require('../../util/Constants');
```

2023-02-17 20:24 UTC, SpaceEEC requested changes
Seems to work fine with this change

2023-02-17 20:24 UTC, SpaceEEC commented on src/client/actions/GuildAuditLogEntryCreate.js
> +      client.emit(Events.GuildAuditLogEntryCreate, auditLogEntry, guild);
```suggestion
      client.emit(Events.GUILD_AUDIT_LOG_ENTRY_CREATE, auditLogEntry, guild);
```

2023-02-17 22:07 UTC, kyranet approved these changes

2023-02-17 22:08 UTC, SpaceEEC approved these changes

2023-02-17 23:07 UTC, merged