feat(GuildMember): v13 add `flags`
discordjs/discord.js pull request #9098
Opened 2023-01-30 13:34 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**
Backports:
- #9087

**Status and versioning classification:**

2023-01-30 13:49 UTC, almeidx requested changes

2023-01-30 13:49 UTC, almeidx commented on src/util/GuildMemberFlags.js
> + * @memberof ActivityFlags
```suggestion
 * @name GuildMemberFlags
 * @kind constructor
 * @memberof GuildMemberFlags
```

2023-01-30 13:49 UTC, almeidx commented on src/util/GuildMemberFlags.js
> + * * A string (see {@link GuildMemberFlagsBitField.Flags})
```suggestion
 * * A string (see {@link GuildMemberFlags.FLAGS})
```

2023-01-30 13:49 UTC, almeidx commented on src/util/GuildMemberFlags.js
> + * * An instance of GuildMemberFlagsBitField
```suggestion
 * * An instance of GuildMemberFlags
```

2023-01-30 13:49 UTC, almeidx commented on typings/index.d.ts
> +export type GuildMemberFlagsResolvable= BitFieldResolvable<GuildMemberFlagsString, number>;
```suggestion

export type GuildMemberFlagsString = 'DID_REJOIN' | 'COMPLETED_ONBOARDING'| 'BYPASSES_VERIFICATION'| 'STARTED_ONBOARDING';

export type GuildMemberFlagsResolvable = BitFieldResolvable<GuildMemberFlagsString, number>;
```

2023-02-17 19:44 UTC, vladfrangu approved these changes

2023-02-17 20:06 UTC, SpaceEEC approved these changes

2023-02-17 21:12 UTC, SpaceEEC approved these changes

2023-02-17 21:16 UTC, merged