feat(cleanContent): add missing emojis & slash mentions
discordjs/discord.js pull request #9143
Opened 2023-02-18 15:54 UTC by DraftProducts

**Please describe the changes this PR makes and why it should be merged:**

The function `<Util>.cleanContent` function replace all mentions by the text equivalent.
This PR add the two missing mentions types : 
- **Commands mentions**: `</command:318312854816161792>`.
- **Custom emojis mentions**:  `<:emoji:318312854816161792>`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-02-18 17:13 UTC, jaw0r3k commented
`:name` doesnt look like a proper way to show a emoji

2023-02-18 17:53 UTC, DraftProducts commented
> `:name` doesnt look like a proper way to show an emoji

Discord render emojis like that : `:name:`

2023-02-18 17:57 UTC, jaw0r3k commented
> Discord render emojis like that : `:name:`

Then nvm

2023-03-29 14:14 UTC, vladfrangu requested changes

2023-03-29 14:14 UTC, vladfrangu commented on packages/discord.js/src/util/Util.js
> +  return str.replaceAll(/<(?:(@[!&]?|#)|([/:])([\w ]+):)(\d{17,19})>/g, (match, type, prefix, name, id) => {
Your regexp does not match animated emojis! it's also became much more complex to handle.

![Google Chrome Dev - 2023-03-29 at 17 03 58@2x](https://user-images.githubusercontent.com/17960496/228563557-12db4694-f89b-4e11-b06e-1ac1be1700fc.png)

You could use `<(?:(?<type>@[!&]?|#)|(?:(?<command>\/[\w ]+)|(?<animatedEmoji>a)?:(?<emojiName>[\w]+)):)(?<id>\d{17,19})>` for a regex, and then use the groups for the actual replacing (if you prefer that), or.. honestly 🤷 whatever floats your boat

![Google Chrome Dev - 2023-03-29 at 17 14 12@2x](https://user-images.githubusercontent.com/17960496/228566691-a8c7e2f2-bbf9-48bb-9524-d79f18583992.png)

2023-09-07 14:09 UTC, DraftProducts commented
My apologies for forgetting and abandoning PR; strangely enough, I don't seem to have received any notification of the answer or milestone changes 🤔

2023-09-07 14:09 UTC, closed without merging