feat(collection): align some methods with the Change By Copy proposal
discordjs/discord.js pull request #9207
Opened 2023-03-06 12:56 UTC by almeidx

**Please describe the changes this PR makes and why it should be merged:**
Stage 4 proposal:
- https://github.com/tc39/proposal-change-array-by-copy

Overview of the changes:
- `sorted` -> `toSorted`
- Added `toReversed`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2023-03-06 12:57 UTC, almeidx commented on packages/collection/src/collection.ts
> +	 * Identical to {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed | Array.toReversed()}
This page doesn't currently exist but I imagine it will be added at some point

2023-03-22 19:29 UTC, kyranet requested changes

2023-03-22 19:29 UTC, kyranet commented on packages/collection/__tests__/collection.test.ts
> +	});
This is redundant with the test below.

2023-03-22 19:29 UTC, kyranet commented on packages/collection/__tests__/collection.test.ts
> +	});
This is redundant with the test below.

2023-05-01 22:12 UTC, vladfrangu approved these changes

2023-11-07 18:16 UTC, suneettipirneni approved these changes

2023-11-07 18:17 UTC, SpaceEEC approved these changes

2023-11-07 18:26 UTC, merged