chore: Include discord.js in the user agent string
discordjs/discord.js pull request #9267
Opened 2023-03-23 04:34 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
This includes discord.js in the user agent string, even if a custom appendix is supplied.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-03-23 06:44 UTC, vladfrangu approved these changes

2023-03-23 06:50 UTC, kyranet requested changes

2023-03-23 06:50 UTC, kyranet commented on packages/discord.js/src/client/BaseClient.js
> +      options.rest.userAgentAppendix = `${Options.userAgentAppendix} ${options.rest?.userAgentAppendix}`;
The existence of the field is already checked by line 17.
```suggestion
      options.rest.userAgentAppendix = `${Options.userAgentAppendix} ${options.rest.userAgentAppendix}`;
```

2023-03-23 06:50 UTC, kyranet commented on packages/discord.js/src/client/BaseClient.js
> +    if (options.rest?.userAgentAppendix !== undefined) {
This should be below line 23 so it checks for `options`'s type first. Otherwise passing `null` will result on a different error.

2023-03-23 13:30 UTC, almeidx commented on packages/discord.js/src/client/BaseClient.js
> +    if (options.rest?.userAgentAppendix !== undefined) {
Appending an empty string is probably not very useful
```suggestion
    if (options.rest?.userAgentAppendix) {
```

2023-03-24 14:49 UTC, almeidx requested changes
As a side note, shouldn't /rest's default user agent URL point to the new docs (`https://discordjs.dev/docs/packages/rest` or something), or use `@discordjs/rest@<version>` in the version itself? Currently, it's set to `DiscordBot (https://discord.js.org, 1.6.0)`

2023-03-24 14:49 UTC, almeidx commented on packages/discord.js/src/util/Options.js
> +  static userAgentAppendix = `discord.js/${version} ${DefaultUserAgentAppendix}`.trim();
With the changes to `DefaultUserAgentAppendix`, there are no extra spaces here anymore
```suggestion
  static userAgentAppendix = `discord.js/${version} ${DefaultUserAgentAppendix}`;
```

2023-03-24 14:52 UTC, almeidx commented on packages/discord.js/src/util/Options.js
> +  static userAgentAppendix = `discord.js/${version} ${DefaultUserAgentAppendix}`.trim();
oops, yeah. I mistook it for `DefaultUserAgent`. `trimEnd()` can be used here instead then

2023-03-24 15:02 UTC, Jiralite commented
From https://discord.com/developers/docs/reference#user-agent-user-agent-example, there doesn't seem to be a place to include `@discordjs/rest`—supposedly, the URL accounts for that. Changing the URL to the new documentation site would probably be best done in another pull request where we change everything over.

2023-04-01 22:10 UTC, SpaceEEC approved these changes

2023-04-01 22:26 UTC, merged