refactor: remove zlib-sync
discordjs/discord.js pull request #9279
Opened 2023-03-26 12:10 UTC by didinele

**Please describe the changes this PR makes and why it should be merged:**
draft because vlad wants us to keep zlib-sync & the new pure-native node:zlib impl together for a few dev releases

**Status and versioning classification:**

2023-03-26 12:14 UTC, kyranet requested changes
Just a tiny thing:

2023-03-26 12:14 UTC, kyranet commented on packages/ws/src/ws/WebSocketShard.ts
> +				decompressable.length &&
```suggestion
				decompressable.length > 4 &&
```

2023-04-23 11:30 UTC, SuperchupuDev commented on packages/ws/src/ws/WebSocketShard.ts
> +			`useIdentifyCompress: ${this.useIdentifyCompression.toString()}`,
```suggestion
			`useIdentifyCompression: ${this.useIdentifyCompression.toString()}`,
```

2023-10-24 17:04 UTC, JMTK commented
Just a small followup to this issue:
I created a PR for `zlib-sync` that addresses it not compiling on NodeJS 21 https://github.com/abalabahaha/zlib-sync/pull/11

2024-05-03 13:06 UTC, didinele commented
closing in favor of a new PR since this has the branch on my fork and it's just a whole mess to work with.

2024-05-03 13:06 UTC, closed without merging