Fixed MessageReplyOptions
discordjs/discord.js pull request #9283
Opened 2023-03-27 18:35 UTC by BoogeyMan24

**Please describe the changes this PR makes and why it should be merged:**
Changed `BaseMessageCreateOptions` to `MessageCreateOptions` on line 822 in `discordjs/src/structures/Messages.js`.

Hopefully this fixes #9209.

I probably may have missed something, so if I did just send a comment and I will change it.

**Status and versioning classification:**
There are no code changes
This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-03-27 18:52 UTC, jaw0r3k commented
But it already have pr?

2023-03-27 19:03 UTC, BoogeyMan24 commented
I deleted stickers because MessageCreateOptions already has stickers.

2023-03-27 19:16 UTC, Jiralite requested changes
Extending `MessageCreateOptions` isn't correct. It now contains irrelevant properties such as `reply`, etc.

2023-03-27 19:17 UTC, BoogeyMan24 commented
Should I just then extend `BaseMessageOptions` and add everything except `reply`

2023-04-01 23:36 UTC, Jiralite commented
For purposes of deduplication, I would:

1. Create `BaseMessageCreateOptions` which has everything `MessageCreateOptions` has right now except `reply`.
2. Have `MessageCreateOptions` extend `BaseMessageCreateOptions` and add `reply`.
3. Create `MessageReplyOptions` and have it extend `BaseMessageCreateOptions` and add `failIfNotExists`.

2023-04-10 10:48 UTC, BoogeyMan24 commented
I added the changes for deduplication.

2023-04-10 11:37 UTC, jaw0r3k commented on packages/discord.js/src/structures/interfaces/TextBasedChannel.js
> +
```suggestion

```

2023-04-12 22:50 UTC, Jiralite approved these changes

2023-04-13 15:02 UTC, vladfrangu approved these changes

2023-04-13 15:04 UTC, kyranet approved these changes

2023-04-14 21:34 UTC, iCrawl approved these changes

2023-04-14 21:46 UTC, merged