chore: expand error feedback
discordjs/discord.js pull request #9325
Opened 2023-04-03 20:00 UTC by TetieWasTaken

**Please describe the changes this PR makes and why it should be merged:**
This PR adds more robust error checking in `Client#_validateOptions()` and `Client#generateInvite()`

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-04-13 15:10 UTC, vladfrangu approved these changes

2023-04-13 15:56 UTC, kyranet approved these changes

2023-04-14 14:29 UTC, Jiralite requested changes
This makes `allowedMentions` a required property. This is breaking.

2023-04-14 19:55 UTC, TetieWasTaken commented
Closing this in favour of #9390

2023-04-14 19:55 UTC, closed without merging