refactor(GuildMember): make _roles a getter and roles a normal prop
discordjs/discord.js pull request #9387
Opened 2023-04-14 12:28 UTC by Idris1401

**Please describe the changes this PR makes and why it should be merged:**

I think it would be better to have `GuildMember#roles` to be defined as a "normal" property (dunno what's the right term) instead of a getter and make `GuildMember#_roles` a getter.
People are often `console.log`ing data to get available properties and `._roles` does appear in the log and `.roles` doesn't which makes people using a private property.
I was also told that this change could cause performance issue but I still wanted to make this PR to know everyone's thought about it.

*I made another PR because I fucked up the branch in the old one.*

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2023-04-15 19:50 UTC, SpaceEEC requested changes
I'd prefer `_roles` to be made non-enumerable over this change here, which would require further considerations (e.g. updates for all members when a role is deleted)

2023-05-07 01:16 UTC, Jiralite commented
> People are often `console.log`ing data to get available properties and `._roles` does appear in the log and `.roles` doesn't which makes people using a private property.

Frankly, that's their fault. Additionally, the property is prefixed with `_` which is the convention for something that is private. I do not see this as a valid reason for this change. It instead seems like a reason to cater towards individuals that do not know what they are doing or know what they are doing is wrong.

Since #9529 landed, I am pretty sure this reverts the performance improvements.

2023-05-10 17:08 UTC, Idris1401 commented
> I'd prefer `_roles` to be made non-enumerable over this change here, which would require further considerations (e.g. updates for all members when a role is deleted)

what does "non-enumerable" mean?

2023-05-10 18:27 UTC, SpaceEEC commented
The `descriptor` parameter of [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) has an `enumerable` property, setting that to `false` is what I meant.
I think we are doing this with the `client` field in the `Base` class.

2023-05-10 19:01 UTC, Idris1401 commented
> The `descriptor` parameter of [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) has an `enumerable` property, setting that to `false` is what I meant. I think we are doing this with the `client` field in the `Base` class.

based on MDN, `enumerable` is default set to `false` so I didn't add it

2023-05-10 19:14 UTC, SpaceEEC requested changes

2023-05-10 19:14 UTC, SpaceEEC commented on packages/discord.js/src/structures/GuildMember.js
> +    Object.defineProperty(this, '_roles', { value: [] });
I think you also need to add `writable` there, otherwise assigning to it will throw. 😅

2023-05-14 11:21 UTC, vladfrangu approved these changes

2023-05-14 11:26 UTC, kyranet approved these changes

2023-05-18 10:08 UTC, SpaceEEC approved these changes

2023-05-18 10:13 UTC, merged