types(ModalSubmitFields): components is an array
discordjs/discord.js pull request #9406
Opened 2023-04-16 22:03 UTC by ImRodry

**Please describe the changes this PR makes and why it should be merged:**

This PR simply fixes an issue in ModalSubmitFields#components as it wasn't marked as an array and instead was simply an action row

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-04-16 22:04 UTC, ImRodry commented
Oh cool you're using teams now, just fyi github only officially assigns 2 members of the team at a time despite you all appearing on the side

2023-04-16 22:12 UTC, kyranet approved these changes

2023-04-16 22:16 UTC, kyranet submitted a review, later dismissed
Upon further inspection, I just noticed there's a mismatch in the types used. In the JS code, we use a custom interface (documented [here](https://old.discordjs.dev/#/docs/discord.js/main/typedef/ActionRowModalData)):

https://github.com/discordjs/discord.js/blob/e04801bba14ce2eb3a285f82449ae2ad051fbd8f/packages/discord.js/src/structures/ModalSubmitFields.js#L12-L16

`ActionRowModalData` is defined in the typings here:

https://github.com/discordjs/discord.js/blob/e04801bba14ce2eb3a285f82449ae2ad051fbd8f/packages/discord.js/typings/index.d.ts#L2218-L2221

However, this is using `ActionRow<ModalActionRowComponent>` instead.

2023-04-16 22:25 UTC, ImRodry commented
I didn't notice but yeah the type is wrong however I don't think that one is right either because that one technically indicates that you can chain `components.components` infinitely, despite the actual TextInputComponent object coming with a `components` property set to undefined. Should I just use that type and ignore this?

2023-04-16 22:26 UTC, kyranet commented
The types should match what the JS code is, unless the JS code is somehow wrong and has been for a year.

2023-04-16 22:29 UTC, ImRodry commented
The only thing "wrong" about the JS code is the fact that components is set as undefined on text input objects. I'll try to modify the types a little to match that

2023-04-16 22:30 UTC, ImRodry commented
Also I know how to fix that issue, can I include that in this PR?

2023-04-16 22:47 UTC, ImRodry commented
Pushed both the types change and a small change to the transformComponent function that should get rid of all the undefined properties to align it with the data returned by the API and the TS types. If you want me to remove that commit or move it to a different PR lmk

2023-05-14 11:28 UTC, vladfrangu approved these changes

2023-05-25 17:04 UTC, Jiralite approved these changes

2023-06-08 18:28 UTC, kyranet approved these changes

2023-06-08 18:37 UTC, almeidx requested changes

2023-06-08 18:39 UTC, ImRodry commented on packages/discord.js/src/structures/ModalSubmitInteraction.js
>     * @returns {ModalData[]}
I did not touch that. If it wasn’t private before I won’t make it private. Idk if I should fix this either

2023-06-09 09:55 UTC, SpaceEEC approved these changes

2023-06-09 10:23 UTC, Jiralite commented on packages/discord.js/src/structures/ModalSubmitInteraction.js
>     * @returns {ModalData[]}
This can be addressed in another pull request.

2023-06-13 18:58 UTC, merged