feat: Check for empty directory
discordjs/discord.js pull request #9539
Opened 2023-05-07 18:08 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Resolves #9537. Requiring a fresh directory (or a directory that is empty) rather than allowing some files to be present.

2023-05-07 18:41 UTC, jaw0r3k approved these changes

2023-05-07 18:54 UTC, SpaceEEC requested changes

2023-05-07 18:54 UTC, SpaceEEC commented on packages/create-discord-bot/src/create-discord-bot.ts
> +	console.error(chalk.red(`Please specify a non-empty directory.`));
I don't think that was correct 😅 

```suggestion
	console.error(chalk.red(`Please specify an empty directory.`));
```

2023-05-08 06:59 UTC, iCrawl approved these changes

2023-05-08 07:00 UTC, merged