fix(core): fix inconsistencies on `core`
discordjs/discord.js pull request #9680
Opened 2023-07-03 01:02 UTC by suneettipirneni

**Please describe the changes this PR makes and why it should be merged:**

This PR implements the changes outlined in #9618.

Additionally, I've removed `createForumThread` as it was essentially an alias for `createThread` just with types constrained to forum JSON payload options.

Closes #9618

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2023-07-03 07:10 UTC, vladfrangu commented
So what's the replacement of `createForumThread` now? Code wise that is

2023-07-05 00:48 UTC, vladfrangu requested changes

2023-07-05 00:48 UTC, vladfrangu commented on packages/core/src/api/channel.ts
> +	public async create(
Shouldn't this be createWebhook?

2023-07-06 11:30 UTC, Jiralite approved these changes

2023-07-06 13:33 UTC, kyranet approved these changes

2023-07-06 13:35 UTC, merged