fix(WebSocketShard): close errors not being catchable
discordjs/discord.js pull request #9704
Opened 2023-07-12 21:12 UTC by D4isDAVID

**Please describe the changes this PR makes and why it should be merged:**

Resolves #9621.

It seems like the errors could only occur when using `WebSocketShard#connect` (and I didn't want to modify much code), so my approach was to listen to the close event and throw the errors directly from `connect`, therefore making them catchable.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-07-12 21:52 UTC, didinele requested changes
Not fond of this approach and how it separates the close code handling at all.

I think I would much rather we keep it in the `onClose` method, swap out all the `throw`s for emitting `WebSocketShardEvents.Error` and instead leveraging `waitForEvent` inside of `connect`.

2023-07-14 10:31 UTC, D4isDAVID commented
> I think I would much rather we keep it in the `onClose` method, swap out all the `throw`s for emitting `WebSocketShardEvents.Error` and instead leveraging `waitForEvent` inside of `connect`.

Using `waitForEvent` would be a bit tricky no? It seems like other *recoverable* events can also happen when using `connect` and I don't see a way to use this function to ensure that the error is a close error. Should I maybe stick to using `once` from `node:events`?

2023-07-14 11:04 UTC, didinele commented
Yeah, just use `once`.

2023-07-14 11:17 UTC, D4isDAVID commented
I've ran into another issue where emitting `WebSocketShardEvents.Error` already causes `connect` to throw a catchable error (and as a result doesn't let me listen to it), but the error is for some reason `undefined`. I'll look into it later today.

2023-07-14 12:38 UTC, D4isDAVID commented
Turns out `once` handles error events, so I'll just use that.

2023-07-14 21:43 UTC, didinele requested changes

2023-07-14 21:43 UTC, didinele commented on packages/ws/src/ws/WebSocketShard.ts
> +			await promise?.catch(({ error }) => {
This is... very silly, we're in a `try` block and attach a `.catch` to the promise, just use a `catch` block instead.

2023-07-14 21:43 UTC, didinele commented on packages/ws/src/ws/WebSocketShard.ts
> +				return this.emit(WebSocketShardEvents.Error, {
Should emit, and then destroy with no recovery - same as all the other emits.

2023-07-15 08:03 UTC, didinele approved these changes

2023-07-15 08:05 UTC, vladfrangu commented
Does this work with the worker strategy too?

2023-07-15 08:08 UTC, didinele commented
Definitely not:

https://github.com/discordjs/discord.js/blob/8d9701745840e23854e8f0b057d21cb10e7d1d54/packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts#L221-L224

But that is way out of scope for this PR, I'll tackle that myself in the near future - lots of things the workers currently don't really forward or leave room to handle in the parent thread.

2023-07-15 08:12 UTC, vladfrangu approved these changes

2023-07-15 10:55 UTC, kyranet approved these changes

2023-07-15 10:55 UTC, merged