feat: user avatar decorations (v13)
discordjs/discord.js pull request #9710
Opened 2023-07-14 01:35 UTC by aiko-chan-ai

**Please describe the changes this PR makes and why it should be merged:**

v14: #8914 
Supersedes: #9018 

> Added:

- `User#avatarDecoration`
- `User#avatarDecorationURL()`

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR does not include any braking changes

2023-07-14 02:09 UTC, Jiralite approved these changes

2023-07-15 11:05 UTC, Syjalo approved these changes

2023-07-15 11:41 UTC, D4isDAVID requested changes

2023-07-15 11:41 UTC, D4isDAVID commented on typings/index.d.ts
> +      AvatarDecoration: (userId: Snowflake, hash: string, format: AllowedImageFormat, size: AllowedImageSize) => string;
```suggestion
      AvatarDecoration(userId: Snowflake, hash: string, format: AllowedImageFormat, size: AllowedImageSize): string;
```
You could make it fit with the rest of the endpoints here

2023-07-15 17:25 UTC, iCrawl approved these changes

2023-07-15 17:25 UTC, merged