refactor(REST): remove double classing
discordjs/discord.js pull request #9722
Opened 2023-07-17 08:54 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

We weren't exactly sure why this existed, it added extra complexity for no real reason.  The diff is a little unfortunate, sorry.
In order to help a little bit with this and my own sanity when doing this, all types were moved to a types util file.

BREAKING CHANGE: `REST` and `RequestManager` have been combined, most of the properties, methods, and events from both classes can now be found on `REST`
BREAKING CHANGE: `REST#raw` has been removed in favor of `REST#queueRequest`
BREAKING CHANGE: `REST#getAgent` has been removed in favor of `REST#agent`

This also fixes some issues that popped up in node 16 due to globals not being present.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

2023-07-17 11:25 UTC, suneettipirneni requested changes

2023-07-17 11:25 UTC, suneettipirneni commented on packages/rest/src/shared.ts
> +export * from './lib/REST.js';
`REST.js`is exported twice.
```suggestion
```

2023-07-17 12:04 UTC, vladfrangu requested changes

2023-07-24 20:06 UTC, suneettipirneni approved these changes

2023-07-24 20:32 UTC, vladfrangu approved these changes

2023-07-24 20:38 UTC, sdanialraza approved these changes

2023-07-25 00:23 UTC, Jiralite approved these changes

2023-07-25 08:40 UTC, didinele approved these changes

2023-07-25 08:40 UTC, merged