feat: add ws option support for "buildIdentifyThrottler"
discordjs/discord.js pull request #9728
Opened 2023-07-20 02:45 UTC by Deivu

**Please describe the changes this PR makes and why it should be merged:**
Adds support for custom identify throttlers

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2023-07-20 08:37 UTC, didinele approved these changes

2023-07-20 08:58 UTC, sdanialraza approved these changes

2023-07-20 11:32 UTC, Qjuh requested changes
Can you add documentation on `ClientOptions#ws` please? In `src/util/Options.js`.

2023-07-21 04:59 UTC, Deivu commented
> Can you add documentation on `ClientOptions#ws` please? In `src/util/Options.js`.

Resolved

2023-07-21 08:41 UTC, Qjuh requested changes

2023-07-21 08:41 UTC, Qjuh commented on packages/discord.js/src/util/Options.js
> + * (manager) => new SimpleIdentifyThrottler(concurrency);
Please adjust the example to reflect the default used in `@discordjs/ws` and not a hardcoded concurrency of 1.
https://github.com/discordjs/discord.js/blob/d26e022afcc84448bb91deb4dd621aea20df6617/packages/ws/src/utils/constants.ts#L32-L35

2023-07-21 20:05 UTC, 7xa5h approved these changes

2023-07-22 02:14 UTC, Deivu commented
Resolved

2023-07-22 06:18 UTC, Qjuh approved these changes

2023-07-22 07:08 UTC, kyranet approved these changes

2023-07-22 08:57 UTC, SpaceEEC approved these changes

2023-07-22 08:57 UTC, merged