feat: Support widget image URL
discordjs/discord.js pull request #9782
Opened 2023-08-18 15:15 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Supersedes #8589 in implementing the widget image URL.

Since the client does not need to be a member of any guild to return this method, I have placed the implementation on the `GuildManager`. I added helper methods to the `Guild` class and the `Widget` class for ease.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-08-18 19:15 UTC, SpaceEEC requested changes

2023-08-18 19:18 UTC, SpaceEEC approved these changes

2023-08-19 10:04 UTC, jaw0r3k commented
Shouldnt it be added to REST's cdn?

2023-08-19 12:23 UTC, Jiralite commented
It is not documented as a CDN endpoint.[^1]

[^1]: https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints

2023-09-09 17:40 UTC, vladfrangu approved these changes

2023-09-17 18:26 UTC, suneettipirneni approved these changes

2023-09-17 18:26 UTC, merged