fix(Webhook): do not call `client.deleteWebhook` in `delete`
discordjs/discord.js pull request #9786
Opened 2023-08-20 09:23 UTC by kyranet

**Please describe the changes this PR makes and why it should be merged:**

Partially reverts #9777 which caused a regression (#9785) when using `WebhookClient`.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-08-20 09:36 UTC, SpaceEEC approved these changes

2023-08-20 10:38 UTC, sdanialraza approved these changes

2023-08-20 11:49 UTC, Jiralite approved these changes

2023-09-06 15:05 UTC, Jiralite requested changes
On second thought, why not simply move the implementation from `Client` to `BaseClient`? There will be no need to duplicate the implementation in Webhook.js since `WebhookClient` and `Client` both extend `BaseClient`.

2023-11-05 18:12 UTC, Jiralite approved these changes

2023-11-05 18:19 UTC, vladfrangu approved these changes

2023-11-05 18:23 UTC, merged