refactor(TeamMember): deprecate permissions property
discordjs/discord.js pull request #9805
Opened 2023-08-24 12:29 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
https://github.com/discord/discord-api-docs/pull/6372

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-08-25 20:24 UTC, Jiralite requested changes

2023-08-25 20:24 UTC, Jiralite commented on packages/discord.js/src/structures/TeamMember.js
> +       * @deprecated
```suggestion
       * @deprecated Use {@link TeamMember#role} instead.
```

2023-08-25 20:24 UTC, Jiralite commented on packages/discord.js/typings/index.d.ts
> +  /** @deprecated */
```suggestion
  /** @deprecated Use {@link role} instead. */
```

2023-08-25 20:34 UTC, Jiralite approved these changes

2023-09-09 17:33 UTC, vladfrangu approved these changes

2023-09-15 18:15 UTC, SpaceEEC approved these changes

2023-09-15 18:18 UTC, merged