feat(cleanContent): add slash commands and emojis
discordjs/discord.js pull request #9809
Opened 2023-08-28 12:21 UTC by jaw0r3k

**Please describe the changes this PR makes and why it should be merged:**

- Supersedes: #9143

Expression suggested by vlad

<details>
<summary>Usage</summary>

![image](https://github.com/discordjs/discord.js/assets/76836550/20b9c512-eee2-4e1e-a480-9ef631382fea)

</details>

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

2023-09-09 17:30 UTC, vladfrangu submitted a review, later dismissed

2023-09-17 20:53 UTC, Jiralite requested changes

2023-09-17 20:53 UTC, Jiralite commented on packages/discord.js/src/util/Util.js
> +    /<(?:(?<type>@[!&]?|#)|(?:\/(?<commandName>[\w ]+)|a?:(?<emojiName>[\w]+)):)(?<id>\d{17,19})>/g,
Command names may be purely in another language:

```JavaScript
client.application.commands.create({
	name: "你",
	description: "你",
});
```

<img width="113" alt="image" src="https://github.com/discordjs/discord.js/assets/33201955/72619204-fdbb-4a8a-a435-91a4f7eb7ed7">

The raw result will be returned in this case (`</你:1153070376113410049>`). Perhaps the full regular expression for names is needed here.

2023-09-18 07:17 UTC, kyranet commented on packages/discord.js/src/util/Util.js
> +    /<(?:(?<type>@[!&]?|#)|(?:\/(?<commandName>[\w ]+)|a?:(?<emojiName>[\w]+)):)(?<id>\d{17,19})>/g,
We can probably use and/or export this:
https://github.com/discordjs/discord.js/blob/4588e075c3d0cd437b4057dbd2dde18639e98ae9/packages/builders/src/interactions/slashCommands/Assertions.ts#L11

2023-10-08 13:01 UTC, Jiralite requested changes
This now fails to match user mentions, channel mentions, role mentions, etc. This needs to be tested.

2023-10-08 13:35 UTC, Jiralite approved these changes

2023-10-24 10:49 UTC, vladfrangu approved these changes

2023-11-05 18:33 UTC, kyranet approved these changes

2023-11-05 18:36 UTC, merged